hopital_numerique_registre_homepage:
    pattern:  /annuaire-reseau
    defaults: { _controller: HopitalNumeriqueRegistreBundle:Ambassadeur:index }
        
hopital_numerique_registre_edit_session:
    pattern:  /annuaire-reseau/editer-session
    defaults: { _controller: HopitalNumeriqueRegistreBundle:Ambassadeur:editerSession }

hopital_numerique_registre_ambassadeur_objets:
    pattern:  /annuaire-reseau/show/objets/{id}
    defaults: { _controller: HopitalNumeriqueRegistreBundle:Ambassadeur:objets }
    requirements:
        id: \d+

hopital_numerique_registre_ambassadeur_domaines:
    pattern:  /annuaire-reseau/show/domaines/{id}
    defaults: { _controller: HopitalNumeriqueRegistreBundle:Ambassadeur:domaines }
    requirements:
        id: \d+

hopital_numerique_registre_ambassadeur_connaissance_si:
    pattern:  /annuaire-reseau/show/connaissance-si/{id}
    defaults: { _controller: HopitalNumeriqueRegistreBundle:Ambassadeur:connaissanceSI }
    requirements:
        id: \d+

hopital_numerique_user_informations_ambassadeurs:
    pattern:  /annuaire-reseau/download/ambassadeurs
    defaults: { _controller: HopitalNumeriqueRegistreBundle:Ambassadeur:downloadAmbassadeurs }
    requirements:
        id: \d+
