hopital_numerique_registre_homepage:
    pattern:  /{region}/{domaine}
    defaults: { _controller: HopitalNumeriqueRegistreBundle:Ambassadeur:index, region:null, domaine:null }

hopital_numerique_registre_ambassadeur_objets:
    pattern:  /objets/{id}
    defaults: { _controller: HopitalNumeriqueRegistreBundle:Ambassadeur:objets }
    requirements:
        id: \d+