hopital_numerique_registre_homepage:
    pattern:  /registre-ambassadeurs/{region}/{domaine}
    defaults: { _controller: HopitalNumeriqueRegistreBundle:Ambassadeur:index, region:null, domaine:null }
    requirements:
        _method: get

hopital_numerique_registre_ambassadeur_objets:
    pattern:  /registre-ambassadeurs/show/objets/{id}
    defaults: { _controller: HopitalNumeriqueRegistreBundle:Ambassadeur:objets }
    requirements:
        id: \d+
        _method: get

hopital_numerique_registre_ambassadeur_domaines:
    pattern:  /registre-ambassadeurs/show/domaines/{id}
    defaults: { _controller: HopitalNumeriqueRegistreBundle:Ambassadeur:domaines }
    requirements:
        id: \d+
        _method: get