services:
    new_account.profile.completion_calculator:
        class: HopitalNumerique\NewAccountBundle\Service\ProfileCompletionCalculator

    new_account.dashboard.widgets_aggregator:
        class: HopitalNumerique\NewAccountBundle\Service\Dashboard\WidgetsAggregator
        arguments:
            - '@translator'
            - '@dmishh.settings.settings_manager'
            - '@security.token_storage'

    new_account.dashboard.widgets.profile:
        class: HopitalNumerique\NewAccountBundle\Service\Widget\ProfileCompletionWidget
        tags:
            - { name: new_account.dashboard_widget, type: dashboard }
        arguments:
            - '@twig'
            - '@security.token_storage'
            - '@translator'
        calls:
            - [setProfileCompletionCalculator, ['@new_account.profile.completion_calculator']]
        public: false

    new_account.dashboard.command_handler.reorder:
        class: HopitalNumerique\NewAccountBundle\Domain\Command\ReorderDashboardHandler
        arguments:
            - '@dmishh.settings.settings_manager'

    HopitalNumerique\NewAccountBundle\Security\InformationsAccessVoter:
        class: HopitalNumerique\NewAccountBundle\Security\InformationsAccessVoter
        tags:
            - { name: security.voter }
        public: false

    HopitalNumerique\NewAccountBundle\Service\UserData\ContractWidget:
        class: HopitalNumerique\NewAccountBundle\Service\UserData\ContractWidget
        tags:
            - { name: new_account.dashboard_widget, type: user_informations, priority: 10 }
        arguments:
            - '@twig'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@translator'
            - '@hopitalnumerique_user.repository.contractualisation'
        public: false

    HopitalNumerique\NewAccountBundle\Service\UserData\PaymentWidget:
        class: HopitalNumerique\NewAccountBundle\Service\UserData\PaymentWidget
        tags:
            - { name: new_account.dashboard_widget, type: user_informations, priority: 30 }
        arguments:
            - '@twig'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@translator'
            - '@hopitalnumerique_paiement.manager.remboursement'
            - '@hopitalnumerique_intervention.manager.intervention_demande'
            - '@hopitalnumerique_module.manager.inscription'
            - '@hopitalnumerique_paiement.manager.facture'
        public: false

    HopitalNumerique\NewAccountBundle\Service\UserData\ActivityMonitoringWidget:
        class: HopitalNumerique\NewAccountBundle\Service\UserData\ActivityMonitoringWidget
        tags:
            - { name: new_account.dashboard_widget, type: user_informations, priority: 20 }
        arguments:
            - '@twig'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@translator'
            - '@hopitalnumerique_reference.manager.reference'
            - '@hopitalnumerique_expert.manager.activiteexpert'
        public: false
