parameters:
    fos_elastica.index_manager.class: HopitalNumerique\SearchBundle\Service\IndexManager

services:
    hopital_numerique_search.indexer_subscriber:
        class: HopitalNumerique\SearchBundle\EventListener\IndexerSubscriber
        arguments:
            - '@hopitalnumerique_publication.twig.publication_extension'
        tags:
            - { name: kernel.event_subscriber }

    hopital_numerique_search.config_factory:
        class: HopitalNumerique\SearchBundle\Service\ConfigFactory
        autowire: true
        arguments:
            3: '%search_engine_aggregations%'
