#Questionnaire
hopitalnumerique_questionnaire_edit:
    pattern:  /questionnaire/edit/{user}/{questionnaire}
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Questionnaire:edit", user: 1, questionnaire: 1 }
    requirements:
        user: \d+  
        questionnaire: \d+

hopitalnumerique_questionnaire_delete_all:
    pattern: /questionnaire/deleteAll
    defaults: { _controller: HopitalNumeriqueQuestionnaireBundle:Questionnaire:deleteAll }

#Question

#Réponse
hopitalnumerique_reponse_download:
    pattern: /reponse/download/{reponse}
    defaults: { _controller: HopitalNumeriqueQuestionnaireBundle:Reponse:dowloadReponse }
    requirements:
        reponse: \d+ 

hopitalnumerique_reponse_deleteAll:
    pattern: /reponse/deleteAll/{user}/{questionnaire}.{_format}
    defaults: { _controller: HopitalNumeriqueQuestionnaireBundle:Reponse:deleteAll, _format: json}
    requirements:
        user: \d+ 
        questionnaire: \d+  
        _method: post|delete
