#Questionnaire

hopitalnumerique_questionnaire_list:
    path:  /compte-hn/questionnaires
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Questionnaire:list"}
    methods: GET

#---Index - grid
hopitalnumerique_questionnaire_index:
    path:  /admin/questionnaire/gestion/index
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Questionnaire:indexQuestionnaire"}
    requirements:
        _method: GET|POST
#---Ajout
hopitalnumerique_questionnaire_add_questionnaire:
    path:  /admin/questionnaire/gestion/add
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Questionnaire:addQuestionnaire" }
#---Edition
hopitalnumerique_questionnaire_edit_questionnaire:
    path:  /admin/questionnaire/gestion/edit/{id}
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Questionnaire:editQuestionnaire", id: 1 }
    requirements:
        id: \d+
#---Delete
hopitalnumerique_questionnaire_delete_questionnaire:
    path:  /admin/questionnaire/gestion/delete/{id}
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Questionnaire:deleteQuestionnaire", id: 1 }
    requirements:
        id: \d+
#---Export CSV
hopitalnumerique_questionnaire_exportCSV_questionnaire:
    path:  /admin/questionnaire/gestion/exportcsv/{id}
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Questionnaire:exportCSV", id: 1 }
    requirements:
        id: \d+
#---Plugin pour les WYSIWYG
hopitalnumerique_questionnaire_get_questionnaires:
    path:  /admin//questionnaire/getQuestionnaires
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Questionnaire:getQuestionnaires" }
#---Front-office
hopitalnumerique_questionnaire_edit_front_gestionnaire:
    path:  /questionnaire/edit/{id}/{redirectReferer}
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Questionnaire:editFrontGestionnaire", id: 1, redirectReferer: false }
    requirements:
        id: \d+

hopitalnumerique_questionnaire_edit_front_gestionnaire_occurrence:
    path:  /questionnaire/edit/{questionnaire}/occ/{occurrence}
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Questionnaire:editFrontGestionnaireOccurrence" }
    requirements:
        questionnaire: \d+
        occurrence: \d+

# Back-office
hopitalnumerique_questionnaire_edit:
    path:  /admin/questionnaire/edit/{user}/{questionnaire}
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Questionnaire:edit", user: 1, questionnaire: 1 }
    requirements:
        user: \d+
        questionnaire: \d+

# Front-office
hopitalnumerique_questionnaire_edit_front:
    path:  /compte-hn/questionnaire/edit/{user}/{questionnaire}/{occurrence}
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Questionnaire:editFront", user: 1, questionnaire: 1, occurrence: null }
    requirements:
        user: \d+
        questionnaire: \d+

#Question
#---Index
hopitalnumerique_questionnaire_question_index:
    path:  /admin/questionnaire/{id}/question/index
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Question:index", id: 1}
    requirements:
        id: \d+
        _method: GET|POST
#---Add
hopitalnumerique_questionnaire_question_add:
    path:  /admin/questionnaire/question/add/view
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Question:addQuestion"}
    requirements:
        _method: GET|POST
#---Sauvegarde
hopitalnumerique_questionnaire_question_save:
    path:  /admin/questionnaire/question/{id}/save.{_format}
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Question:save", id: 1, _format: json}
    requirements:
        id: \d+
        _method: GET|POST
#---Edition
hopitalnumerique_questionnaire_question_edition:
    path:  /admin/questionnaire/question/edit/{id}/view
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Question:editView", id: 1}
    requirements:
        id: \d+
        _method: GET|POST
#---Delete
hopitalnumerique_questionnaire_question_delete:
    path:  /admin/questionnaire/question/delete/{id}.{_format}
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Question:delete", _format: json }
    requirements:
        id: \d+
        _method: POST|DELETE
#---Reorder
hopitalnumerique_questionnaire_question_reorder:
    path:  /admin/questionnaire/question/reorder.{_format}
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Question:reorder", id: 1, _format: json}
    requirements:
        id: \d+
        _method: GET|POST
#---Template file download
hopitalnumerique_questionnaire_question_download_template:
    path: /compte-hn/questionnaire/template/{question}
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Question:downloadTemplateFile" }

#Réponse
hopitalnumerique_reponse_download:
    path: /admin/reponse/download/{reponse}
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Reponse:dowloadReponse" }
    requirements:
        reponse: \d+

hopitalnumerique_reponse_deleteAll:
    path: /admin/reponse/deleteAll/{user}/{questionnaire}.{_format}
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Reponse:deleteAll", _format: json}
    requirements:
        user: \d+
        questionnaire: \d+

hopitalnumerique_reponse_deleteAllByQuestionnaire:
    path: /admin/questionnaire/reponse/deleteAllByQuestionnaire/{id}.{_format}
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Reponse:deleteAllByQuestionnaire", _format: json, id:1}
    requirements:
        id: \d+

# Occurrences
hopitalnumerique_questionnaire_occurrence_add:
    path:  /questionnaire/{questionnaire}/occ/add
    defaults: { _controller: "HopitalNumeriqueQuestionnaireBundle:Occurrence:add"}
    methods: GET
    requirements:
        questionnaire: \d+
