parameters:
    #Permet d'avoir une valeur par défaut et/ou d'etre surchargé par le config.yml de app/config
    hopitalnumerique_questionnaire.options: ~
    hopitalnumerique_questionnaire.options_config.class: HopitalNumerique\QuestionnaireBundle\Util\OptionsConfig
    #Questionnaire
    hopitalnumerique_questionnaire.manager.questionnaire.class: HopitalNumerique\QuestionnaireBundle\Manager\QuestionnaireManager
    hopitalnumerique_questionnaire.form.type.questionnaire: HopitalNumerique\QuestionnaireBundle\Form\Type\QuestionnaireType
    hopitalnumerique_questionnaire.grid.questionnaire.class: HopitalNumerique\QuestionnaireBundle\Grid\QuestionnaireGrid
    hopitalnumerique_questionnaire.form.type.questionnairegestion: HopitalNumerique\QuestionnaireBundle\Form\Type\QuestionnaireGestionType
    #Question
    hopitalnumerique_questionnaire.manager.question.class: HopitalNumerique\QuestionnaireBundle\Manager\QuestionManager
#    hopitalnumerique_questionnaire.form.type.question: HopitalNumerique\QuestionnaireBundle\Form\Type\QuestionType
    #Reponse
    hopitalnumerique_questionnaire.manager.reponse.class: HopitalNumerique\QuestionnaireBundle\Manager\ReponseManager
#    hopitalnumerique_questionnaire.form.type.reponse: HopitalNumerique\QuestionnaireBundle\Form\Type\ReponseType
    #Type de question
    hopitalnumerique_questionnaire.manager.typequestion.class: HopitalNumerique\QuestionnaireBundle\Manager\TypeQuestionManager
    #Extensions twig
    hopitalnumerique_questionnaire.twig.extensions.class: HopitalNumerique\QuestionnaireBundle\Twig\QuestionnaireExtension
    #Occurrence : 
    hopitalnumerique_questionnaire.form.type.occurrence.class: HopitalNumerique\QuestionnaireBundle\Form\Type\OccurrenceType
    hopitalnumerique_questionnaire.manager.occurrence.class : HopitalNumerique\QuestionnaireBundle\Manager\OccurrenceManager

services:
    #--OptionsConfig
    hopitalnumerique_questionnaire.options:
        class: "%hopitalnumerique_questionnaire.options_config.class%"
        arguments: ["%hopitalnumerique_questionnaire.options%"]
    #Questionnaire:
    #--Manager
    hopitalnumerique_questionnaire.manager.questionnaire:
        class: "%hopitalnumerique_questionnaire.manager.questionnaire.class%"
        arguments: ["@doctrine.orm.entity_manager", "@hopitalnumerique_questionnaire.manager.occurrence", "@hopitalnumerique_questionnaire.manager.reponse", "@hopitalnumerique_user.manager.user", "@hopitalnumerique_etablissement.manager.etablissement", "@router", "%hopitalnumerique_questionnaire.options%"]
    #--Type
    hopitalnumerique_questionnaire.form.type.questionnaire:
        class: "%hopitalnumerique_questionnaire.form.type.questionnaire%"
        arguments: ["@hopitalnumerique_questionnaire.form.type.occurrence", "@hopitalnumerique_questionnaire.manager.reponse", "@hopitalnumerique_questionnaire.manager.questionnaire", "@hopitalnumerique_questionnaire.manager.occurrence", "@hopitalnumerique_user.manager.user", "@router"]
        tags:
            - { name: form.type, alias: nodevo_questionnaire_questionnaire }
    #-Gestion des questionnaires
    #--Grid
    hopitalnumerique_questionnaire.grid.questionnaire:
        class: %hopitalnumerique_questionnaire.grid.questionnaire.class%
        arguments: ["@service_container"]
    #--Type
    hopitalnumerique_questionnaire.form.type.questionnairegestion:
        class: "%hopitalnumerique_questionnaire.form.type.questionnairegestion%"
        arguments: ["@hopitalnumerique_questionnaire.manager.questionnaire", "@validator", "@hopitalnumerique_user.manager.user"]
        tags:
            - { name: form.type, alias: hopitalnumerique_questionnaire_gestion_questionnaire }
    #Question:
    #--Manager
    hopitalnumerique_questionnaire.manager.question:
        class: "%hopitalnumerique_questionnaire.manager.question.class%"
        arguments: ["@doctrine.orm.entity_manager"]
    #Reponse:
    #--Manager
    hopitalnumerique_questionnaire.manager.reponse:
        class: "%hopitalnumerique_questionnaire.manager.reponse.class%"
        arguments: ["@doctrine.orm.entity_manager"]
    #TypeQuestion:
    #--Manager
    hopitalnumerique_questionnaire.manager.typequestion:
        class: "%hopitalnumerique_questionnaire.manager.typequestion.class%"
        arguments: ["@doctrine.orm.entity_manager"]
    #Occurrence
    hopitalnumerique_questionnaire.form.type.occurrence:
        class: "%hopitalnumerique_questionnaire.form.type.occurrence.class%"
        tags:
            - { name: form.type, alias: nodevo_questionnaire_occurrence }
    hopitalnumerique_questionnaire.manager.occurrence:
        class: "%hopitalnumerique_questionnaire.manager.occurrence.class%"
        arguments: ["@doctrine.orm.entity_manager"]
    #Extension Twig        
    hopitalnumerique_questionnaire.twig.questionnaire_extension:
        class: %hopitalnumerique_questionnaire.twig.extensions.class%
        tags:
            - { name: twig.extension }

    hopitalnumerique_questionnaire.repository.response:
        class: HopitalNumerique\QuestionnaireBundle\Repository\ReponseRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumeriqueQuestionnaireBundle:Reponse'

    HopitalNumerique\QuestionnaireBundle\Repository\QuestionnaireRepository:
        class: HopitalNumerique\QuestionnaireBundle\Repository\QuestionnaireRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumeriqueQuestionnaireBundle:Questionnaire'


    hopitalnumerique_questionnaire.widget.survey:
        class: HopitalNumerique\QuestionnaireBundle\Service\Widget\SurveyWidget
        tags:
            - { name: new_account.dashboard_widget, type: service, priority: 30 }
        arguments:
            - '@twig'
            - '@security.token_storage'
            - '@translator'
            - '@router'
            - '@hopitalnumerique_questionnaire.repository.response'
            - '@hopitalnumerique_domaine.service.base_url_provider'
            - '@hopitalnumerique_domaine.dependency_injection.current_domaine'
        public: false
