#partie Objet
hopitalnumerique_objet_objet:
    path:  /objet
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:index" }

hopitalnumerique_objet_back_risk:
    prefix: /risques
    resource: routing/back/risk.yml

hopitalnumerique_objet_back_related_risk:
    prefix: /related-risks/
    resource: routing/back/related_risks.yml

hopitalnumerique_objet_objet_filtre:
    path:  /objet-avec-filtre/{filtre}/{domain}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:indexFiltre", domain: null }

hopitalnumerique_objet_objet_add:
    path:  /objet/add/{type}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:add", type:1 }

hopitalnumerique_objet_objet_isFileExist:
    path:  /objet/isFileExist
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:isFileExist" }

hopitalnumerique_objet_objet_getObjets:
    path:  /objet/getObjets
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:getObjets" }

hopitalnumerique_objet_objet_getObjets_by_domaine:
    path:  /objet/getObjetsByDomaine
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:getObjetsByDomaine" }

hopitalnumerique_objet_objet_getPublications:
    path:  /objet/getPublications/{articles}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:getPublications", articles:1 }

hopitalnumerique_objet_objet_getPublicationDetailsForMenu:
    path:  /objet/getPublicationDetailsForMenu
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:getPublicationDetailsForMenu" }

hopitalnumerique_objet_objet_cancel:
    path:  /objet/cancel/{id}/{message}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:cancel", message:null }

hopitalnumerique_objet_objet_cancel_with_filtre:
    path:  /objet/cancelwithfiltre/{id}/{message}/{filtre}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:cancelWithFiltre",message:null}

hopitalnumerique_objet_objet_show:
    path:  /objet/show/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:show", id:1 }
    requirements:
        id: \d+

hopitalnumerique_objet_objet_edit:
    path:  /objet/edit/{id}/{infra}/{toRef}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:edit", id:1, infra:0, toRef:0  }
    requirements:
        id: \d+

hopitalnumerique_objet_objet_delete:
    path:  /objet/delete/{id}.{_format}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:delete", _format: json }
    requirements: 
        id: \d+

hopitalnumerique_objet_objet_reportPopin:
    path: /objet/report/{object}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:reportPopin" }
    requirements:
        id: \d+

#Partie Link
hopitalnumerique_objet_objet_addLink:
    path:  /objet/addLink/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Link:addLink" }
    requirements: 
        id: \d+

hopitalnumerique_objet_objet_ad_discussion_link:
    path:  /objet/addLink/discussion/{object}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Link:linkDiscussion" }
    requirements:
        id: \d+

hopitalnumerique_objet_board_addLink:
    path:  /objet/board/addLink/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Back/Objet/RelatedBoard:addLink" }
    requirements:
        id: \d+

hopitalnumerique_objet_objet_saveLink:
    path:  /objet/saveLink
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Link:saveLink" }

hopitalnumerique_objet_board_saveLink:
    path:  /objet/board/saveLink
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Back/Objet/RelatedBoard:saveLink" }

hopitalnumerique_objet_board_deleteLink:
    path:  /objet/board/deleteLink/{object}/{board}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Back/Objet/RelatedBoard:deleteLink" }
    requirements:
        object: \d+
        board: \d+

hopitalnumerique_objet_objet_reorder:
    path:  /objet/reorder/{object}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Link:reorder" }
    requirements: 
        id: \d+

hopitalnumerique_objet_objet_remove_link:
    path:  /objet/remove/{source}/{target}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Link:removeLink" }

#partie Contenu
hopitalnumerique_objet_contenu_add:
    path:  /objet/contenu/add/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Contenu:add", id:1 }
    requirements:
        id: \d+

hopitalnumerique_objet_contenu_form:
    path:  /objet/contenu/form/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Contenu:form", id:1}
    requirements:
        id: \d+

hopitalnumerique_objet_contenu_edit:
    path:  /objet/contenu/edit/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Contenu:edit", id:1}
    requirements:
        id: \d+

hopitalnumerique_objet_contenu_delete:
    path:  /objet/contenu/delete/{id}.{_format}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Contenu:delete", _format: json }
    requirements: 
        id: \d+

hopitalnumerique_objet_contenu_delete_all:
    path:  /objet/contenu/delete-all/{object}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Contenu:deleteAllForObject" }

hopitalnumerique_objet_contenu_uploadparse:
    path:  /objet/contenu/upload/parse/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Contenu:uploadParse", id:1 }
    requirements: 
        id: \d+

hopitalnumerique_objet_contenu_upload:
    path:  /objet/contenu/upload
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Contenu:upload" }

hopitalnumerique_objet_contenu_reorder:
    path:  /objet/contenu/reorder
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Contenu:reorder" }

hopitalnumerique_objet_infradoc_related_production:
    path: /objet/contenu/form/{content}/related-productions
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Contenu:relatedProduction" }

#---Commentaire
hopitalnumerique_objet_admin_commentaire:
    path:  /objet/commentaire
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Commentaire:index" }
    requirements: 
        _method: GET|POST

hopitalnumerique_objet_admin_commentaire_edit:
    path:  /objet/commentaire/edit/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Commentaire:edit" }
    requirements:
        id: \d+
        _method: GET|POST

hopitalnumerique_objet_admin_commentaire_toggle_publication:
    path:  /objet/commentaire/toggle-publication/{id}.{_format}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Commentaire:togglePublication", _format: json }
    requirements: 
        id: \d+
        _method: POST|GET

hopitalnumerique_objet_admin_commentaire_delete:
    path:  /objet/commentaire/delete/{id}.{_format}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Commentaire:delete", _format: json }
    requirements: 
        id: \d+
        _method: POST|DELETE

#Temporaire
hopitalnumerique_objet_administration_fichierModifiable:
    path:  /objet/administration/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:FichierModifiable:index" }
    requirements: 
        _method: GET|POST
