#partie Objet
hopitalnumerique_objet_objet:
    pattern:  /objet
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:index" }

hopitalnumerique_objet_objet_add:
    pattern:  /objet/add/{type}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:add", type:1 }

hopitalnumerique_objet_objet_isFileExist:
    pattern:  /objet/isFileExist
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:isFileExist" }

hopitalnumerique_objet_objet_getObjets:
    pattern:  /objet/getObjets
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:getObjets" }

hopitalnumerique_objet_objet_getPublications:
    pattern:  /objet/getPublications/{articles}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:getPublications", articles:1 }

hopitalnumerique_objet_objet_getPublicationDetailsForMenu:
    pattern:  /objet/getPublicationDetailsForMenu
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:getPublicationDetailsForMenu" }

hopitalnumerique_objet_objet_cancel:
    pattern:  /objet/cancel/{id}/{message}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:cancel", message:null }

hopitalnumerique_objet_objet_show:
    pattern:  /objet/show/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:show", id:1 }
    requirements:
        id: \d+

hopitalnumerique_objet_objet_edit:
    pattern:  /objet/edit/{id}/{infra}/{toRef}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:edit", id:1, infra:0, toRef:0  }
    requirements:
        id: \d+

hopitalnumerique_objet_objet_delete:
    pattern:  /objet/delete/{id}.{_format}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Objet:delete", _format: json }
    requirements: 
        id: \d+

#Partie Link
hopitalnumerique_objet_objet_addLink:
    pattern:  /objet/addLink/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Link:addLink" }
    requirements: 
        id: \d+

hopitalnumerique_objet_objet_saveLink:
    pattern:  /objet/saveLink
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Link:saveLink" }

hopitalnumerique_objet_objet_deleteLink:
    pattern:  /objet/deleteLink/{pointDur}/{id}/{obj}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Link:deleteLink" }
    requirements: 
        id: \d+
        pointDur: \d+

hopitalnumerique_objet_objet_reorder:
    pattern:  /objet/reorder/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Link:reorder" }
    requirements: 
        id: \d+

#partie Contenu
hopitalnumerique_objet_contenu_add:
    pattern:  /objet/contenu/add/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Contenu:add", id:1 }
    requirements:
        id: \d+

hopitalnumerique_objet_contenu_form:
    pattern:  /objet/contenu/form/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Contenu:form", id:1}
    requirements:
        id: \d+

hopitalnumerique_objet_contenu_edit:
    pattern:  /objet/contenu/edit/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Contenu:edit", id:1}
    requirements:
        id: \d+

hopitalnumerique_objet_contenu_delete:
    pattern:  /objet/contenu/delete/{id}.{_format}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Contenu:delete", _format: json }
    requirements: 
        id: \d+

hopitalnumerique_objet_contenu_uploadparse:
    pattern:  /objet/contenu/upload/parse/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Contenu:uploadParse", id:1 }
    requirements: 
        id: \d+

hopitalnumerique_objet_contenu_upload:
    pattern:  /objet/contenu/upload
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Contenu:upload" }

hopitalnumerique_objet_contenu_reorder:
    pattern:  /objet/contenu/reorder
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Contenu:reorder" }

#partie reference
hopitalnumerique_objet_reference_objet:
    pattern:  /objet/reference/objet/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Reference:objet", id:1 }
    requirements:
        id: \d+

hopitalnumerique_objet_reference_objet_own:
    pattern:  /objet/reference/objet-own/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Reference:objetOwn", id:1 }
    requirements:
        id: \d+

hopitalnumerique_objet_reference_objet_save:
    pattern:  /objet/reference/save/objet/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Reference:saveObjet" }
    requirements:
        id: \d+

hopitalnumerique_objet_reference_contenu:
    pattern:  /objet/reference/contenu/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Reference:contenu", id:1 }
    requirements:
        id: \d+

hopitalnumerique_objet_reference_contenu_own:
    pattern:  /objet/reference/contenu_own/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Reference:contenuOwn", id:1 }
    requirements:
        id: \d+

hopitalnumerique_objet_reference_contenu_save:
    pattern:  /objet/reference/save/contenu
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Reference:saveContenu" }

#---Commentaire
hopitalnumerique_objet_admin_commentaire:
    pattern:  /objet/commentaire
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Commentaire:index" }
    requirements: 
        _method: GET|POST

hopitalnumerique_objet_admin_commentaire_edit:
    pattern:  /objet/commentaire/edit/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Commentaire:edit" }
    requirements:
        id: \d+
        _method: GET|POST

hopitalnumerique_objet_admin_commentaire_toggle_publication:
    pattern:  /objet/commentaire/toggle-publication/{id}.{_format}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Commentaire:togglePublication", _format: json }
    requirements: 
        id: \d+
        _method: POST|GET

hopitalnumerique_objet_admin_commentaire_delete:
    pattern:  /objet/commentaire/delete/{id}.{_format}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Commentaire:delete", _format: json }
    requirements: 
        id: \d+
        _method: POST|DELETE

#Temporaire
hopitalnumerique_objet_administration_fichierModifiable:
    pattern:  /objet/administration/{id}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:FichierModifiable:index" }
    requirements: 
        _method: GET|POST