parameters:
    #Permet d'avoir une valeur par défaut et/ou d'etre surchargé par le config.yml de app/config
    hopital_numerique_recherche.options:
    hopitalnumerique_recherche.manager.search.class               : HopitalNumerique\RechercheBundle\Manager\SearchManager
    hopitalnumerique_recherche.manager.requete.class              : HopitalNumerique\RechercheBundle\Manager\RequeteManager
    hopitalnumerique_recherche.manager.statClic.class             : HopitalNumerique\RechercheBundle\Manager\StatClicManager
    hopitalnumerique_recherche.manager.expbesoin.class            : HopitalNumerique\RechercheBundle\Manager\ExpBesoinManager
    hopitalnumerique_recherche.manager.expbesoinreponses.class    : HopitalNumerique\RechercheBundle\Manager\ExpBesoinReponsesManager
    hopitalnumerique_recherche.manager.refexpbesoinreponses.class : HopitalNumerique\RechercheBundle\Manager\RefExpBesoinReponsesManager
    hopitalnumerique_recherche.service.logger.cronlogger.class    : HopitalNumerique\RechercheBundle\DependencyInjection\Logger\CronLogger
    #Gestionnaire
    hopitalnumerique_recherche.manager.expbesoingestion.class : HopitalNumerique\RechercheBundle\Manager\ExpBesoinGestionManager
    hopitalnumerique_recherche.grid.expbesoingestion.class    : HopitalNumerique\RechercheBundle\Grid\ExpBesoinGestionGrid
    hopitalnumerique_recherche.form.expbesoingestion.class    : HopitalNumerique\RechercheBundle\Form\ExpBesoinGestionType

services:
    hopitalnumerique_recherche.manager.search:
        class: %hopitalnumerique_recherche.manager.search.class%
        arguments: ["@hopitalnumerique_objet.manager.refobjet", "@hopitalnumerique_objet.manager.refcontenu", "@hopitalnumerique_forum.manager.reftopic", "@ccdn_forum_forum.component.security.authorizer", "%hopital_numerique_recherche.options%"]

    hopitalnumerique_recherche.manager.requete:
        class: %hopitalnumerique_recherche.manager.requete.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
           - [ setCache, [ @liip_doctrine_cache.ns.main ] ]

    hopitalnumerique_recherche.manager.expbesoin:
        class: %hopitalnumerique_recherche.manager.expbesoin.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
           - [ setCache, [ @liip_doctrine_cache.ns.main ] ]

    hopitalnumerique_recherche.manager.expbesoinreponses:
        class: %hopitalnumerique_recherche.manager.expbesoinreponses.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
           - [ setCache, [ @liip_doctrine_cache.ns.main ] ]

    hopitalnumerique_recherche.manager.refexpbesoinreponses:
        class: %hopitalnumerique_recherche.manager.refexpbesoinreponses.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
           - [ setCache, [ @liip_doctrine_cache.ns.main ] ]

    hopitalnumerique_recherche.manager.statClic:
        class: %hopitalnumerique_recherche.manager.statClic.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
           - [ setCache, [ @liip_doctrine_cache.ns.main ] ]

    hopitalnumerique_recherche.service.logger.cronlogger:
        class: "%hopitalnumerique_recherche.service.logger.cronlogger.class%"
        arguments: ["@logger", "@session"]

    #Gestionnaire
    hopitalnumerique_recherche.manager.expbesoingestion:
        class: %hopitalnumerique_recherche.manager.expbesoingestion.class%
        arguments: ["@doctrine.orm.entity_manager", "@hopitalnumerique_user.manager.user"]
        calls:
           - [ setCache, [ @liip_doctrine_cache.ns.main ] ]

    hopitalnumerique_recherche.grid.expbesoingestion:
        class: %hopitalnumerique_recherche.grid.expbesoingestion.class%
        arguments: ["@service_container"]

    hopitalnumerique_recherche.form.expbesoingestion:
        class: %hopitalnumerique_recherche.form.expbesoingestion.class%
        arguments: ["@hopitalnumerique_recherche.manager.expbesoingestion", "@validator", "@hopitalnumerique_user.manager.user"]
        tags:
            - { name: form.type, alias: hopitalnumerique_recherche_expbesoingestion }