parameters:
    hopitalnumerique_recherche.manager.search.class: HopitalNumerique\RechercheBundle\Manager\SearchManager
    hopitalnumerique_recherche.manager.requete.class: HopitalNumerique\RechercheBundle\Manager\RequeteManager
    hopitalnumerique_recherche.service.logger.cronlogger.class: HopitalNumerique\RechercheBundle\DependencyInjection\Logger\CronLogger

services:
    hopitalnumerique_recherche.manager.search:
        class: %hopitalnumerique_recherche.manager.search.class%
        arguments: ["@hopitalnumerique_objet.manager.refobjet", "@hopitalnumerique_objet.manager.refcontenu", "@hopitalnumerique_forum.manager.reftopic", "@ccdn_forum_forum.component.security.authorizer"]

    hopitalnumerique_recherche.manager.requete:
        class: %hopitalnumerique_recherche.manager.requete.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
           - [ setCache, [ @liip_doctrine_cache.ns.main ] ]

    hopitalnumerique_recherche.service.logger.cronlogger:
        class: "%hopitalnumerique_recherche.service.logger.cronlogger.class%"
        arguments: ["@logger", "@session"]