parameters:
    hopitalnumerique_recherche.manager.search.class: HopitalNumerique\RechercheBundle\Manager\SearchManager
    hopitalnumerique_recherche.manager.requete.class: HopitalNumerique\RechercheBundle\Manager\RequeteManager
    hopitalnumerique_recherche.manager.expbesoin.class: HopitalNumerique\RechercheBundle\Manager\ExpBesoinManager
    hopitalnumerique_recherche.manager.expbesoinreponses.class: HopitalNumerique\RechercheBundle\Manager\ExpBesoinReponsesManager
    hopitalnumerique_recherche.manager.refexpbesoinreponses.class: HopitalNumerique\RechercheBundle\Manager\RefExpBesoinReponsesManager
    hopitalnumerique_recherche.service.logger.cronlogger.class: HopitalNumerique\RechercheBundle\DependencyInjection\Logger\CronLogger

services:
    hopitalnumerique_recherche.manager.search:
        class: %hopitalnumerique_recherche.manager.search.class%
        arguments: ["@hopitalnumerique_objet.manager.refobjet", "@hopitalnumerique_objet.manager.refcontenu", "@hopitalnumerique_forum.manager.reftopic"]

    hopitalnumerique_recherche.manager.requete:
        class: %hopitalnumerique_recherche.manager.requete.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
           - [ setCache, [ @liip_doctrine_cache.ns.main ] ]

    hopitalnumerique_recherche.manager.expbesoin:
        class: %hopitalnumerique_recherche.manager.expbesoin.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
           - [ setCache, [ @liip_doctrine_cache.ns.main ] ]

    hopitalnumerique_recherche.manager.expbesoinreponses:
        class: %hopitalnumerique_recherche.manager.expbesoinreponses.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
           - [ setCache, [ @liip_doctrine_cache.ns.main ] ]

    hopitalnumerique_recherche.manager.refexpbesoinreponses:
        class: %hopitalnumerique_recherche.manager.refexpbesoinreponses.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
           - [ setCache, [ @liip_doctrine_cache.ns.main ] ]

    hopitalnumerique_recherche.service.logger.cronlogger:
        class: "%hopitalnumerique_recherche.service.logger.cronlogger.class%"
        arguments: ["@logger", "@session"]