# Hérite de CCDNForum
services:
    ccdn_forum_forum.form.type.post_update:
        class: '%ccdn_forum_forum.form.type.post_update.class%'
        arguments:
            - '%ccdn_forum_forum.entity.post.class%'
            - '@security.authorization_checker'
            - '@hopitalnumerique_forum.manager.topic'
