hopitalnumerique_reference_glossaire_list:
    pattern: '/glossaire'
    defaults: { _controller: 'HopitalNumeriqueReferenceBundle:Glossaire:list' }
    methods: 'get'

hopitalnumerique_reference_glossaire_list_full:
    pattern: '/glossaire/complet'
    defaults: { _controller: 'HopitalNumeriqueReferenceBundle:Glossaire:listFull' }
    methods: 'get'

hopitalnumerique_reference_glossaire_migre:
    pattern: '/admin/glossaire/migre/{token}'
    defaults: { _controller: 'HopitalNumeriqueReferenceBundle:Glossaire:migre' }
    methods: 'get'

hopitalnumerique_reference_glossaire_parse:
    pattern: '/glossaire/parse/{token}'
    defaults: { _controller: 'HopitalNumeriqueReferenceBundle:Glossaire:parse' }
    methods: 'get'

hopitalnumerique_reference_glossaire_popin:
    pattern: '/glossaire/popin/{glossaireReference}'
    defaults: { _controller: 'HopitalNumeriqueReferenceBundle:Glossaire:popin' }
    methods: 'get'
    requirements:
        glossaireReference: '\d+'
