hopitalnumerique_reference_referencement_popin:
    path: '/referencement/popin/{entityType}/{entityId}/{redirect}'
    defaults: { _controller: 'HopitalNumeriqueReferenceBundle:Referencement:popin', "redirect": true }
    methods: 'get'

hopitalnumerique_reference_referencement_popin_user:
    path: '/user-referencement'
    defaults: { _controller: 'HopitalNumeriqueReferenceBundle:Referencement:userPopin' }

hopitalnumerique_reference_referencement_savechosenreferences:
    path: '/referencement/popin/{entityType}/{entityId}/savechosenreferences'
    defaults: { _controller: 'HopitalNumeriqueReferenceBundle:Referencement:saveChosenReferences' }
    methods: 'post'

hopitalnumerique_reference_referencement_cronsavenotes:
    path: '/referencement/cron-save-notes/{token}'
    defaults: { _controller: 'HopitalNumeriqueReferenceBundle:Referencement:cronSaveNotes' }
    methods: 'get'

hopitalnumerique_reference_referencement_cronremoveinexistants:
    path: '/referencement/cron-remove-inexistants/{token}'
    defaults: { _controller: 'HopitalNumeriqueReferenceBundle:Referencement:cronRemoveInexistants' }
    methods: 'get'

hopitalnumerique_reference_referencement_migre:
    path: '/admin/referencement/migre/{token}'
    defaults: { _controller: 'HopitalNumeriqueReferenceBundle:Referencement:migre' }
    methods: 'get'
