services:
    hopitalnumerique_reference.repository.reference:
        class: 'HopitalNumerique\ReferenceBundle\Repository\ReferenceRepository'
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumeriqueReferenceBundle:Reference'

    hopitalnumerique_reference.repository.entity_has_reference:
        class: 'HopitalNumerique\ReferenceBundle\Repository\EntityHasReferenceRepository'
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumeriqueReferenceBundle:EntityHasReference'

    hopitalnumerique_reference.repository.reference_code:
        class: 'HopitalNumerique\ReferenceBundle\Repository\ReferenceCodeRepository'
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumeriqueReferenceBundle:ReferenceCode'

    hopitalnumerique_reference.repository.hobby:
        class: 'HopitalNumerique\ReferenceBundle\Repository\HobbyRepository'
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumeriqueReferenceBundle:Reference\Hobby'
