parameters:
    #Extensions twig
    nodevo_tools.twig.extensions.class: Nodevo\ToolsBundle\Twig\ToolsExtension

services:
    #Extension Twig        
    nodevo_tools.twig.tools_extension:
        class: %nodevo_tools.twig.extensions.class%
        tags:
            - { name: twig.extension }

    #Champ de formulaire
    form.type.nodevocommentaire:
        class: Nodevo\ToolsBundle\Form\Type\NodevoCommentaireType
        tags:
            -  { name: form.type, alias: nodevocommentaire }
