<?php

namespace HopitalNumerique\ReportBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends EntityRepository
{
	/**
     * Récupère les données du grid sous forme de tableau correctement formaté
     *
     * @return array
     * 
     * @author Alexis VAILLANT
     * @copyright Nodevo
     */
    public function getDatasForGrid($domainesIds, \StdClass $condition = null )
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('rep.id, 
        			 rep.date,
                     user.id as userId,
                     user.nom as userNom,
                     user.prenom as userPrenom,
                     user.email as userMail,
                     rep.observations,
                     rep.archive,
                     rep.url,
                     rep.userAgent,
                     domaine.nom as domaineNom')
            ->from('HopitalNumeriqueReportBundle:Report', 'rep')
            ->innerJoin('rep.user','user')
            ->leftJoin('rep.domaines', 'domaine')
                ->where($qb->expr()->orX(
                    $qb->expr()->in('domaine.id', ':domainesId'),
                    $qb->expr()->isNull('domaine.id')
                ))
            ->setParameter('domainesId', $domainesIds);
    
        return $qb;
    }
}
