# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - NodevoAdminBundle
        - NodevoMenuBundle
        - NodevoGridBundle
        - NodevoAclBundle
        - NodevoRoleBundle
        - NodevoMailBundle
        - NodevoFaqBundle
        - NodevoContactBundle
        - NodevoGestionnaireMediaBundle
        - NodevoCookieBundle
        - NodevoTexteDynamiqueBundle
        - HopitalNumeriqueAdminBundle
        - HopitalNumeriqueExpertBundle
        - HopitalNumeriqueInterventionBundle
        - HopitalNumeriqueUserBundle
        - HopitalNumeriqueReferenceBundle
        - HopitalNumeriqueEtablissementBundle
        - HopitalNumeriqueCoreBundle
        - HopitalNumeriqueModuleBundle
        - HopitalNumeriqueObjetBundle
        - HopitalNumeriqueQuestionnaireBundle
        - HopitalNumeriqueAccountBundle
        - HopitalNumeriqueRechercheBundle
        - HopitalNumeriqueRechercheParcoursBundle
        - HopitalNumeriqueRegistreBundle
        - HopitalNumeriquePublicationBundle
        - HopitalNumeriqueFaqBundle
        - HopitalNumeriqueStatBundle
        - HopitalNumeriquePaiementBundle
        - HopitalNumeriqueAutodiagBundle
        - HopitalNumeriqueImportExcelBundle
        - HopitalNumeriqueForumBundle
        - HopitalNumeriqueFlashBundle
        - HopitalNumeriqueGlossaireBundle
        - HopitalNumeriqueReportBundle
        - HopitalNumeriqueDomaineBundle
        - HopitalNumeriqueCommunautePratiqueBundle
        - CCDNForumForumBundle
        - FOSUserBundle
    filters:
        cssrewrite: ~
        cssembed:
            jar: %kernel.root_dir%/Resources/java/cssembed-0.4.5.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar
    assets:
        #JS
        bbcode_js: 
            inputs:
                - '%kernel.root_dir%/../vendor/codeconsortium/ccdn-component-bb-code/src/CCDNComponent/BBCode/Resources/public/js/jquery.bbeditor.js'
            filters : [ ?yui_js ]
        tinymce_js:
            inputs:
                - "bundles/nodevotools/js/tinymce/tinymce.min.js"
                - "bundles/nodevotools/js/tinymce/tinymce.fr_FR.js"
                - "bundles/hopitalnumeriquecore/js/tinymce.js"
            filters : [ ?yui_js ]
        jquery_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/jquery/dist/jquery.min.js"
            filters : [ ?yui_js ]
        jquery_ui_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/jquery-ui/ui/minified/jquery-ui.min.js"
                - "%kernel.root_dir%/Resources/components/jquery-ui/ui/minified/i18n/jquery-ui-i18n.min.js"
                - "%kernel.root_dir%/Resources/components/jquery-ui/ui/minified/i18n/jquery.ui.datepicker-fr.min.js"
            filters : [ ?yui_js ]
        bootstrap_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/bootstrap/dist/js/bootstrap.min.js"
            filters : [ ?yui_js ]
        select2_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/select2/select2.min.js"
                - "%kernel.root_dir%/Resources/components/select2/select2_locale_fr.js"
            filters : [ ?yui_js ]
        fancybox_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/fancybox/source/jquery.fancybox.pack.js"
            filters : [ ?yui_js ]
        validationEngine_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/jQuery-Validation-Engine/js/jquery.validationEngine.js"
                - "%kernel.root_dir%/Resources/components/jQuery-Validation-Engine/js/languages/jquery.validationEngine-fr.js"
            filters : [ ?yui_js ]
        json_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/JSON-js/json2.js"
            filters : [ ?yui_js ]
        bootstrap_iconpicker_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/bootstrap-iconpicker/bootstrap-iconpicker/js/bootstrap-iconpicker.min.js"
            filters : [ ?yui_js ]
        bootstrap_multiselect_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/bootstrap-multiselect/dist/js/bootstrap-multiselect.js"
            filters : [ ?yui_js ]
        nestable_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/Nestable/jquery.nestable.js"
            filters : [ ?yui_js ]
        enquire_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/enquire/dist/enquire.min.js"
            filters : [ ?yui_js ]
        highcharts_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/highcharts.com/js/highcharts.src.js"
                - "%kernel.root_dir%/Resources/components/highcharts.com/js/highcharts-more.src.js"
                - "%kernel.root_dir%/Resources/components/highcharts.com/js/modules/exporting.src.js"
            filters : [ ?yui_js ]
        jquery_gridster_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/gridster/dist/jquery.gridster.min.js"
            filters : [ ?yui_js ]
        jquery_cookie_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/jquery-cookie/jquery.cookie.js"
            filters : [ ?yui_js ]
        jquery_maskedinput_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/jquery-maskedinput/dist/jquery.maskedinput.min.js"
            filters : [ ?yui_js ]
        jquery_toggles_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/jquery-toggles/toggles.min.js"
            filters : [ ?yui_js ]
        jquery_nicescroll_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/jquery-nicescroll/jquery.nicescroll.min.js"
            filters : [ ?yui_js ]
        jquery_stepy_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/stepy/lib/jquery.stepy.js"
            filters : [ ?yui_js ]
        jquery_qtip2_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/qtip2/jquery.qtip.min.js"
            filters : [ ?yui_js ]
        slick_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/slick.js/slick/slick.min.js"
            filters : [ ?yui_js ]
        jquery_mosaicflow_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/jquery.mosaicflow/jquery.mosaicflow.min.js"
            filters : [ ?yui_js ]
        svg_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/canvg-gabelerner/canvg.js"
        jquery_file_upload_js:
            inputs:
                - '%kernel.root_dir%/Resources/components/jquery-file-upload/js/vendor/jquery.ui.widget.js'
                - '%kernel.root_dir%/Resources/components/jquery-file-upload/js/jquery.fileupload.js'
                - '%kernel.root_dir%/Resources/components/jquery-file-upload/js/jquery.fileupload-process.js'
                - '%kernel.root_dir%/Resources/components/jquery-file-upload/js/jquery.fileupload-ui.js'
                #- '%kernel.root_dir%/Resources/components/jquery-file-upload/js/jquery.fileupload-validate.js'
        #CSS
        bbcode_css:
            inputs:
                - '%kernel.root_dir%/../vendor/codeconsortium/ccdn-component-bb-code/src/CCDNComponent/BBCode/Resources/public/css/default.css'
        font_awesome_css:
            inputs:
                - "bundles/nodevotools/fonts/font-awesome/css/font-awesome.min.css"
        select2_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/select2/select2.css"
                - "%kernel.root_dir%/Resources/components/select2/select2-bootstrap.css"
            filters: [ cssembed, ?yui_css ]
        bootstrap_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/bootstrap/dist/css/bootstrap.min.css"
                - "%kernel.root_dir%/Resources/components/bootstrap/dist/css/bootstrap-theme.min.css"
            filters: [ cssembed, ?yui_css ]
        fancybox_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/fancybox/source/jquery.fancybox.css"
            filters: [ cssembed, ?yui_css ]
        validationEngine_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/jQuery-Validation-Engine/css/validationEngine.jquery.css"
            filters: [ cssembed, ?yui_css ]
        jquery_gridster_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/gridster/dist/jquery.gridster.min.css"
            filters: [ cssembed, ?yui_css ]
        jquery_toggles_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/jquery-toggles/toggles.css"
            filters: [ cssembed, ?yui_css ]
        jquery_qtip2_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/qtip2/jquery.qtip.min.css"
            filters: [ cssembed, ?yui_css ]
        bootstrap_iconpicker_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/bootstrap-iconpicker/bootstrap-iconpicker/css/bootstrap-iconpicker.min.css"
            filters: [ cssembed, ?yui_css ]
        bootstrap_multiselect_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/bootstrap-multiselect/dist/css/bootstrap-multiselect.css"
            filters: [ cssembed, ?yui_css ]
        slick_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/slick.js/slick/slick.css"
            filters : [ cssembed, ?yui_css ]
        slick_theme_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/slick.js/slick/slick-theme.css"
            filters : [ cssembed, ?yui_css ]
        jquery_file_upload_css:
            inputs:
                - '%kernel.root_dir%/Resources/components/jquery-file-upload/css/jquery.fileupload.css'
        fonts_css:
            inputs:
                - 'bundles/nodevoadmin/fonts/glyphicons/css/glyphicons.min.css'
                - 'bundles/hopitalnumeriqueadmin/css/fonts.css'
