# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - NodevoAdminBundle
        - NodevoMenuBundle
        - NodevoGridBundle
        - NodevoAclBundle
        - NodevoRoleBundle
        - NodevoMailBundle
        - NodevoFaqBundle
        - NodevoContactBundle
        - NodevoGestionnaireMediaBundle
        - NodevoCookieBundle
        - NodevoTexteDynamiqueBundle
        - HopitalNumeriqueAdminBundle
        - HopitalNumeriqueExpertBundle
        - HopitalNumeriqueInterventionBundle
        - HopitalNumeriqueCartBundle
        - HopitalNumeriqueUserBundle
        - HopitalNumeriqueReferenceBundle
        - HopitalNumeriqueEtablissementBundle
        - HopitalNumeriqueCoreBundle
        - HopitalNumeriqueModuleBundle
        - HopitalNumeriqueObjetBundle
        - HopitalNumeriqueQuestionnaireBundle
        - HopitalNumeriqueAccountBundle
        - NewAccountBundle
        - HopitalNumeriqueRechercheBundle
        - HopitalNumeriqueRechercheParcoursBundle
        - HopitalNumeriqueRegistreBundle
        - HopitalNumeriquePublicationBundle
        - HopitalNumeriqueFaqBundle
        - HopitalNumeriqueStatBundle
        - HopitalNumeriquePaiementBundle
        - HopitalNumeriqueForumBundle
        - HopitalNumeriqueFlashBundle
        - HopitalNumeriqueReportBundle
        - HopitalNumeriqueDomaineBundle
        - HopitalNumeriqueCommunautePratiqueBundle
        - HopitalNumeriqueAideBundle
        - HopitalNumeriqueAutodiagBundle
        - HopitalNumeriqueContextualNavigationBundle
        - CCDNForumForumBundle
        - FOSUserBundle
    filters:
        cssrewrite: ~
        cssembed:
            jar: %kernel.root_dir%/Resources/java/cssembed-0.4.5.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar
    assets:
        #<-- Factorisation
        front_css:
            inputs:
                - 'bundles/nodevoadmin/css/custom-jquery-ui.min.css'
                - 'bundles/nodevoadmin/plugins/apprise/apprise.css'
                - 'bundles/nodevoadmin/plugins/nodevoLoader/nodevoLoader.css'
                - 'bundles/hopitalnumeriquecore/css/layout.css'
                - 'bundles/hopitalnumeriquecore/css/Glyphter.css'
                - 'bundles/hopitalnumeriqueaccount/css/connexion-bloc.css'
                - 'bundles/hopitalnumeriquesearch/css/search.css'
        front_js:
            inputs:
                - 'bundles/fosjsrouting/js/router.js'
                - 'bundles/hopitalnumeriquecore/js/script.js'
                - 'bundles/hopitalnumeriquecore/js/recherche.js'
                - 'bundles/hopitalnumeriquecore/js/components/InplaceEditor.js'
                - 'bundles/hopitalnumeriquecore/js/components/AjaxList.js'
                - 'bundles/hopitalnumeriquecore/js/components/CountyList.js'
                - 'bundles/hopitalnumeriquecore/js/components/HobbyCollection.js'
                - 'bundles/nodevoadmin/plugins/apprise/apprise.js'
                - 'bundles/nodevoadmin/plugins/nodevoLoader/nodevoLoader.js'
                - '%kernel.root_dir%/Resources/lib/nodevo/Web.js'
                - '%kernel.root_dir%/Resources/lib/Highlight.js'
                - 'bundles/hopitalnumeriqueaccount/js/InformationsManquantes.js'
        #-->
        #JS
        bbcode_js:
            inputs:
                - '%kernel.root_dir%/../vendor/codeconsortium/ccdn-component-bb-code/src/CCDNComponent/BBCode/Resources/public/js/jquery.bbeditor.js'
            filters : [ ?yui_js ]
        tinymce_js:
            inputs:
                - "bundles/nodevotools/js/tinymce/tinymce.min.js"
                - "bundles/nodevotools/js/tinymce/tinymce.fr_FR.js"
                - "bundles/hopitalnumeriquecore/js/tinymce.js"
            filters : [ ?yui_js ]
        moxiemanager_js:
            inputs:
                - 'bundles/nodevogestionnairemedia/js/moxiemanager/js/moxman.loader.min.js'
                - 'bundles/nodevogestionnairemedia/js/MoxieManager.js'
            filters : [ ?yui_js ]
        jquery_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/jquery/dist/jquery.min.js"
            filters : [ ?yui_js ]
        jquery_ui_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/jquery-ui/ui/minified/jquery-ui.min.js"
                - "%kernel.root_dir%/Resources/components/jquery-ui/ui/minified/i18n/jquery-ui-i18n.min.js"
                - "%kernel.root_dir%/Resources/components/jquery-ui/ui/minified/i18n/jquery.ui.datepicker-fr.min.js"
            filters : [ ?yui_js ]
        jquery_ui_slider_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/jquery-ui/ui/minified/jquery.ui.slider.min.js"
                - "%kernel.root_dir%/Resources/components/jquery-ui/ui/minified/i18n/jquery-ui-i18n.min.js"
            filters : [ ?yui_js ]
        bootstrap_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/bootstrap/dist/js/bootstrap.min.js"
            filters : [ ?yui_js ]
        select2_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/select2/dist/js/select2.js"
                - "%kernel.root_dir%/Resources/components/select2/dist/js/i18n/fr.js"
            filters : [ ?yui_js ]
        fancybox_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/fancybox/source/jquery.fancybox.pack.js"
            filters : [ ?yui_js ]
        validationEngine_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/jQuery-Validation-Engine/js/jquery.validationEngine.js"
                - "%kernel.root_dir%/Resources/components/jQuery-Validation-Engine/js/languages/jquery.validationEngine-fr.js"
            filters : [ ?yui_js ]
        json_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/json-js/json2.js"
            filters : [ ?yui_js ]
        handlebars_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/handlebars/handlebars.js"
            filters : [ ?yui_js ]
        bootstrap_iconpicker_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/bootstrap-iconpicker/dist/js/bootstrap-iconpicker.min.js"
            filters : [ ?yui_js ]
        bootstrap_multiselect_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/bootstrap-multiselect/dist/js/bootstrap-multiselect.js"
            filters : [ ?yui_js ]
        nestable_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/nestable/jquery.nestable.js"
            filters : [ ?yui_js ]
        enquire_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/enquire/dist/enquire.min.js"
            filters : [ ?yui_js ]
        highcharts_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/highcharts.com/js/highcharts.src.js"
                - "%kernel.root_dir%/Resources/components/highcharts.com/js/highcharts-more.src.js"
                - "%kernel.root_dir%/Resources/components/highcharts.com/js/modules/exporting.src.js"
            filters : [ ?yui_js ]
        jquery_gridster_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/gridster/dist/jquery.gridster.min.js"
            filters : [ ?yui_js ]
        jquery_cookie_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/jquery-cookie/jquery.cookie.js"
            filters : [ ?yui_js ]
        jquery_maskedinput_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/jquery-maskedinput/dist/jquery.maskedinput.min.js"
            filters : [ ?yui_js ]
        jquery_toggles_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/jquery-toggles/toggles.min.js"
            filters : [ ?yui_js ]
        jquery_nicescroll_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/jquery-nicescroll/jquery.nicescroll.min.js"
            filters : [ ?yui_js ]
        jquery_stepy_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/stepy/js/jquery.stepy.js"
            filters : [ ?yui_js ]
        jquery_qtip2_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/qtip2/jquery.qtip.min.js"
            filters : [ ?yui_js ]
        slick_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/slick.js/slick/slick.min.js"
            filters : [ ?yui_js ]
        jquery_mosaicflow_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/jquery.mosaicflow/jquery.mosaicflow.min.js"
            filters : [ ?yui_js ]
        svg_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/canvg-gabelerner/canvg.js"
        jquery_file_upload_js:
            inputs:
                - '%kernel.root_dir%/Resources/components/jquery-file-upload/js/vendor/jquery.ui.widget.js'
                - '%kernel.root_dir%/Resources/components/jquery-file-upload/js/jquery.fileupload.js'
                - '%kernel.root_dir%/Resources/components/jquery-file-upload/js/jquery.fileupload-process.js'
                - '%kernel.root_dir%/Resources/components/jquery-file-upload/js/jquery.fileupload-ui.js'
                #- '%kernel.root_dir%/Resources/components/jquery-file-upload/js/jquery.fileupload-validate.js'
        jstree_js:
            inputs:
                - '%kernel.root_dir%/Resources/components/jstree/dist/jstree.min.js'
        #CSS
        bbcode_css:
            inputs:
                - '%kernel.root_dir%/../vendor/codeconsortium/ccdn-component-bb-code/src/CCDNComponent/BBCode/Resources/public/css/default.css'
        font_awesome_css:
            inputs:
                - "bundles/nodevotools/fonts/font-awesome/css/font-awesome.min.css"
        select2_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/select2/dist/css/select2.css"
            filters: [ cssembed, ?yui_css ]
        bootstrap_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/bootstrap/dist/css/bootstrap.min.css"
                - "%kernel.root_dir%/Resources/components/bootstrap/dist/css/bootstrap-theme.min.css"
            filters: [ cssembed, ?yui_css ]
        fancybox_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/fancybox/source/jquery.fancybox.css"
            filters: [ cssembed, ?yui_css ]
        validationEngine_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/jQuery-Validation-Engine/css/validationEngine.jquery.css"
            filters: [ cssembed, ?yui_css ]
        jquery_gridster_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/gridster/dist/jquery.gridster.min.css"
            filters: [ cssembed, ?yui_css ]
        jquery_toggles_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/jquery-toggles/toggles.css"
                - 'bundles/nodevoadmin/css/toggles.css'
            filters: [ cssembed, ?yui_css ]
        jquery_qtip2_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/qtip2/jquery.qtip.min.css"
            filters: [ cssembed, ?yui_css ]
        bootstrap_iconpicker_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/bootstrap-iconpicker/dist/css/bootstrap-iconpicker.min.css"
            filters: [ cssembed, ?yui_css ]
        bootstrap_multiselect_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/bootstrap-multiselect/dist/css/bootstrap-multiselect.css"
            filters: [ cssembed, ?yui_css ]
        slick_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/slick.js/slick/slick.css"
            filters : [ cssembed, ?yui_css ]
        slick_theme_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/slick.js/slick/slick-theme.css"
            filters : [ cssembed, ?yui_css ]
        jquery_file_upload_css:
            inputs:
                - '%kernel.root_dir%/Resources/components/jquery-file-upload/css/jquery.fileupload.css'
        fonts_css:
            inputs:
                - 'bundles/nodevoadmin/fonts/glyphicons/css/glyphicons.min.css'
                - 'bundles/hopitalnumeriqueadmin/css/fonts.css'
        jstree_css:
            inputs:
                - '%kernel.root_dir%/Resources/components/jstree/dist/themes/default/style.min.css'
                - 'bundles/hopitalnumeriquecore/css/redefinitions/jstree.css'
        gauge:
            inputs:
                - "%kernel.root_dir%/Resources/components/gauge.js/dist/gauge.min.js"

        datatables_js:
            inputs:
                - "%kernel.root_dir%/Resources/components/datatables/media/js/jquery.dataTables.js"
                - "%kernel.root_dir%/Resources/components/datatables/media/js/dataTables.bootstrap.js"

        datatables_css:
            inputs:
                - "%kernel.root_dir%/Resources/components/datatables/media/css/dataTables.bootstrap.css"
