imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
        cookie_lifetime: 36000
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - NodevoAdminBundle
        - NodevoMenuBundle
        - NodevoGridBundle
        - NodevoAclBundle
        - NodevoRoleBundle
        - NodevoMailBundle
        - NodevoGestionnaireMediaBundle
        - HopitalNumeriqueInterventionBundle
        - HopitalNumeriqueUserBundle
        - HopitalNumeriqueReferenceBundle
        - HopitalNumeriqueEtablissementBundle
        - HopitalNumeriqueCoreBundle
        - HopitalNumeriqueObjetBundle
        - HopitalNumeriqueQuestionnaireBundle
        - HopitalNumeriqueAccountBundle
        - HopitalNumeriqueRechercheBundle
        - HopitalNumeriqueRegistreBundle
        - HopitalNumeriquePublicationBundle
        - FOSUserBundle
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
          default:
              auto_mapping: true
              dql:
                  string_functions:
                      GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Cache Doctrine
liip_doctrine_cache:
    namespaces:
        main:
            type: array

# Gestion des users via FOSUserBundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: HopitalNumerique\UserBundle\Entity\User
    from_email:
        address: admin@nodevo.com
        sender_name: Administrateur
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template: HopitalNumeriqueUserBundle:Resetting:email.txt.twig

#KNP Menu Bundle
knp_menu:
    twig:
        template: knp_main_menu.html.twig
    templating: true
    default_renderer: twig

# Grid APY DATA GRID
apy_data_grid:
    pagerfanta:
        enable: true
        view_class: Pagerfanta\View\TwitterBootstrap3View
        options:
           prev_message : «
           next_message : »

# Genemu Form - Ajout de composant externe dans les formulaires
genemu_form:
    select2: ~
    date: ~
    tinymce:
        enabled: true
        theme:   advanced

# Nodevo mail
nodevo_mail:
    options:
        allowAdd: false
        allowDelete: false
        mailAnap: #Tableaux des adresses mails copie caché de tout les mails envoyé par l'application sous la forme "adresse_mail: nom_affiché"
            toto@yopmail.com: adresse1
            toto2@yopmail.com: adresse2

nodevo_menu:
    options:
        breadcrumbRouteRacine: hopital_numerique_admin_homepage

# Gestion download fichiers sécurisé (pas dans /web)
igorw_file_serve:
    base_dir: ~        # The default value is "%kernel.root_dir%"

hopital_numerique_user:
    options: 
        idEtatActif: 3      #Ids de la table Référence
        idTypeAutres : 10

hopital_numerique_questionnaire:
    options:
        idRoles:
            expert: 1
            ambassadeur: 2
