imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assetic.yml }
    - { resource: forum.yml }

framework:
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name: hopitalnumerique
        handler_id:  ~
        cookie_lifetime: 36000
    fragments:       ~
    http_method_override: true

# Mise en place des services
services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
    logout_handler:
        class: HopitalNumerique\UserBundle\Handler\LogoutHandler
        arguments: ["@hopitalnumerique_objet.manager.objet", "@security.context"]

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        ForumBundle:
            translation: HopitalNumeriqueForumBundle

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        resolve_target_entities:
            Symfony\Component\Security\Core\User\UserInterface: HopitalNumerique\UserBundle\Entity\User
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    string_functions:
                        GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat
                mappings:
                    CCDNForumForumBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  "../../../../../src/HopitalNumerique/ForumBundle/Resources/config/doctrine"
                        alias:                ~
                        prefix:               HopitalNumerique\ForumBundle\Entity
                        is_bundle:            true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Cache Doctrine
liip_doctrine_cache:
    namespaces:
        main:
            type: array

# Gestion des users via FOSUserBundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: HopitalNumerique\UserBundle\Entity\User
    from_email:
        address: admin@nodevo.com
        sender_name: Administrateur
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template: HopitalNumeriqueUserBundle:Resetting:email.txt.twig

#KNP Menu Bundle
knp_menu:
    twig:
        template: knp_menu.html.twig
    templating: true
    default_renderer: twig

# Grid APY DATA GRID
apy_data_grid:
    pagerfanta:
        enable: true
        view_class: Pagerfanta\View\TwitterBootstrap3View
        options:
           prev_message : «
           next_message : »

# Genemu Form - Ajout de composant externe dans les formulaires
genemu_form:
    select2: ~
    date: ~
    tinymce:
        enabled: true
        theme:   advanced

# Nodevo mail
nodevo_mail:
    options:
        allowAdd: false
        allowDelete: false
        expediteurEnCopie: %confighn_nodevomail_expediteurEnCopie%
        mailAnap: %confighn_nodevomail_mailsAnap%

#Menu Breadcrumb Admin Link
nodevo_menu:
    options:
        breadcrumbRoot: hopital_numerique_admin_homepage

# Gestion download fichiers sécurisé (pas dans /web)
igorw_file_serve:
    base_dir: ~        # The default value is "%kernel.root_dir%"

hopital_numerique_user:
    options: 
        idEtatActif: 3      #Ids de la table Référence
        idTypeAutres : 10

hopital_numerique_questionnaire:
    options:
        idRoles:
            expert: 1
            ambassadeur: 2
            module-evaluation: 4

hopital_numerique_contact:
    options:
        mailsContact: %confighn_hopitalnumerique_contact%

#html to Pdf
knp_snappy:
    pdf:
        enabled: true
        binary: %wkhtmltopdf%
        options: []
    image:
        enabled: true
        binary: %wkhtmltoimage%
        options: []
