imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assetic.yml }
    - { resource: forum.yml }

framework:
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name: hopitalnumerique
        handler_id:  ~
        cookie_lifetime: 86400 # 24h
    fragments:       ~
    http_method_override: true

# Mise en place des services
services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
    logout_handler:
        class: HopitalNumerique\UserBundle\Handler\LogoutHandler
        arguments: ["@hopitalnumerique_objet.manager.objet", "@security.context"]
    genemu.form.jquery.type.date:
        class: Nodevo\FormBundle\Form\JQuery\Type\DateType
        arguments: ["%genemu.form.date.options%"]
        tags:
            - { name: form.type, alias: genemu_jquerydate }
    fos_user.doctrine_registry:
        alias: doctrine

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        ForumBundle:
            translation: HopitalNumeriqueForumBundle
        CookieLink: %cookieLink%
        ActivateRsxSociaux: %activateRsxSociaux%
    form:
        resources:
            - 'HopitalNumeriqueForumBundle:Formulaire/Theme:theme.vertical.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: true
        resolve_target_entities:
            Symfony\Component\Security\Core\User\UserInterface: HopitalNumerique\UserBundle\Entity\User
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    string_functions:
                        GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat
                        RAND: DoctrineExtensions\Query\Mysql\Rand
                mappings:
                    CCDNForumForumBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  "../../../../../src/HopitalNumerique/ForumBundle/Resources/config/doctrine"
                        alias:                ~
                        prefix:               HopitalNumerique\ForumBundle\Entity
                        is_bundle:            true
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Gestion des users via FOSUserBundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: HopitalNumerique\UserBundle\Entity\User
    from_email:
        address: admin@nodevo.com
        sender_name: Administrateur
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template: HopitalNumeriqueUserBundle:Resetting:email.txt.twig
    registration:
        confirmation:
            enabled: true

#KNP Menu Bundle
knp_menu:
    twig:
        template: knp_menu.html.twig
    templating: true
    default_renderer: twig

# Grid APY DATA GRID
apy_data_grid:
    pagerfanta:
        enable: true
        view_class: Pagerfanta\View\TwitterBootstrap3View
        options:
           prev_message : «
           next_message : »

# Genemu Form - Ajout de composant externe dans les formulaires
genemu_form:
    select2: ~
    date: ~
    tinymce:
        enabled: true
        theme:   advanced

# Nodevo mail
nodevo_mail:
    options:
        allowAdd: false
        allowDelete: false
        expediteurEnCopie: %confighn_nodevomail_expediteurEnCopie%
        mailAnap: %confighn_nodevomail_mailsAnap%

#Menu Breadcrumb Admin Link
nodevo_menu:
    options:
        breadcrumbRoot: hopital_numerique_admin_homepage

# Gestion download fichiers sécurisé (pas dans /web)
igorw_file_serve:
    base_dir: ~        # The default value is "%kernel.root_dir%"

hopital_numerique_user:
    options: 
        idEtatActif: 3      #Ids de la table Référence
        idTypeAutres : 10

hopital_numerique_questionnaire:
    options:
        idRoles:
            expert: 1
            ambassadeur: 2
            module-evaluation: 4
        mailReponses       : %confighn_hopitalnumerique_questionnaire_mailReponse%
        mailExpertReponses : %confighn_hopitalnumerique_questionnaire_mailExpertReponses%

hopital_numerique_contact:
    options:
        mailsContact: %confighn_hopitalnumerique_contact%

hopital_numerique_recherche:
    options:
        urlRechercheTextuelle : %confighn_hopitalnumerique_recherche%
        activationExalead     : %confighn_hopitalnumerique_exalead%

#html to Pdf
knp_snappy:
    pdf:
        enabled: true
        binary: %wkhtmltopdf%
        options:
            load-error-handling: 'ignore'
    image:
        enabled: true
        binary: %wkhtmltoimage%
        options: []

#Stof Stuff
stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default: 
            loggable: true
            timestampable: true

#Flux RSS
eko_feed:
    feeds:
        objet:
            title:       'Publications'
            description: 'Dernières publications'
            link:
                route_name: hopital_numerique_publication_publication_objet
                route_params: {id: 1}
            encoding:    'utf-8'
            author:      'ANAP' # Only required for Atom feeds

white_october_pagerfanta:
    default_view: 'twitter_bootstrap3'

fos_js_routing:
    routes_to_expose:
        - hopitalnumerique_communautepratique_commentaire_blockview
        - hopitalnumerique_communautepratique_commentaire_delete
        - hopitalnumerique_communautepratique_commentaire_edit
        - hopitalnumerique_communautepratique_document_delete
        - hopitalnumerique_communautepratique_document_download
        - hopitalnumerique_communautepratique_document_listbygroupe
        - hopitalnumerique_communautepratique_document_upload
        - hopitalnumerique_communautepratique_fiche_close
        - hopitalnumerique_communautepratique_fiche_open
        - hopitalnumerique_communautepratique_fiche_view
        - hopitalnumerique_communautepratique_tinymce_documents
        - hopitalnumerique_communautepratique_user_desinscritgroupe
        - hopitalnumerique_communautepratique_user_listbygroupe
        - hopitalnumerique_objet_objet_getObjets
        - hopital_numerique_recherche_parcours_save
        - hopitalnumerique_reference_referencement_savechosenreferences
        - hopital_numerique_user_front_departements_informationsPersonelles
        - hopital_numerique_user_front_etablissements_informationsPersonelles

# Miniatures
liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: '%kernel.root_dir%/..'
    filter_sets:
        communaute_pratique_document:
            quality: 75
            filters:
                thumbnail: { size: [100, 100], mode: inset, allow_upscale: true }

ivory_google_map:
    distance_matrix:
        enabled: true
        url: "https://maps.googleapis.com/maps/api/distancematrix"
        adapter: "widop_http_adapter.curl"
        https: true
        format: "json"
