ccdn_forum_forum:
    template:
        engine:               twig
        pager_theme:          KnpPaginatorBundle:Pagination:twitter_bootstrap_pagination.html.twig
    entity:
        forum:
            class:                HopitalNumerique\ForumBundle\Entity\Forum
        category:
            class:                HopitalNumerique\ForumBundle\Entity\Category
        board:
            class:                HopitalNumerique\ForumBundle\Entity\Board
        topic:
            class:                HopitalNumerique\ForumBundle\Entity\Topic
        post:
            class:                HopitalNumerique\ForumBundle\Entity\Post
        subscription:
            class:                HopitalNumerique\ForumBundle\Entity\Subscription
        registry:
            class:                HopitalNumerique\ForumBundle\Entity\Registry
    component:
        helper:
            role:
                class:            HopitalNumerique\ForumBundle\Component\Helper\RoleHelper
    gateway:
        forum:
            class:                CCDNForum\ForumBundle\Model\Component\Gateway\ForumGateway
        category:
            class:                CCDNForum\ForumBundle\Model\Component\Gateway\CategoryGateway
        board:
            class:                CCDNForum\ForumBundle\Model\Component\Gateway\BoardGateway
        topic:
            class:                CCDNForum\ForumBundle\Model\Component\Gateway\TopicGateway
        post:
            class:                CCDNForum\ForumBundle\Model\Component\Gateway\PostGateway
        subscription:
            class:                CCDNForum\ForumBundle\Model\Component\Gateway\SubscriptionGateway
        registry:
            class:                CCDNForum\ForumBundle\Model\Component\Gateway\RegistryGateway
    repository:
        forum:
            class:                HopitalNumerique\ForumBundle\Model\Component\Repository\ForumRepository
        category:
            class:                HopitalNumerique\ForumBundle\Model\Component\Repository\CategoryRepository
        board:
            class:                HopitalNumerique\ForumBundle\Model\Component\Repository\BoardRepository
        topic:
            class:                HopitalNumerique\ForumBundle\Model\Component\Repository\TopicRepository
        post:
            class:                HopitalNumerique\ForumBundle\Model\Component\Repository\PostRepository
        subscription:
            class:                HopitalNumerique\ForumBundle\Model\Component\Repository\SubscriptionRepository
        registry:
            class:                HopitalNumerique\ForumBundle\Model\Component\Repository\RegistryRepository
    manager:
        forum:
            class:                CCDNForum\ForumBundle\Model\Component\Manager\ForumManager
        category:
            class:                CCDNForum\ForumBundle\Model\Component\Manager\CategoryManager
        board:
            class:                CCDNForum\ForumBundle\Model\Component\Manager\BoardManager
        topic:
            class:                CCDNForum\ForumBundle\Model\Component\Manager\TopicManager
        post:
            class:                CCDNForum\ForumBundle\Model\Component\Manager\PostManager
        subscription:
            class:                HopitalNumerique\ForumBundle\Model\Component\Manager\SubscriptionManager
        registry:
            class:                CCDNForum\ForumBundle\Model\Component\Manager\RegistryManager
    model:
        forum:
            class:                CCDNForum\ForumBundle\Model\FrontModel\ForumModel
        category:
            class:                CCDNForum\ForumBundle\Model\FrontModel\CategoryModel
        board:
            class:                CCDNForum\ForumBundle\Model\FrontModel\BoardModel
        topic:
            class:                CCDNForum\ForumBundle\Model\FrontModel\TopicModel
        post:
            class:                CCDNForum\ForumBundle\Model\FrontModel\PostModel
        subscription:
            class:                CCDNForum\ForumBundle\Model\FrontModel\SubscriptionModel
        registry:
            class:                CCDNForum\ForumBundle\Model\FrontModel\RegistryModel
    form:
        handler:
            forum_create:
                class:                CCDNForum\ForumBundle\Form\Handler\Admin\Forum\ForumCreateFormHandler
            forum_update:
                class:                CCDNForum\ForumBundle\Form\Handler\Admin\Forum\ForumUpdateFormHandler
            forum_delete:
                class:                CCDNForum\ForumBundle\Form\Handler\Admin\Forum\ForumDeleteFormHandler
            category_create:
                class:                CCDNForum\ForumBundle\Form\Handler\Admin\Category\CategoryCreateFormHandler
            category_update:
                class:                CCDNForum\ForumBundle\Form\Handler\Admin\Category\CategoryUpdateFormHandler
            category_delete:
                class:                CCDNForum\ForumBundle\Form\Handler\Admin\Category\CategoryDeleteFormHandler
            board_create:
                class:                CCDNForum\ForumBundle\Form\Handler\Admin\Board\BoardCreateFormHandler
            board_update:
                class:                CCDNForum\ForumBundle\Form\Handler\Admin\Board\BoardUpdateFormHandler
            board_delete:
                class:                CCDNForum\ForumBundle\Form\Handler\Admin\Board\BoardDeleteFormHandler
            topic_create:
                class:                CCDNForum\ForumBundle\Form\Handler\User\Topic\TopicCreateFormHandler
            topic_update:
                class:                CCDNForum\ForumBundle\Form\Handler\User\Topic\TopicUpdateFormHandler
            topic_delete:
                class:                CCDNForum\ForumBundle\Form\Handler\Moderator\Topic\TopicDeleteFormHandler
            change_topics_board:
                class:                CCDNForum\ForumBundle\Form\Handler\Moderator\Topic\TopicChangeBoardFormHandler
            post_create:
                class:                CCDNForum\ForumBundle\Form\Handler\User\Post\PostCreateFormHandler
            post_update:
                class:                CCDNForum\ForumBundle\Form\Handler\User\Post\PostUpdateFormHandler
            post_delete:
                class:                CCDNForum\ForumBundle\Form\Handler\User\Post\PostDeleteFormHandler
            post_unlock:
                class:                CCDNForum\ForumBundle\Form\Handler\Moderator\Post\PostUnlockFormHandler
        type:
            forum_create:
                class:                CCDNForum\ForumBundle\Form\Type\Admin\Forum\ForumCreateFormType
            forum_update:
                class:                CCDNForum\ForumBundle\Form\Type\Admin\Forum\ForumUpdateFormType
            forum_delete:
                class:                CCDNForum\ForumBundle\Form\Type\Admin\Forum\ForumDeleteFormType
            category_create:
                class:                CCDNForum\ForumBundle\Form\Type\Admin\Category\CategoryCreateFormType
            category_update:
                class:                CCDNForum\ForumBundle\Form\Type\Admin\Category\CategoryUpdateFormType
            category_delete:
                class:                CCDNForum\ForumBundle\Form\Type\Admin\Category\CategoryDeleteFormType
            board_create:
                class:                CCDNForum\ForumBundle\Form\Type\Admin\Board\BoardCreateFormType
            board_update:
                class:                CCDNForum\ForumBundle\Form\Type\Admin\Board\BoardUpdateFormType
            board_delete:
                class:                CCDNForum\ForumBundle\Form\Type\Admin\Board\BoardDeleteFormType
            topic_create:
                class:                CCDNForum\ForumBundle\Form\Type\User\Topic\TopicCreateFormType
            topic_update:
                class:                CCDNForum\ForumBundle\Form\Type\User\Topic\TopicUpdateFormType
            topic_delete:
                class:                CCDNForum\ForumBundle\Form\Type\Moderator\Topic\TopicDeleteFormType
            change_topics_board:
                class:                CCDNForum\ForumBundle\Form\Type\Moderator\Topic\TopicChangeBoardFormType
            post_create:
                class:                CCDNForum\ForumBundle\Form\Type\User\Post\PostCreateFormType
            post_update:
                class:                CCDNForum\ForumBundle\Form\Type\User\Post\PostUpdateFormType
            post_delete:
                class:                CCDNForum\ForumBundle\Form\Type\User\Post\PostDeleteFormType
            post_unlock:
                class:                CCDNForum\ForumBundle\Form\Type\Moderator\Post\PostUnlockFormType
    forum:
        admin:
            create:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
                form_theme:           HopitalNumeriqueAccountBundle:Formulaire:theme.default.html.twig
            delete:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
                form_theme:           HopitalNumeriqueAccountBundle:Formulaire:theme.default.html.twig
            edit:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
                form_theme:           HopitalNumeriqueAccountBundle:Formulaire:theme.default.html.twig
            list:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
    category:
        admin:
            create:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
                form_theme:           HopitalNumeriqueAccountBundle:Formulaire:theme.default.html.twig
            delete:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
                form_theme:           HopitalNumeriqueAccountBundle:Formulaire:theme.default.html.twig
            edit:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
                form_theme:           HopitalNumeriqueAccountBundle:Formulaire:theme.default.html.twig
            list:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
        user:
            last_post_datetime_format:  d-m-Y - H:i
            index:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
            show:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
    board:
        admin:
            create:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
                form_theme:           HopitalNumeriqueAccountBundle:Formulaire:theme.default.html.twig
            delete:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
                form_theme:           HopitalNumeriqueAccountBundle:Formulaire:theme.default.html.twig
            edit:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
                form_theme:           HopitalNumeriqueAccountBundle:Formulaire:theme.default.html.twig
            list:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
        user:
            show:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
                topics_per_page:      50
                topic_title_truncate:  50
                first_post_datetime_format:  d-m-Y - H:i
                last_post_datetime_format:  d-m-Y - H:i
    topic:
        moderator:
            change_board:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
                form_theme:           HopitalNumeriqueAccountBundle:Formulaire:theme.default.html.twig
            delete:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
                form_theme:           HopitalNumeriqueAccountBundle:Formulaire:theme.default.html.twig
        user:
            flood_control:
                post_limit:           4
                block_for_minutes:    1
            show:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
                posts_per_page:       20
                closed_datetime_format:  d-m-Y - H:i
                deleted_datetime_format:  d-m-Y - H:i
            create:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
                form_theme:           HopitalNumeriqueAccountBundle:Formulaire:theme.default.html.twig
            reply:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
                form_theme:           HopitalNumeriqueAccountBundle:Formulaire:theme.default.html.twig
    post:
        moderator:
            unlock:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
                form_theme:           HopitalNumeriqueAccountBundle:Formulaire:theme.default.html.twig
        user:
            show:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
            edit:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
                form_theme:           HopitalNumeriqueAccountBundle:Formulaire:theme.default.html.twig
            delete:
                layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
                form_theme:           HopitalNumeriqueAccountBundle:Formulaire:theme.default.html.twig
            lock:
                enable:               true
                after_days:           7
    item_post:
        created_datetime_format:  d-m-Y - H:i
        edited_datetime_format:  d-m-Y - H:i
        locked_datetime_format:  d-m-Y - H:i
        deleted_datetime_format:  d-m-Y - H:i
    subscription:
        list:
            layout_template:      HopitalNumeriqueForumBundle::layout.html.twig
            topics_per_page:      50
            topic_title_truncate:  50
            first_post_datetime_format:  d-m-Y - H:i
            last_post_datetime_format:  d-m-Y - H:i
    fixtures:
        user_admin:           user-admin
    seo:
        title_length:         67