hopital_numerique_forum:
    resource: "@HopitalNumeriqueForumBundle/Resources/config/routing.yml"
    prefix:   /

# Bundles Hopital Numérique : partie Front
hopital_numerique_core:
    resource: "@HopitalNumeriqueCoreBundle/Resources/config/routing.yml"
    prefix:   /

hopital_numerique_recherche:
    resource: "@HopitalNumeriqueRechercheBundle/Resources/config/routing.yml"
    prefix:   /

hopital_numerique_registre:
    resource: "@HopitalNumeriqueRegistreBundle/Resources/config/routing.yml"
    prefix:   /

hopital_numerique_publication:
    resource: "@HopitalNumeriquePublicationBundle/Resources/config/routing.yml"
    prefix:   /

hopital_numerique_account:
    resource: "@HopitalNumeriqueAccountBundle/Resources/config/routing.yml"
    prefix:   /compte-hn

hopital_numerique_intervention_objet:
    resource: "@HopitalNumeriqueInterventionBundle/Resources/config/routing/objet.yml"
    prefix:   /compte-hn/intervention

hopital_numerique_contact:
    resource: "@HopitalNumeriqueContactBundle/Resources/config/routing.yml"
    prefix:   /

hopital_numerique_faq:
    resource: "@HopitalNumeriqueFaqBundle/Resources/config/routing.yml"
    prefix:   /faq

# Bundles Hopital Numérique : partie Admin
hopital_numerique_reference:
    resource: "@HopitalNumeriqueReferenceBundle/Resources/config/routing.yml"
    prefix:   /admin

hopital_numerique_etablissement:
    resource: "@HopitalNumeriqueEtablissementBundle/Resources/config/routing.yml"
    prefix:   /admin

hopital_numerique_admin:
    resource: "@HopitalNumeriqueAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

hopital_numerique_objet:
    resource: "@HopitalNumeriqueObjetBundle/Resources/config/routing.yml"
    prefix:   /admin

hopital_numerique_intervention_admin:
    resource: "@HopitalNumeriqueInterventionBundle/Resources/config/routing/admin.yml"
    prefix:   /admin/intervention

hopital_numerique_module:
    resource: "@HopitalNumeriqueModuleBundle/Resources/config/routing.yml"
    prefix:   /

# Bundles Hopital Numérique : partie Admin ET partie Front
hopital_numerique_user:
    resource: "@HopitalNumeriqueUserBundle/Resources/config/routing.yml"
    prefix:   /

hopital_numerique_questionnaire:
    resource: "@HopitalNumeriqueQuestionnaireBundle/Resources/config/routing.yml"
    prefix:   /

hopital_numerique_paiement:
    resource: "@HopitalNumeriquePaiementBundle/Resources/config/routing.yml"
    prefix:   /

hopital_numerique_autodiag:
    resource: "@HopitalNumeriqueAutodiagBundle/Resources/config/routing.yml"
    prefix:   /

# Bundles Nodevo
nodevo_acl:
    resource: "@NodevoAclBundle/Resources/config/routing.yml"
    prefix:   /admin

nodevo_role:
    resource: "@NodevoRoleBundle/Resources/config/routing.yml"
    prefix:   /admin

nodevo_menu:
    resource: "@NodevoMenuBundle/Resources/config/routing.yml"
    prefix:   /admin

nodevo_admin:
    resource: "@NodevoAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

nodevo_mail:
    resource: "@NodevoMailBundle/Resources/config/routing.yml"
    prefix:   /admin

nodevo_contact:
    resource: "@NodevoContactBundle/Resources/config/routing.yml"
    prefix:   /

nodevo_faq:
    resource: "@NodevoFaqBundle/Resources/config/routing.yml"
    prefix:   /

nodevo_gestionnaire_media:
    resource: "@NodevoGestionnaireMediaBundle/Resources/config/routing.yml"
    prefix:   /admin/media

#Forum
CCDNForumForumBundle:
    resource: "@CCDNForumForumBundle/Resources/config/routing.yml"
    prefix:   /

