security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # Formulaire ADMIN (accessible aux anonymes)
        admin_login:
            pattern: ^/admin/login$
            anonymous: true

        # Formulaire FRONT : connexion + reset password (accessible aux anonymes)
        comptehn_login:
            pattern: (^/compte-hn/(connexion|mot-de-passe-perdu(.*))$)|(^/compte-hn/inscription) # Cette expression régulière permet de prendre /login
            anonymous: true
            context: application

        # Console DEV/ASSETS (sans notions de sécurité)
        dev:
            pattern: ^/(_(profiler|wdt)|compiled|js|css|images)/
            security: false

        # Si on essaye d'accéder à l'url  /compte-hn, on redirige vers le form /compte-hn/login
        frontoffice_connecte:
            pattern: ^/(compte-hn|registre-ambassadeurs)
            anonymous: false
            form_login:
                login_path: account_login
                check_path: account_login_check
                provider: fos_userbundle
                remember_me:  true
                always_use_default_target_path : false
                default_target_path: hopital_numerique_user_informations_personnelles
                use_referer : true
                csrf_provider: form.csrf_provider
            logout: true
            logout:
                path:   account_logout
                target: hopital_numerique_homepage
            remember_me:
                key: %secret%
            context: application

        # Pare-feu de la partie admin du site (on protège tout)
        admin:
            pattern: ^/admin
            form_login:
                login_path: /admin/login
                check_path: fos_user_security_check
                provider: fos_userbundle
                remember_me:  true
                always_use_default_target_path : false
                default_target_path: hopital_numerique_admin_homepage
                use_referer : true
                csrf_provider: form.csrf_provider
            logout: true
            logout:
                path:   /admin/logout
                target: hopital_numerique_admin_homepage
            remember_me:
                key: %secret%
            anonymous: false
            context: application

        # Pare-feu de la partie front du site
        main:
            pattern: ^/
            form_login:
                login_path: account_login
                check_path: account_login_check
                provider: fos_userbundle
                remember_me:  true
                always_use_default_target_path : false
                default_target_path: hopital_numerique_user_informations_personnelles 
                use_referer : true
                csrf_provider: form.csrf_provider
            logout: true
            logout:
                path:   account_logout
                target: hopital_numerique_homepage
            remember_me:
                key: %secret%
            anonymous: true
            context: application

    access_decision_manager:
        strategy: unanimous

    # On Gère rien ici, tout est authorisé en anonymous car les ACLs sont gérés depuis le NodevoAclBundle
    access_control:
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/compte-hn/connexion$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/compte-hn/inscription, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/compte-hn/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }