hopitalnumerique_objet_risk_list:
    path:  /
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Back/Risk:list" }

hopitalnumerique_objet_risk_add:
    path:  /add
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Back/Risk:edit" }

hopitalnumerique_objet_risk_edit:
    path:  /edit/{risk}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Back/Risk:edit", risk: 1 }
