hopitalnumerique_objet_risk_list:
    path:  /
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Back/Risk:list" }

hopitalnumerique_objet_risk_add:
    path:  /add
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Back/Risk:edit" }

hopitalnumerique_objet_risk_edit:
    path:  /edit/{risk}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Back/Risk:edit", risk: 1 }

hopitalnumerique_objet_risk_delete:
    path:  /delete/{risk}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Back/Risk:delete" }

hopitalnumerique_objet_risk_mass_delete:
    path:  /mass-delete/{risk}
    defaults: { _controller: "HopitalNumeriqueObjetBundle:Back/Risk:deleteMass" }
