nodevo_contact_edit:
    pattern:  /contact
    defaults: { _controller: NodevoContactBundle:Contact:index }

index:
    pattern: /contact
    defaults: { _controller: NodevoContactBundle:Contact:index }
