hopital_numerique_guided_search_risk_synthesis:
    path: /{guidedSearch}
    defaults: { _controller: HopitalNumeriqueRechercheParcoursBundle:Front/GuidedSearchRiskSynthesis:synthesis }

hopital_numerique_guided_search_risk_synthesis_pdf_export:
    path: /{guidedSearch}/export.pdf
    defaults: { _controller: HopitalNumeriqueRechercheParcoursBundle:Front/GuidedSearchRiskSynthesis:PDFExport }

hopital_numerique_guided_search_risk_synthesis_export:
    path: /{guidedSearch}/export.{type}
    defaults: { _controller: HopitalNumeriqueRechercheParcoursBundle:Front/GuidedSearchRiskSynthesis:export }
    requirements:
        type: csv|xlsx
