#Activité expert
#-Grid
hopitalnumerique_expert_expert_activite:
    pattern:  /expert/activite
    defaults: { _controller: "HopitalNumeriqueExpertBundle:ActiviteExpert:index" }
    requirements: 
        _method: GET|POST

#-Gestion entity
hopitalnumerique_expert_expert_activite_add:
    pattern:  /expert/activite/add
    defaults: { _controller: "HopitalNumeriqueExpertBundle:ActiviteExpert:add" }
    requirements: 
        _method: GET|POST

hopitalnumerique_expert_expert_activite_edit:
    pattern:  /expert/activite/edit/{id}
    defaults: { _controller: "HopitalNumeriqueExpertBundle:ActiviteExpert:edit", id: 1 }
    requirements:
        id: \d+
        _method: GET|POST

hopitalnumerique_expert_expert_activite_delete:
    pattern:  /expert/activite/delete/{id}.{_format}
    defaults: { _controller: "HopitalNumeriqueExpertBundle:ActiviteExpert:delete", _format: json }
    requirements: 
        id: \d+
        _method: POST|DELETE

hopitalnumerique_expert_expert_ajout_date_fictive:
    pattern:  /expert/activite/ajout-date-fictive/{id}
    defaults: { _controller: "HopitalNumeriqueExpertBundle:DateFictive:add" }
    requirements:
        id: \d+
        _method: GET|POST

hopitalnumerique_expert_expert_liste_date_fictive:
    pattern:  /expert/activite/liste-date-fictive/{id}
    defaults: { _controller: "HopitalNumeriqueExpertBundle:DateFictive:list" }
    requirements:
        id: \d+
        _method: GET

hopitalnumerique_expert_expert_delete_date_fictive:
    pattern:  /expert/activite/delete-date-fictive/{id}
    defaults: { _controller: "HopitalNumeriqueExpertBundle:DateFictive:delete"}
    requirements: 
        id: \d+
        _method: POST|GET

#-Fancy de modif de la vacation
hopitalnumerique_expert_expert_activite_parametrage:
    pattern:  /expert/activite/parametrage
    defaults: { _controller: "HopitalNumeriqueExpertBundle:ActiviteExpert:parametrage" }
    requirements: 
        id : \d+ 

#-Action du grid
hopitalnumerique_expert_expert_payer_facture:
    pattern:  /expert/activite/facture/payer/{id}
    defaults: { _controller: "HopitalNumeriqueExpertBundle:ActiviteExpert:payerFacture" }
    requirements:
        id: \d+
        _method: GET|POST

hopitalnumerique_expert_expert_generer_facture:
    pattern:  /expert/activite/facture/generer/{id}
    defaults: { _controller: "HopitalNumeriqueExpertBundle:ActiviteExpert:genererFacture" }
    requirements:
        id: \d+
        _method: GET|POST

#-Suppression de masse du grid
delete_mass:
    path:     /expert/activite/deleteMass
    defaults: { _controller: HopitalNumeriqueExpertBundle:ActiviteExpertMassController:deleteMass }

#Evenement expert
hopitalnumerique_expert_evenement_expert:
    pattern:  /expert/evenement/{id}   #id de l'activité
    defaults: { _controller: "HopitalNumeriqueExpertBundle:EvenementExpert:index", id: 1 }
    requirements: 
        _method: GET|POST

hopitalnumerique_expert_evenement_expert_add:
    pattern:  /expert/evenement/add/{id}  #id de l'activité
    defaults: { _controller: "HopitalNumeriqueExpertBundle:EvenementExpert:add" , id: 1}
    requirements: 
        _method: GET|POST

hopitalnumerique_expert_evenement_expert_edit:
    pattern:  /expert/evenement/edit/{id}  #id de l'evenement
    defaults: { _controller: "HopitalNumeriqueExpertBundle:EvenementExpert:edit", id: 1 }
    requirements:
        id: \d+
        _method: GET|POST

#---Impression Fiche
hopitalnumerique_expert_evenement_expert_impression_fiche:
    pattern:  /expert/evenement/fiche-presence/{id}
    defaults: { _controller: "HopitalNumeriqueExpertBundle:EvenementExpert:impressionFichePresence" }
    requirements:
        id: \d+
        _method: GET

#-Fancy de modif de la vacation
hopitalnumerique_expert_expert_expert_parametrage:
    pattern:  /expert/evenement/parametrage/{id}
    defaults: { _controller: "HopitalNumeriqueExpertBundle:EvenementExpert:parametrage" }
    requirements: 
        id : \d+ 

hopitalnumerique_expert_expert_expert_parametrage_save:
    pattern:  /expert/evenement/parametrage/{id}/save
    defaults: { _controller: "HopitalNumeriqueExpertBundle:EvenementExpert:parametrageSave" }
    requirements:
        id: \d+

