fos_user_security:
    prefix:   /admin
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

# ----- Front Office -----

#Utilisateur  
hopital_numerique_user_inscription:
    pattern:  /compte-hn/inscription
    defaults: { _controller: HopitalNumeriqueUserBundle:User:inscription }

hopital_numerique_user_informations_personnelles:
    pattern:  /compte-hn/informationsPersonnelles
    defaults: { _controller: HopitalNumeriqueUserBundle:User:informationsPersonnelles }

#Utilisateur - ajax
hopital_numerique_user_front_departements:
    pattern:  /compte-hn/inscription/departements
    defaults: { _controller: HopitalNumeriqueUserBundle:User:ajaxEditDepartements }

hopital_numerique_user_front_etablissements:
    pattern:  /compte-hn/inscription/etablissements
    defaults: { _controller: HopitalNumeriqueUserBundle:User:ajaxEditEtablissements }

#Expert
hopitalnumerique_user_expert_front_edit:
    pattern:  /compte-hn/expert/edit
    defaults: { _controller: "HopitalNumeriqueUserBundle:Expert:editFront", id: 1 }
    requirements:
        id: \d+

#Ambassadeur
hopitalnumerique_user_ambassadeur_front_edit:
    pattern:  /compte-hn/ambassadeur/edit
    defaults: { _controller: "HopitalNumeriqueUserBundle:Ambassadeur:editFront", id: 1 }
    requirements:
        id: \d+

# ----- Back Office -----

#Utilisateur 
hopital_numerique_user_homepage:
    pattern:  /admin/user
    defaults: { _controller: HopitalNumeriqueUserBundle:User:index }

hopital_numerique_user_add:
    pattern:  /admin/user/add
    defaults: { _controller: HopitalNumeriqueUserBundle:User:add }

hopital_numerique_user_edit:
    pattern: /admin/user/edit/{id}
    defaults: { _controller: HopitalNumeriqueUserBundle:User:edit, id: 1 }
    requirements:
        id: \d+

hopital_numerique_user_show:
    pattern: /admin/user/show/{id}
    defaults: { _controller: HopitalNumeriqueUserBundle:User:show, id: 1}
    requirements:
        id: \d+

hopital_numerique_user_delete:
    pattern: /admin/user/delete/{id}.{_format}
    defaults: { _controller: HopitalNumeriqueUserBundle:User:delete, _format: json}
    requirements:
        id: \d+
        _method: post|delete

#Utilisateur - ajax
hopital_numerique_user_departements:
    pattern:  /admin/user/departements
    defaults: { _controller: HopitalNumeriqueUserBundle:User:ajaxEditDepartements }

hopital_numerique_user_etablissements:
    pattern:  /admin/user/etablissements
    defaults: { _controller: HopitalNumeriqueUserBundle:User:ajaxEditEtablissements }

#Contractualisation
hopitalnumerique_user_contractualisation:
    pattern:  /admin/user/contractualisation/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Contractualisation:index", id: 1 }
    requirements:
        id: \d+

hopitalnumerique_user_contractualisation_add:
    pattern:  /admin/user/contractualisation/add/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Contractualisation:add", id: 1  }
    requirements:
        id: \d+

hopitalnumerique_user_contractualisation_show:
    pattern:  /admin/user/contractualisation/show/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Contractualisation:show", id: 1 }
    requirements:
        id: \d+

hopitalnumerique_user_contractualisation_dowload:
    pattern:  /admin/user/contractualisation/dowload/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Contractualisation:dowload", id: 1 }
    requirements:
        id: \d+

hopitalnumerique_user_contractualisation_edit:
    pattern:  /admin/user/contractualisation/edit/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Contractualisation:edit", id: 1 }
    requirements:
        id: \d+

hopitalnumerique_user_contractualisation_delete:
    pattern:  /admin/user/contractualisation/delete/{id}.{_format}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Contractualisation:delete", _format: json }
    requirements: 
        id: \d+
        _method: post|delete

#Contractualisation - archiver
hopitalnumerique_user_contractualisation_archiver:
    pattern:  /admin/user/contractualisation/archiver/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Contractualisation:archiver", _format: json }
    requirements:
        id: \d+

#Contractualisation - ajax
hopitalnumerique_user_contractualisation_isFileExist:
    pattern:  /admin/user/contractualisation/isFileExist
    defaults: { _controller: "HopitalNumeriqueUserBundle:Contractualisation:isFileExist" }

#Contractualisation - liste
hopitalnumerique_user_contractualisation_liste:
    pattern:  /admin/user/contractualisation/liste/{idUser}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Contractualisation:liste", id: 1 }
    requirements:
        idUser: \d+

#Expert
hopitalnumerique_user_expert_edit:
    pattern:  /admin/user/expert/edit/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Expert:edit", id: 1 }
    requirements:
        id: \d+        

hopitalnumerique_user_expert_fiche:
    pattern: /admin/user/expert/show/{idUser}
    defaults: { _controller: HopitalNumeriqueUserBundle:Expert:show, idUser: 1 }
    requirements:
        idUser: \d+

hopitalnumerique_user_expert_download:
    pattern: /admin/user/expert/dowload/{id}
    defaults: { _controller: HopitalNumeriqueUserBundle:Expert:dowload, id: 1 }
    requirements:
        id: \d+

hopitalnumerique_user_expert_deleteAll:
    pattern: /admin/user/expert/{idUser}/{idQuestionnaire}
    defaults: { _controller: HopitalNumeriqueUserBundle:Expert:deleteAll, _format: json, idUser: 1, idQuestionnaire: 1 }
    requirements:
        idUser: \d+
        idQuestionnaire: \d+
        _method: post|delete

hopitalnumerique_user_expert_validationCandidature:
    pattern: /admin/user/expert/validation/{user}
    defaults: { _controller: HopitalNumeriqueUserBundle:Expert:validationCandidature, _format: json, user: 1}
    requirements:
        user: \d+
        _method: post

hopitalnumerique_user_expert_refusCandidature:
    pattern: /admin/user/expert/refus/{user}
    defaults: { _controller: HopitalNumeriqueUserBundle:Expert:refusCandidature, _format: json, user: 1}
    requirements:
        user: \d+

hopitalnumerique_user_expert_messageRefusCandidature:
    pattern: /admin/user/expert/messagerefus
    defaults: { _controller: HopitalNumeriqueUserBundle:Expert:messageRefusCandidature}

#Ambassadeur
hopitalnumerique_user_ambassadeur_edit:
    pattern:  /admin/user/ambassadeur/edit/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Ambassadeur:edit", id: 1 }
    requirements:
        id: \d+

hopitalnumerique_user_ambassadeur_fiche:
    pattern: /admin/user/ambassadeur/show/{idUser}
    defaults: { _controller: HopitalNumeriqueUserBundle:Ambassadeur:show, idUser: 1 }
    requirements:
        idUser: \d+

hopitalnumerique_user_ambassadeur_deleteAll:
    pattern: /admin/user/ambassadeur/deleteAll/{idUser}/{idQuestionnaire}
    defaults: { _controller: HopitalNumeriqueUserBundle:Ambassadeur:deleteAll, _format: json, idUser: 1, idQuestionnaire: 1 }
    requirements:
        idUser: \d+
        idQuestionnaire: \d+
        _method: post|delete

hopitalnumerique_user_ambassadeur_validationCandidature:
    pattern: /admin/user/ambassadeur/validation/{user}
    defaults: { _controller: HopitalNumeriqueUserBundle:Ambassadeur:validationCandidature, _format: json, user: 1}
    requirements:
        user: \d+
        _method: post

hopitalnumerique_user_ambassadeur_refusCandidature:
    pattern: /admin/user/ambassadeur/refus/{user}
    defaults: { _controller: HopitalNumeriqueUserBundle:Ambassadeur:refusCandidature, _format: json, user: 1}
    requirements:
        user: \d+
        _method: post

hopitalnumerique_user_ambassadeur_messageRefusCandidature:
    pattern: /admin/user/ambassadeur/messagerefus
    defaults: { _controller: HopitalNumeriqueUserBundle:Ambassadeur:messageRefusCandidature}

hopitalnumerique_user_ambassadeur_liste_objets:
    pattern:  /admin/user/ambassadeur/listeobjets/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Ambassadeur:listeObjets", id: 1 }
    requirements:
        id: \d+

hopitalnumerique_user_ambassadeur_objets:
    pattern:  /admin/user/ambassadeur/objets/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Ambassadeur:objets", id: 1 }
    requirements:
        id: \d+

hopitalnumerique_user_ambassadeur_addobjet:
    pattern: /admin/user/ambassadeur/addObjet/{id}
    defaults: { _controller: HopitalNumeriqueUserBundle:Ambassadeur:addObjet, _format: json, id: 1 }
    requirements:
        id: \d+

hopitalnumerique_user_ambassadeur_deleteobjet:
    pattern: /admin/user/ambassadeur/deleteObjet/{id}/{user}
    defaults: { _controller: HopitalNumeriqueUserBundle:Ambassadeur:deleteObjet, _format: json, id: 1, user: 1 }
    requirements:
        id: \d+
        user: \d+
        _method: post|delete

hopitalnumerique_user_ambassadeur_saveobjet:
    pattern: /admin/user/ambassadeur/saveObjet
    defaults: { _controller: HopitalNumeriqueUserBundle:Ambassadeur:saveObjet, _format: json }
