fos_user_security:
    prefix:   /admin
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_registration:
    prefix:   /compte-hn/acces-compte
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"



# ----- Front Office -----

#Utilisateur  
hopital_numerique_user_inscription:
    pattern:  /compte-hn/inscription
    defaults: { _controller: HopitalNumeriqueUserBundle:User:inscription }

hopital_numerique_user_desinscription:
    pattern:  /compte-hn/desinscription
    defaults: { _controller: HopitalNumeriqueUserBundle:User:desinscription }

hopital_numerique_user_informations_personnelles:
    pattern:  /compte-hn/informations-personnelles    
    defaults: { _controller: HopitalNumeriqueUserBundle:User:informationsPersonnelles }

hopital_numerique_user_front_departements_informationsPersonelles:
    pattern:  /compte-hn/informations-personnelles/departements
    defaults: { _controller: HopitalNumeriqueUserBundle:User:ajaxEditDepartements }

hopital_numerique_user_front_etablissements_informationsPersonelles:
    pattern:  /compte-hn/informations-personnelles/etablissements
    defaults: { _controller: HopitalNumeriqueUserBundle:User:ajaxEditEtablissements }

#Modication de mot de passe
hopital_numerique_user_motdepasse:
    pattern:  /compte-hn/mot-de-passe
    defaults: { _controller: HopitalNumeriqueUserBundle:User:motDePasse }

#Utilisateur - ajax
hopital_numerique_user_front_departements:
    pattern:  /compte-hn/inscription/departements
    defaults: { _controller: HopitalNumeriqueUserBundle:User:ajaxEditDepartements }

hopital_numerique_user_front_etablissements:
    pattern:  /compte-hn/inscription/etablissements
    defaults: { _controller: HopitalNumeriqueUserBundle:User:ajaxEditEtablissements }

#Expert
hopitalnumerique_user_expert_front_edit:
    pattern:  /compte-hn/expert/edit
    defaults: { _controller: "HopitalNumeriqueUserBundle:Expert:editFront", id: 1 }
    requirements:
        id: \d+

#Ambassadeur
hopitalnumerique_user_ambassadeur_front_edit:
    pattern:  /compte-hn/ambassadeur/edit
    defaults: { _controller: "HopitalNumeriqueUserBundle:Ambassadeur:editFront", id: 1 }
    requirements:
        id: \d+

# ----- Back Office -----

#Utilisateur
hopital_numerique_user_homepage:
    pattern:  /admin/user
    defaults: { _controller: HopitalNumeriqueUserBundle:User:index }

hopital_numerique_user_homepage_filtre:
    pattern:  /admin/user-filtre/{filtre}
    defaults: { _controller: HopitalNumeriqueUserBundle:User:indexFiltre, filtre: null }

hopital_numerique_user_add:
    pattern:  /admin/user/add
    defaults: { _controller: HopitalNumeriqueUserBundle:User:add }

hopital_numerique_user_edit:
    pattern: /admin/user/edit/{id}
    defaults: { _controller: HopitalNumeriqueUserBundle:User:edit, id: 1 }
    requirements:
        id: \d+

hopital_numerique_user_show:
    pattern: /admin/user/show/{id}
    defaults: { _controller: HopitalNumeriqueUserBundle:User:show, id: 1}
    requirements:
        id: \d+

hopital_numerique_user_historique:
    pattern: /admin/user/historique/{id}
    defaults: { _controller: HopitalNumeriqueUserBundle:User:historique}
    requirements:
        id: \d+

hopital_numerique_user_delete:
    pattern: /admin/user/delete/{id}.{_format}
    defaults: { _controller: HopitalNumeriqueUserBundle:User:delete, _format: json}
    requirements:
        id: \d+

#Utilisateur - ajax
hopital_numerique_user_departements:
    pattern:  /admin/user/departements
    defaults: { _controller: HopitalNumeriqueUserBundle:User:ajaxEditDepartements }

hopital_numerique_user_etablissements:
    pattern:  /admin/user/etablissements
    defaults: { _controller: HopitalNumeriqueUserBundle:User:ajaxEditEtablissements }

#Contractualisation
hopitalnumerique_user_contractualisation:
    pattern:  /admin/user/contractualisation/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Contractualisation:index", id: 1 }
    requirements:
        id: \d+

hopitalnumerique_user_contractualisation_add:
    pattern:  /admin/user/contractualisation/add/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Contractualisation:add", id: 1  }
    requirements:
        id: \d+

hopitalnumerique_user_contractualisation_show:
    pattern:  /admin/user/contractualisation/show/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Contractualisation:show", id: 1 }
    requirements:
        id: \d+

hopitalnumerique_user_contractualisation_dowload:
    pattern:  /admin/user/contractualisation/dowload/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Contractualisation:dowload", id: 1 }
    requirements:
        id: \d+

hopitalnumerique_user_contractualisation_edit:
    pattern:  /admin/user/contractualisation/edit/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Contractualisation:edit", id: 1 }
    requirements:
        id: \d+

hopitalnumerique_user_contractualisation_delete:
    pattern:  /admin/user/contractualisation/delete/{id}.{_format}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Contractualisation:delete", _format: json }
    requirements: 
        id: \d+

#Contractualisation - archiver
hopitalnumerique_user_contractualisation_archiver:
    pattern:  /admin/user/contractualisation/archiver/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Contractualisation:archiver", _format: json }
    requirements:
        id: \d+

#Contractualisation - liste
hopitalnumerique_user_contractualisation_liste:
    pattern:  /admin/user/contractualisation/liste/{idUser}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Contractualisation:liste", id: 1 }
    requirements:
        idUser: \d+

#Expert
hopitalnumerique_user_expert_edit:
    pattern:  /admin/user/expert/edit/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Expert:edit", id: 1 }
    requirements:
        id: \d+     

hopitalnumerique_user_expert_fiche:
    pattern: /admin/user/expert/show/{idUser}
    defaults: { _controller: HopitalNumeriqueUserBundle:Expert:show, idUser: 1 }
    requirements:
        idUser: \d+

hopitalnumerique_user_expert_validationCandidature:
    pattern: /admin/user/expert/validation/{user}
    defaults: { _controller: HopitalNumeriqueUserBundle:Expert:validationCandidature, _format: json, user: 1}
    requirements:
        user: \d+

hopitalnumerique_user_expert_refusCandidature:
    pattern: /admin/user/expert/refus/{user}
    defaults: { _controller: HopitalNumeriqueUserBundle:Expert:refusCandidature, _format: json, user: 1}
    requirements:
        user: \d+

hopitalnumerique_user_expert_messageRefusCandidature:
    pattern: /admin/user/expert/messagerefus
    defaults: { _controller: HopitalNumeriqueUserBundle:Expert:messageRefusCandidature}

#Ambassadeur
hopitalnumerique_user_ambassadeur_edit:
    pattern:  /admin/user/ambassadeur/edit/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Ambassadeur:edit", id: 1 }
    requirements:
        id: \d+

hopitalnumerique_user_ambassadeur_fiche:
    pattern: /admin/user/ambassadeur/show/{idUser}
    defaults: { _controller: HopitalNumeriqueUserBundle:Ambassadeur:show, idUser: 1 }
    requirements:
        idUser: \d+

hopitalnumerique_user_ambassadeur_validationCandidature:
    pattern: /admin/user/ambassadeur/validation/{user}
    defaults: { _controller: HopitalNumeriqueUserBundle:Ambassadeur:validationCandidature, _format: json, user: 1}
    requirements:
        user: \d+

hopitalnumerique_user_ambassadeur_refusCandidature:
    pattern: /admin/user/ambassadeur/refus/{user}
    defaults: { _controller: HopitalNumeriqueUserBundle:Ambassadeur:refusCandidature, _format: json, user: 1}
    requirements:
        user: \d+

hopitalnumerique_user_ambassadeur_messageRefusCandidature:
    pattern: /admin/user/ambassadeur/messagerefus
    defaults: { _controller: HopitalNumeriqueUserBundle:Ambassadeur:messageRefusCandidature}

hopitalnumerique_user_ambassadeur_liste_objets:
    pattern:  /admin/user/ambassadeur/listeobjets/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Ambassadeur:listeObjets", id: 1 }
    requirements:
        id: \d+

hopitalnumerique_user_ambassadeur_objets:
    pattern:  /admin/user/ambassadeur/objets/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Ambassadeur:objets", id: 1 }
    requirements:
        id: \d+

hopitalnumerique_user_ambassadeur_addobjet:
    pattern: /admin/user/ambassadeur/addObjet/{id}
    defaults: { _controller: HopitalNumeriqueUserBundle:Ambassadeur:addObjet, _format: json, id: 1 }
    requirements:
        id: \d+

hopitalnumerique_user_ambassadeur_deleteobjet:
    pattern: /admin/user/ambassadeur/deleteObjet/{id}/{user}
    defaults: { _controller: HopitalNumeriqueUserBundle:Ambassadeur:deleteObjet, _format: json, id: 1, user: 1 }
    requirements:
        id: \d+
        user: \d+

hopitalnumerique_user_ambassadeur_saveobjet:
    pattern: /admin/user/ambassadeur/saveObjet
    defaults: { _controller: HopitalNumeriqueUserBundle:Ambassadeur:saveObjet, _format: json }

hopitalnumerique_user_ambassadeur_domainesFonctionnels:
    pattern:  /admin/user/ambassadeur/connaissances-metiers/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Ambassadeur:domainesFonctionnels", id: 1 }
    requirements:
        id: \d+

hopitalnumerique_user_ambassadeur_savedomaine:
    pattern: /admin/user/ambassadeur/saveDomaine
    defaults: { _controller: HopitalNumeriqueUserBundle:Ambassadeur:saveDomaine, _format: json }

hopitalnumerique_user_ambassadeur_connaissancesSI:
    pattern:  /admin/user/ambassadeur/connaissances-SI/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:Ambassadeur:connaissancesSI", id: 1 }
    requirements:
        id: \d+

hopitalnumerique_user_ambassadeur_saveConnaissancesSI:
    pattern: /admin/user/ambassadeur/saveConnaissancesSI
    defaults: { _controller: HopitalNumeriqueUserBundle:Ambassadeur:saveConnaissancesSI, _format: json }

#Utilisateur
hopital_numerique_user_resultats:
    pattern:  /admin/user/{id}/resultats
    defaults: { _controller: HopitalNumeriqueUserBundle:Resultat:index }

#Refus candidature
hopitalnumerique_user_refuscandidature:
    pattern:  /admin/user/refuscandidature
    defaults: { _controller: "HopitalNumeriqueUserBundle:RefusCandidature:index" }
    requirements: 
        _method: GET|POST


hopitalnumerique_user_refuscandidature_show:
    pattern:  /admin/user/refuscandidature/show/{id}
    defaults: { _controller: "HopitalNumeriqueUserBundle:RefusCandidature:show", id: 1 }
    requirements:
        id: \d+
        _method: GET

hopital_numerique_user_get_user_from_email_forAutodiag:
    pattern:  /compte-hn/autodiagnostic/recuperation-user
    defaults: { _controller: HopitalNumeriqueUserBundle:User:getUserFromEmail }

