parameters:
    #Permet d'avoir une valeur par défaut et/ou d'etre surchargé par le config.yml de app/config
    hopital_numerique_user.options: ~
    hopitalnumerique_user.options_config.class: HopitalNumerique\UserBundle\Util\OptionsConfig
    #Utilisateur
    hopitalnumerique_user.manager.user.class: HopitalNumerique\UserBundle\Manager\UserManager
    hopitalnumerique_user.form.type.user: HopitalNumerique\UserBundle\Form\Type\UserType
    hopitalnumerique_user.grid.user.class: HopitalNumerique\UserBundle\Grid\UserGrid
    #Contractualisation
    hopitalnumerique_user.manager.contractualisation.class: HopitalNumerique\UserBundle\Manager\ContractualisationManager
    hopitalnumerique_user.grid.contractualisation.class: HopitalNumerique\UserBundle\Grid\ContractualisationGrid
    hopitalnumerique_user.form.contractualisation.class: HopitalNumerique\UserBundle\Form\Type\ContractualisationType
    #Contractualisation - grid  column  
    hopitalnumerique_user.column.contractualisation.class: HopitalNumerique\UserBundle\Grid\Column\ContractualisationColumn
    #Ambassadeurs
    hopitalnumerique_user.grid.objet.class: HopitalNumerique\UserBundle\Grid\ObjetGrid
    #Etablissements
    hopitalnumerique_user.grid.etablissement.class: HopitalNumerique\UserBundle\Grid\EtablissementGrid

services:
    #Utilisateur:
    #--Manager
    hopitalnumerique_user.manager.user:
        class: %hopitalnumerique_user.manager.user.class%
        arguments: ["@doctrine.orm.entity_manager", "@hopitalnumerique_questionnaire.manager.reponse", "@hopitalnumerique_questionnaire.manager.questionnaire"]
        calls:
            - [ setCache, [ @liip_doctrine_cache.ns.main ] ]
    #--Type
    hopitalnumerique_user.form.type.user:
        class: %hopitalnumerique_user.form.type.user%
        arguments: ["@hopitalnumerique_user.manager.user", "@validator", "@nodevo_role.manager.role", "@security.context"]
        tags:
            - { name: form.type, alias: nodevo_user_user }
    #--Grid
    hopitalnumerique_user.grid.user:
        class: %hopitalnumerique_user.grid.user.class%
        arguments: ["@service_container"]
    #--OptionsConfig
    hopitalnumerique_user.options.user:
        class: %hopitalnumerique_user.options_config.class%
        arguments: ["%hopital_numerique_user.options%"]

    #Contractualisation
    #--Manager
    hopitalnumerique_user.manager.contractualisation:
        class: %hopitalnumerique_user.manager.contractualisation.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
           - [ setCache, [ @liip_doctrine_cache.ns.main ] ]
    #--Grid
    hopitalnumerique_user.grid.contractualisation:
        class: %hopitalnumerique_user.grid.contractualisation.class%
        arguments: ["@service_container"]
    #--Grid-Column
#    hopitalnumerique_user.grid.column.contractualisation:
#       class: %hopitalnumerique_user.column.contractualisation.class%
#       tags:
#            - { name: grid.column.extension }
    #--Type
    hopitalnumerique_user.form.contractualisation:
        class: %hopitalnumerique_user.form.contractualisation.class%
        arguments: ["@hopitalnumerique_user.manager.contractualisation", "@validator"]
        tags:
            - { name: form.type, alias: hopitalnumerique_user_contractualisation }

    #Ambassadeurs
    #--Grid
    hopitalnumerique_user.grid.objet:
        class: %hopitalnumerique_user.grid.objet.class%
        arguments: ["@service_container"]

    #Etablissement
    #--Grid
    hopitalnumerique_user.grid.etablissement:
        class: %hopitalnumerique_user.grid.etablissement.class%
        arguments: ["@service_container"]

    #HOOK redirect response after password reset
    hopitalnumerique_user.password_resetting:
        class: HopitalNumerique\UserBundle\EventListener\PasswordResettingListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
    #GestionAffichageOnglet
    hopitalnumerique_user.gestion_affichage_onglet:
        class: HopitalNumerique\UserBundle\Util\GestionAffichageOnglets
        arguments: ["@hopitalnumerique_questionnaire.manager.reponse", "@hopitalnumerique_questionnaire.manager.questionnaire"]