parameters:
    #Permet d'avoir une valeur par défaut et/ou d'etre surchargé par le config.yml de app/config
    hopital_numerique_user.options: ~
    hopitalnumerique_user.options_config.class: HopitalNumerique\UserBundle\Util\OptionsConfig
    #Utilisateur
    hopitalnumerique_user.manager.user.class: HopitalNumerique\UserBundle\Manager\UserManager
    hopitalnumerique_user.form.type.user: HopitalNumerique\UserBundle\Form\Type\UserType
    hopitalnumerique_user.grid.user.class: HopitalNumerique\UserBundle\Grid\UserGrid
    #Mot-de-passe
    hopitalnumerique_user.form.type.motdepasse: HopitalNumerique\UserBundle\Form\Type\MotDePasseType
    #Desinscription
    hopitalnumerique_user.form.type.desinscription: HopitalNumerique\UserBundle\Form\Type\DesinscriptionType
    #Contractualisation
    hopitalnumerique_user.manager.contractualisation.class: HopitalNumerique\UserBundle\Manager\ContractualisationManager
    hopitalnumerique_user.grid.contractualisation.class: HopitalNumerique\UserBundle\Grid\ContractualisationGrid
    hopitalnumerique_user.form.contractualisation.class: HopitalNumerique\UserBundle\Form\Type\ContractualisationType
    #Contractualisation - grid  column
    hopitalnumerique_user.column.contractualisation.class: HopitalNumerique\UserBundle\Grid\Column\ContractualisationColumn
    #Refus candidature
    hopitalnumerique_user.manager.refus_candidature.class: HopitalNumerique\UserBundle\Manager\RefusCandidatureManager
    #Ambassadeurs
    hopitalnumerique_user.grid.objet.class: HopitalNumerique\UserBundle\Grid\ObjetGrid
    hopitalnumerique_user.manager.connaissance_ambassadeur.class: HopitalNumerique\UserBundle\Manager\ConnaissanceAmbassadeurManager
    hopitalnumerique_user.manager.connaissance_ambassadeur_si.class: HopitalNumerique\UserBundle\Manager\ConnaissanceAmbassadeurSIManager
    #Etablissements
    hopitalnumerique_user.grid.etablissement.class: HopitalNumerique\UserBundle\Grid\EtablissementGrid
    #Extensions twig
    hopitalnumerique_user.twig.extensions.class: HopitalNumerique\UserBundle\Twig\UserExtension
    #Login - event
    hopitalnumerique_user.manager.login.class: HopitalNumerique\UserBundle\Manager\LoginManager
    #Refus candidature
    hopitalnumerique_user.manager.refuscandidature.class: HopitalNumerique\UserBundle\Manager\RefusCandidatureManager
    hopitalnumerique_user.grid.refuscandidature.class: HopitalNumerique\UserBundle\Grid\RefusCandidatureGrid
    #Listener
    hopitalnumerique_user.listener.user.class: HopitalNumerique\UserBundle\EventListener\UserUpdateListener
    #Login Handler
    hopitalnumerique_user.handler.login.class: HopitalNumerique\UserBundle\Handler\LoginHandler

services:
    #Utilisateur:
    #--Manager
    hopitalnumerique_user.manager.user:
        class: %hopitalnumerique_user.manager.user.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.context"
            - "@hopitalnumerique_questionnaire.manager.reponse"
            - "@hopitalnumerique_user.manager.refus_candidature"
            - "@hopitalnumerique_domaine.manager.domaine"
            - '@hopitalnumerique_paiement.manager.remboursement'
            - '@hopitalnumerique_domaine.dependency_injection.current_domaine'
            - '@event_dispatcher'
    #--Type
    hopitalnumerique_user.form.type.user:
        class: %hopitalnumerique_user.form.type.user%
        arguments:
            - '@hopitalnumerique_user.manager.user'
            - '@validator'
            - '@nodevo_role.manager.role'
            - '@security.context'
            - '@hopitalnumerique_user.manager.user'
            - '@hopitalnumerique_reference.manager.reference'
            - '@hopitalnumerique_etablissement.manager.etablissement'
        tags:
            - { name: form.type, alias: nodevo_user_user }

    hopitalnumerique_user.form.type.registration:
        class: HopitalNumerique\UserBundle\Form\Type\RegistrationType
        arguments:
            - "@hopitalnumerique_reference.manager.reference"
        tags:
            - { name: form.type, alias: nodevo_user_registration }
    #--Grid
    hopitalnumerique_user.grid.user:
        class: %hopitalnumerique_user.grid.user.class%
        arguments: ["@service_container"]
    #--OptionsConfig
    hopitalnumerique_user.options.user:
        class: %hopitalnumerique_user.options_config.class%
        arguments: ["%hopital_numerique_user.options%"]
    #MotDePasse:
    #--Formulaire
    hopitalnumerique_user.form.type.motdepasse:
        class: %hopitalnumerique_user.form.type.motdepasse%
        arguments: ["@hopitalnumerique_user.manager.user"]
        tags:
            - { name: form.type, alias: nodevo_user_motdepasse }
    #Desinscription:
    #--Formulaire
    hopitalnumerique_user.form.type.desinscription:
        class: %hopitalnumerique_user.form.type.desinscription%
        arguments: ["@hopitalnumerique_user.manager.user"]
        tags:
            - { name: form.type, alias: nodevo_user_desinscription }

    #Contractualisation
    #--Manager
    hopitalnumerique_user.manager.contractualisation:
        class: %hopitalnumerique_user.manager.contractualisation.class%
        arguments: ["@doctrine.orm.entity_manager"]
    #--Grid
    hopitalnumerique_user.grid.contractualisation:
        class: %hopitalnumerique_user.grid.contractualisation.class%
        arguments: ["@service_container"]
    #--Grid-Column
#    hopitalnumerique_user.grid.column.contractualisation:
#       class: %hopitalnumerique_user.column.contractualisation.class%
#       tags:
#            - { name: grid.column.extension }
    #--Type
    hopitalnumerique_user.form.contractualisation:
        class: %hopitalnumerique_user.form.contractualisation.class%
        arguments: ["@hopitalnumerique_user.manager.contractualisation", "@validator"]
        tags:
            - { name: form.type, alias: hopitalnumerique_user_contractualisation }

    #Refus candidature
    #--Manager
    hopitalnumerique_user.manager.refus_candidature:
        class: %hopitalnumerique_user.manager.refus_candidature.class%
        arguments: ["@doctrine.orm.entity_manager"]
    #--Grid
    hopitalnumerique_user.grid.refuscandidature:
        class: %hopitalnumerique_user.grid.refuscandidature.class%
        arguments: ["@service_container"]

    #Ambassadeurs
    #--Grid
    hopitalnumerique_user.grid.objet:
        class: %hopitalnumerique_user.grid.objet.class%
        arguments: ["@service_container"]
    #--Manager
    hopitalnumerique_user.manager.connaissance_ambassadeur:
        class: %hopitalnumerique_user.manager.connaissance_ambassadeur.class%
        arguments: ["@doctrine.orm.entity_manager"]
    #--Manager
    hopitalnumerique_user.manager.connaissance_ambassadeur_si:
        class: %hopitalnumerique_user.manager.connaissance_ambassadeur_si.class%
        arguments: ["@doctrine.orm.entity_manager"]

    #Etablissement
    #--Grid
    hopitalnumerique_user.grid.etablissement:
        class: %hopitalnumerique_user.grid.etablissement.class%
        arguments: ["@service_container"]

    #HOOK redirect response after password reset
    hopitalnumerique_user.password_resetting:
        class: HopitalNumerique\UserBundle\EventListener\PasswordResettingListener
        arguments: ["@router"]
        tags:
            - { name: kernel.event_subscriber }

    #GestionAffichageOnglet
    hopitalnumerique_user.gestion_affichage_onglet:
        class: HopitalNumerique\UserBundle\Util\GestionAffichageOnglets
        arguments: ["@hopitalnumerique_questionnaire.manager.reponse", "@hopitalnumerique_questionnaire.manager.questionnaire"]

    #Extension Twig
    hopitalnumerique_user.twig.user_extension:
        class: %hopitalnumerique_user.twig.extensions.class%
        arguments: ['@security.csrf.token_manager', "@hopitalnumerique_reference.manager.reference", "@hopitalnumerique_etablissement.manager.etablissement", "@hopitalnumerique_questionnaire.manager.questionnaire"]
        tags:
            - { name: twig.extension }

    #Login
    #--Manager
    hopitalnumerique_user.manager.login:
        class: %hopitalnumerique_user.manager.login.class%
        tags:
            - { name: 'kernel.event_subscriber'}
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }

    #Listener
    hopitalnumerique_user.listener.user:
        class: %hopitalnumerique_user.listener.user.class%
        arguments: ["@nodevo_mail.manager.mail", "@mailer", '@hopitalnumerique_reference.doctrine.referencement_deleter']
        tags:
            - { name: 'kernel.event_subscriber' }

    hopitalnumerique_user.subscriber.token:
        class: HopitalNumerique\UserBundle\EventListener\TokenSubscriber
        arguments:
            - '@session'
            - '@hopitalnumerique_user.token.token_storage'
        tags:
            - { name: 'kernel.event_subscriber' }

    HopitalNumerique\UserBundle\EventListener\CommunautePratiqueSubscriber:
        class: HopitalNumerique\UserBundle\EventListener\CommunautePratiqueSubscriber
        arguments:
            - '@hopitalnumerique_user.manager.user'
        tags:
            - { name: 'kernel.event_subscriber' }

    #--Handler
    hopitalnumerique_user.handler.login:
        class:  %hopitalnumerique_user.handler.login.class%
        arguments:  ["@router", "@security.context", '@hopitalnumerique_recherche.dependency_injection.referencement.requete_session', "@nodevo_acl.manager.acl", "@hopitalnumerique_user.manager.user", "@hopitalnumerique_domaine.manager.domaine"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }


    hopitalnumerique_user.form.user.informations_manquantes:
        class: 'HopitalNumerique\UserBundle\Form\Type\User\InformationsManquantesType'
        arguments: ['@security.token_storage', '@router', '@request_stack', '@hopitalnumerique_reference.manager.reference', '@hopitalnumerique_etablissement.manager.etablissement']
        tags:
            - { name: 'form.type', alias: 'nodevouser_user_informationsmanquantes' }

    hopitalnumerique_user.dependency_injection.connected_user:
        class: 'HopitalNumerique\UserBundle\DependencyInjection\ConnectedUser'
        arguments: ['@security.token_storage']

    hopitalnumerique_user.service.active_member_calculator:
        class: 'HopitalNumerique\UserBundle\Service\ActiveMemberCalculator'
        arguments:
            - "@hopitalnumerique_objet.repository.commentaire"
            - "@hopitalnumerique_objet.repository.note"
            - "@ccdn_forum_forum.repository.post"
            - "@nodevo_mail.repository.recommendation_mail_log"
            - '@hopitalnumerique_user.repository.user'

    hopitalnumerique_user.form.type.account:
        class: HopitalNumerique\UserBundle\Form\Type\UserAccountType
        arguments:
            - "@hopitalnumerique_reference.manager.reference"
            - "@hopitalnumerique_etablissement.manager.etablissement"
            - "@security.token_storage"
        tags:
            - { name: form.type }

    hopitalnumerique_user.repository.user:
        class: HopitalNumerique\UserBundle\Repository\UserRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumerique\UserBundle\Entity\User'

    hopitalnumerique_user.repository.token:
        class: HopitalNumerique\UserBundle\Repository\TokenRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumerique\UserBundle\Entity\Token'

    hopitalnumerique_user.repository.contractualisation:
        class: HopitalNumerique\UserBundle\Repository\ContractualisationRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumerique\UserBundle\Entity\Contractualisation'

    hopitalnumerique_user.token.token_storage:
        class: HopitalNumerique\UserBundle\Service\TokenStorage
        arguments:
            - '@hopitalnumerique_user.repository.token'
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'

    HopitalNumerique\UserBundle\Domain\Command\UpdateUserParametersCommandHandler:
        class: HopitalNumerique\UserBundle\Domain\Command\UpdateUserParametersCommandHandler
        arguments:
            - '@security.token_storage'
            - '@fos_user.user_manager.default'
            - '@hopitalnumerique\notificationbundle\domain\command\updatenotificationsettingshandler'

    HopitalNumerique\UserBundle\Domain\Command\UpdateNotificationsSettingsHandler:
        class: HopitalNumerique\UserBundle\Domain\Command\UpdateNotificationsSettingsHandler
        arguments:
            - '@fos_user.user_manager.default'
            - '@hopitalnumerique\notificationbundle\domain\command\updatenotificationsettingshandler'

    hopitalnumerique_user.widgets.activity:
        class: HopitalNumerique\UserBundle\Service\Widget\ActivityWidget
        tags:
            - { name: new_account.dashboard_widget, type: dashboard }
        arguments:
            - '@twig'
            - '@security.token_storage'
            - '@translator'
            - '@hopitalnumerique_user.service.active_member_calculator'
            - '@hopitalnumerique_rechercheparcours.repository.guided_search'
        calls:
            - method: setRepositories
              arguments:
                - '@hopitalnumerique_recherche.repository.requete'
                - '@hopitalnumerique_objet.repository.consultation'
                - '@autodiag.repository.autodiagentry'
                - '@hopitalnumerique_user.repository.user'
        public: false

    HopitalNumerique\UserBundle\Service\ShareMessageGenerator:
        class: HopitalNumerique\UserBundle\Service\ShareMessageGenerator
        arguments:
            - '@translator'

    HopitalNumerique\UserBundle\Service\Notification\UserRoleUpdatedNotificationProvider:
        class: HopitalNumerique\UserBundle\Service\Notification\UserRoleUpdatedNotificationProvider
        arguments:
            - '@event_dispatcher'
            - '@security.token_storage'
            - '@translator'
            - '@hopitalnumerique_user.repository.user'
            - '@nodevo_role.manager.role'
        tags:
            - { name: notification.aggregator, key: user_role_updated }
        calls:
            - [setMailManager, ['@nodevo_mail.manager.mail']]

    HopitalNumerique\UserBundle\EventListener\UserRoleUpdatedListener:
        class: HopitalNumerique\UserBundle\EventListener\UserRoleUpdatedListener
        arguments: [ '@hopitalnumerique\notificationbundle\service\notifications' ]
        tags:
            - { name: kernel.event_subscriber, event: user.role_updated }
