hopitalnumerique_communautepratique_admin_groupe_list:
    path:  /groupe/liste
    defaults: { _controller: "HopitalNumeriqueCommunautePratiqueBundle:Admin/Groupe:list" }
    methods: GET|POST

hopitalnumerique_communautepratique_admin_groupe_add:
    path:  /groupe/add
    defaults: { _controller: "HopitalNumeriqueCommunautePratiqueBundle:Admin/Groupe:add" }
    methods: GET|POST

hopitalnumerique_communautepratique_admin_groupe_edit:
    path:  /groupe/edit/{id}/{toRef}
    defaults: { _controller: "HopitalNumeriqueCommunautePratiqueBundle:Admin/Groupe:edit", id: null, toRef: 0 }
    methods: GET|POST|PATCH
    requirements:
        id: \d+

hopitalnumerique_communautepratique_admin_groupe_deletemass:
    path:  /groupe/deletemass
    defaults: { _controller: "HopitalNumeriqueCommunautePratiqueBundle:Admin/Groupe:deleteMass" }
    methods: GET|POST
