hopitalnumerique_communautepratique_commentaire_blockview:
    pattern: '/commentaire/{commentaire}/block-view'
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:Commentaire:blockView' }
    methods: 'GET'
    requirements:
        commentaire: \d+

hopitalnumerique_communautepratique_commentaire_edit:
    pattern: '/commentaire/{commentaire}/edit'
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:Commentaire:edit' }
    methods: 'GET|POST'
    requirements:
        commentaire: \d+

hopitalnumerique_communautepratique_commentaire_delete:
    pattern: '/commentaire/{commentaire}/delete'
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:Commentaire:delete' }
    methods: 'POST'
    requirements:
        commentaire: \d+

hopitalnumerique_communautepratique_commentaire_fichecommentaire_add:
    pattern: '/commentaire/fiche/{fiche}/add'
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:Commentaire/FicheCommentaire:add' }
    methods: 'GET|POST'
    requirements:
        fiche: \d+

hopitalnumerique_communautepratique_commentaire_groupecommentaire_add:
    pattern: '/commentaire/groupe/{groupe}/add'
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:Commentaire/GroupeCommentaire:add' }
    methods: 'GET|POST'
    requirements:
        groupe: \d+
