hopitalnumerique_communautepratique_discussions_public:
    path: /
    defaults: { _controller: HopitalNumeriqueCommunautePratiqueBundle:Front/Discussion:public }

hopitalnumerique_communautepratique_discussions_public_desfult_discussion:
    path: /{discussion}
    defaults: { _controller: HopitalNumeriqueCommunautePratiqueBundle:Front/Discussion:public }
    requirements:
        discussion: \d+

hopitalnumerique_communautepratique_discussions_download_discussion:
    path: /{discussion}/download
    defaults: { _controller: HopitalNumeriqueCommunautePratiqueBundle:Front/Discussion:downloadDiscussion }
    requirements:
        discussion: \d+

hopitalnumerique_communautepratique_discussions_copy_discussion:
    path: /{discussion}/copy
    defaults: { _controller: HopitalNumeriqueCommunautePratiqueBundle:Front/Discussion:copyToGroup }
    requirements:
        discussion: \d+

hopitalnumerique_communautepratique_discussions_discussion_read_message:
    path: /reading-message
    defaults: { _controller: HopitalNumeriqueCommunautePratiqueBundle:Front/Discussion:read }
    methods:
        - POST

hopitalnumerique_communautepratique_discussions_create_discussion:
    path: /create
    defaults: { _controller: HopitalNumeriqueCommunautePratiqueBundle:Front/Discussion:createDiscussion }
    methods:
        - POST

hopitalnumerique_communautepratique_discussions_reply_discussion:
    path: /{discussion}/reply
    defaults: { _controller: HopitalNumeriqueCommunautePratiqueBundle:Front/Discussion:reply }
    methods:
        - POST

hopitalnumerique_communautepratique_discussions_edit_reply_discussion:
    path: /{discussion}/edit/{message}
    defaults: { _controller: HopitalNumeriqueCommunautePratiqueBundle:Front/Discussion:reply }
    methods:
        - POST
        - GET

hopitalnumerique_communautepratique_discussions_discussion:
    path: /{discussion}/lire
    defaults: { _controller: HopitalNumeriqueCommunautePratiqueBundle:Front/Discussion:discussion }

hopitalnumerique_communautepratique_discussions_discussion_message_helpful:
    path: /message/{message}/helpful/toggle
    defaults: { _controller: HopitalNumeriqueCommunautePratiqueBundle:Front/Discussion:toggleHelpfulMessage }

hopitalnumerique_communautepratique_discussions_discussion_recommendation:
    path: /{discussion}/recommendation/toggle
    defaults: { _controller: HopitalNumeriqueCommunautePratiqueBundle:Front/Discussion:toggleRecommendation }

hopitalnumerique_communautepratique_discussions_discussion_message_delete:
    path: /message/{message}/delete
    defaults: { _controller: HopitalNumeriqueCommunautePratiqueBundle:Front/Discussion:deleteMessage }

hopitalnumerique_communautepratique_discussions_discussion_message_validate:
    path: /message/{message}/validate
    defaults: { _controller: HopitalNumeriqueCommunautePratiqueBundle:Front/Discussion:validateMessage }
