hopitalnumerique_communautepratique_document_listbygroupe:
    pattern: /groupe/{groupe}
    defaults: { _controller: "HopitalNumeriqueCommunautePratiqueBundle:Document:listByGroupe" }
    methods: GET

hopitalnumerique_communautepratique_document_upload:
    pattern: /groupe/{groupe}/upload
    defaults: { _controller: "HopitalNumeriqueCommunautePratiqueBundle:Document:upload" }
    methods: POST
