hopitalnumerique_communautepratique_groupe_list:
    path: /list
    defaults: { _controller: "HopitalNumeriqueCommunautePratiqueBundle:Groupe:list" }
    methods: GET

hopitalnumerique_communautepratique_groupe_view:
    path: /{groupe}
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:Groupe:view' }
    methods: GET
    requirements:
        groupe: \d+

hopitalnumerique_communautepratique_groupe_inscrit:
    path: /{groupe}/inscription
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:Groupe:inscrit' }
    methods: GET|POST
    requirements:
        groupe: \d+

hopitalnumerique_communautepratique_groupe_validinscription:
    path: /{groupe}/valid-inscription
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:Groupe:validInscription' }
    methods: GET
    requirements:
        groupe: \d+

hopitalnumerique_communautepratique_groupe_panelinformations:
    path: /{groupe}/panel-informations
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:Groupe:panelInformations' }
    methods: GET
    requirements:
        groupe: \d+

hopitalnumerique_communautepratique_groupe_panelusergroupes:
    path: /panel-user-groupes/{user}
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:Groupe:panelUserGroupes' }
    methods: GET
    requirements:
        user: \d+

hopitalnumerique_communautepratique_groupe_export_comments:
    path: /{group}/export
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:Groupe:exportCsv' }
    methods: GET
    requirements:
        group: \d+
