hopitalnumerique_communautepratique_inscription_ajaxinscrit:
    path: /inscription
    defaults: { _controller: "HopitalNumeriqueCommunautePratiqueBundle:Inscription:ajaxInscrit" }
    methods: POST

hopitalnumerique_communautepratique_inscription:
    path: /rejoindre
    defaults: { _controller: "HopitalNumeriqueCommunautePratiqueBundle:Inscription:inscription" }

hopitalnumerique_communautepratique_inscription_ajaxdesinscrit:
    path: /desinscription
    defaults: { _controller: "HopitalNumeriqueCommunautePratiqueBundle:Inscription:ajaxDesinscrit" }
    methods: POST
