hopitalnumerique_communautepratique_publication_list:
    pattern: /list/{page}
    defaults: { _controller: "HopitalNumeriqueCommunautePratiqueBundle:Publication:list", page:1 }
    methods: GET
    requirements:
        page: \d+
