hopitalnumerique_communautepratique_user_list:
    path: /list/{page}/{membreId}
    defaults: { _controller: "HopitalNumeriqueCommunautePratiqueBundle:User:list", page:1, membreId:null}
    methods: GET|POST
    requirements:
        page: \d+
        membreId: \d+

hopitalnumerique_communautepratique_user_details:
    path: /details/{user}
    defaults: { _controller: "HopitalNumeriqueCommunautePratiqueBundle:User:userDetails"}
    methods: GET
    requirements:
        user: \d+

hopitalnumerique_communautepratique_user_listbygroupe:
    path: '/list/groupe/{groupe}/{page}'
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:User:listByGroupe', page:1 }
    methods: 'GET|POST'
    requirements:
        groupe: '\d+'
        page: '\d+'

hopitalnumerique_communautepratique_user_viewforgroupe:
    path: '/view/{user}/groupe/{groupe}'
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:User:viewForGroupe' }
    methods: 'GET'
    requirements:
        user: '\d+'
        groupe: '\d+'

hopitalnumerique_communautepratique_user_desinscritgroupe:
    path: '/groupe/{groupe}/desinscrit/{user}'
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:User:desinscritGroupe' }
    methods: 'POST'
    requirements:
        groupe: '\d+'
        user: '\d+'

hopitalnumerique_communautepratique_user_activegroupe:
    path: '/groupe/{groupe}/activegroupe/{user}'
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:User:activeGroupe' }
    methods: 'POST'
    requirements:
        groupe: '\d+'
        user: '\d+'
