hopitalnumerique_communautepratique_user_list:
    path: /list/{page}/{membreId}
    defaults: { _controller: "HopitalNumeriqueCommunautePratiqueBundle:User:list", page:1, membreId:null}
    methods: GET|POST
    requirements:
        page: \d+
        membreId: \d+

hopitalnumerique_communautepratique_user_details:
    path: /details/{user}/{group}
    defaults: { _controller: "HopitalNumeriqueCommunautePratiqueBundle:User:userDetails", group: null}
    methods: GET
    requirements:
        user: \d+

hopitalnumerique_communautepratique_user_listbygroupe:
    path: '/list/groupe/{groupe}/'
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:User:listByGroupe', filtered: false }
    methods: GET
    requirements:
        groupe: '\d+'

hopitalnumerique_communautepratique_user_listbygroupe_filtered:
    path: '/list/groupe/{groupe}/filtered'
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:User:listByGroupe', filtered: true }
    methods: GET
    requirements:
        groupe: '\d+'

hopitalnumerique_communautepratique_user_add:
    path: '/group/{group}/add-user'
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:User:addUser' }
    methods: POST
    requirements:
        group: '\d+'

hopitalnumerique_communautepratique_user_viewforgroupe:
    path: '/view/{user}/groupe/{groupe}'
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:User:viewForGroupe' }
    methods: 'GET'
    requirements:
        user: '\d+'
        groupe: '\d+'

hopitalnumerique_communautepratique_user_desinscritgroupe:
    path: '/groupe/{groupe}/desinscrit/{user}'
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:User:desinscritGroupe' }
    methods: 'POST'
    requirements:
        groupe: '\d+'
        user: '\d+'

hopitalnumerique_communautepratique_user_activegroupe:
    path: '/groupe/{groupe}/activegroupe/{user}'
    defaults: { _controller: 'HopitalNumeriqueCommunautePratiqueBundle:User:activeGroupe' }
    methods: 'POST'
    requirements:
        groupe: '\d+'
        user: '\d+'
