hopitalnumerique_communautepratique_user_list:
    pattern: /list/{page}
    defaults: { _controller: "HopitalNumeriqueCommunautePratiqueBundle:User:list", page:1 }
    methods: GET|POST
    requirements:
        page: \d+
