<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20140417093944 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql", "Migration can only be executed safely on 'mysql'.");
        
        $this->addSql("CREATE TABLE core_menu_item (itm_id INT AUTO_INCREMENT NOT NULL COMMENT 'ID du lien', itm_parent INT DEFAULT NULL COMMENT 'ID du lien', mnu_menu INT DEFAULT NULL COMMENT 'ID du menu', itm_name VARCHAR(255) NOT NULL COMMENT 'Nom du lien', itm_route VARCHAR(255) DEFAULT NULL COMMENT 'Route associée', itm_route_parameters VARCHAR(255) DEFAULT NULL COMMENT 'Paramètres de la route', itm_route_absolute TINYINT(1) DEFAULT NULL COMMENT 'Le lien est-il absolu ?', itm_uri VARCHAR(255) DEFAULT NULL COMMENT 'Lien extérieur', itm_icon VARCHAR(32) DEFAULT NULL COMMENT 'Icône du lien', itm_display TINYINT(1) DEFAULT NULL COMMENT 'Afficher le lien ?', itm_display_children TINYINT(1) NOT NULL COMMENT 'Afficher les enfants ?', itm_role VARCHAR(255) NOT NULL COMMENT 'Rôle pouvant visualiser le lien', itm_order INT NOT NULL COMMENT 'Ordre du lien', INDEX IDX_9834E574710838CD (itm_parent), INDEX IDX_9834E57448A87C5C (mnu_menu), PRIMARY KEY(itm_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE core_menu (mnu_id INT AUTO_INCREMENT NOT NULL COMMENT 'ID du menu', mnu_name VARCHAR(100) NOT NULL COMMENT 'Nom du menu', mnu_alias VARCHAR(255) NOT NULL COMMENT 'Alias du menu', mnu_cssClass VARCHAR(32) DEFAULT NULL COMMENT 'Classe CSS associée', mnu_cssId VARCHAR(32) DEFAULT NULL COMMENT 'ID CSS associé', mnu_lock TINYINT(1) NOT NULL COMMENT 'Verrouillage du menu ?', PRIMARY KEY(mnu_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_user_refus_candidature (urc_id INT AUTO_INCREMENT NOT NULL, usr_id INT DEFAULT NULL COMMENT 'ID de l utilisateur', usr_id_orgine_refus INT DEFAULT NULL COMMENT 'ID de l utilisateur', qst_id INT DEFAULT NULL COMMENT 'ID du questionnaire', urc_motif_refus LONGTEXT NOT NULL COMMENT 'Motif de refus de la candidature', urc_date_refus DATETIME NOT NULL COMMENT 'Date de refus de la candidature', INDEX IDX_A36968C1C69D3FB (usr_id), INDEX IDX_A36968C140EE18B4 (usr_id_orgine_refus), INDEX IDX_A36968C1B293CE31 (qst_id), PRIMARY KEY(urc_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE core_user_contractualisation (ctn_id INT AUTO_INCREMENT NOT NULL COMMENT 'ID de la contractualisation', ref_type_document INT DEFAULT NULL COMMENT 'ID de la référence', usr_id INT DEFAULT NULL COMMENT 'ID de l utilisateur', ctn_path VARCHAR(255) DEFAULT NULL COMMENT 'Nom du document pdf stocké', ctn_nom_document VARCHAR(255) NOT NULL COMMENT 'Nom du document pdf utilisateur', ctn_archiver TINYINT(1) DEFAULT NULL COMMENT 'Document archivé ?', ctn_date_renouvellement DATETIME DEFAULT NULL COMMENT 'Date de renouvellement', INDEX IDX_915456F331C6FAEA (ref_type_document), INDEX IDX_915456F3C69D3FB (usr_id), PRIMARY KEY(ctn_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE core_user (usr_id INT AUTO_INCREMENT NOT NULL COMMENT 'ID de l utilisateur', ref_region INT DEFAULT NULL COMMENT 'ID de la référence', ref_departement INT DEFAULT NULL COMMENT 'ID de la référence', ref_etat INT DEFAULT NULL COMMENT 'ID de la référence', ref_titre INT DEFAULT NULL COMMENT 'ID de la référence', ref_civilite INT DEFAULT NULL COMMENT 'ID de la référence', ref_statut_etablissement_sante INT DEFAULT NULL COMMENT 'ID de la référence', eta_etablissement_rattachement_sante INT DEFAULT NULL COMMENT 'ID de l établissement', ref_profil_etablissement_sante INT DEFAULT NULL COMMENT 'ID de la référence', ref_raison_inscription_sante INT DEFAULT NULL COMMENT 'ID de la référence', ref_raison_inscription_structure INT DEFAULT NULL COMMENT 'ID de la référence', roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', usr_date_inscription DATETIME NOT NULL COMMENT 'Date inscription', usr_nom VARCHAR(50) NOT NULL COMMENT 'Nom de l utilisateur', usr_prenom VARCHAR(50) NOT NULL COMMENT 'Prénom de l utilisateur', usr_telephone_direct VARCHAR(14) DEFAULT NULL COMMENT 'Téléphone de l utilisateur', usr_telephone_portable VARCHAR(14) DEFAULT NULL COMMENT 'Téléphone portable de l utilisateur', usr_contact_autre LONGTEXT DEFAULT NULL COMMENT 'Autre moyen de contacter l utilsateur', usr_autre_rattachement_sante VARCHAR(255) DEFAULT NULL COMMENT 'Autre structure de rattachement santé de l utilisateur', usr_fonction_dans_etablissement VARCHAR(255) DEFAULT NULL COMMENT 'Fonction dans l etablissement de santé de l utilisateur', usr_nom_structure VARCHAR(255) DEFAULT NULL COMMENT 'Nom de la structure de l utilisateur', usr_fonction_strucutre VARCHAR(255) DEFAULT NULL COMMENT 'Fonction au sein de la structure', usr_lock TINYINT(1) NOT NULL COMMENT 'L utilisateur est-il verrouillé ?', usr_archiver TINYINT(1) NOT NULL COMMENT 'L utilisateur est-il archivé ?', usr_username VARCHAR(50) NOT NULL COMMENT 'Nom utilisateur pour la connexion', usr_username_canonical VARCHAR(50) NOT NULL COMMENT 'Pseudonyme canonique', usr_email VARCHAR(50) NOT NULL COMMENT 'Adresse électronique', usr_email_canonical VARCHAR(50) NOT NULL COMMENT 'Adresse électronique canonique', usr_enabled TINYINT(1) NOT NULL COMMENT 'L utilisateur est-il activé ?', usr_salt VARCHAR(100) DEFAULT NULL COMMENT 'Grain de sel de chiffrement du mot de passe', usr_password VARCHAR(100) NOT NULL COMMENT 'Mot de passe', usr_last_login DATETIME DEFAULT NULL COMMENT 'Date de la dernière connexion', usr_confirmation_token VARCHAR(50) DEFAULT NULL COMMENT 'Jeton de confirmation du compte', usr_password_requested_at DATETIME DEFAULT NULL COMMENT 'Date de demande du nouveau mot de passe', usr_locked TINYINT(1) DEFAULT NULL COMMENT 'Verrouillage de l utilisateur ?', usr_expired TINYINT(1) DEFAULT NULL COMMENT 'L utilisateur est-il activé ?', usr_expires_at DATETIME DEFAULT NULL COMMENT 'Date d expiration de l utilisateur', usr_credentials_expired TINYINT(1) DEFAULT NULL COMMENT 'Expiration du mot de passe ?', usr_credentials_expire_at DATETIME DEFAULT NULL COMMENT 'Date d expiration du mot de passe', UNIQUE INDEX UNIQ_BF76157CB66BC5FE (usr_username_canonical), UNIQUE INDEX UNIQ_BF76157C3E93317B (usr_email_canonical), INDEX IDX_BF76157C7A7B998F (ref_region), INDEX IDX_BF76157C3B7FA3EF (ref_departement), INDEX IDX_BF76157C42B9B6E5 (ref_etat), INDEX IDX_BF76157C8CBC2276 (ref_titre), INDEX IDX_BF76157CAA5BDD51 (ref_civilite), INDEX IDX_BF76157C9657DD40 (ref_statut_etablissement_sante), INDEX IDX_BF76157CEA6C7CAC (eta_etablissement_rattachement_sante), INDEX IDX_BF76157CA30C838E (ref_profil_etablissement_sante), INDEX IDX_BF76157C6049BC8D (ref_raison_inscription_sante), INDEX IDX_BF76157CD8B5DFB9 (ref_raison_inscription_structure), PRIMARY KEY(usr_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE core_user_domaines (usr_id INT NOT NULL COMMENT 'ID de l utilisateur', ref_id INT NOT NULL COMMENT 'ID de la référence', INDEX IDX_E18CE0C5C69D3FB (usr_id), INDEX IDX_E18CE0C521B741A9 (ref_id), PRIMARY KEY(usr_id, ref_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE core_role (ro_id INT AUTO_INCREMENT NOT NULL COMMENT 'ID du groupe', ref_etat INT DEFAULT NULL COMMENT 'ID de la référence', ro_name VARCHAR(255) NOT NULL COMMENT 'Nom du groupe', ro_role VARCHAR(70) NOT NULL COMMENT 'Code du groupe', ro_initial TINYINT(1) NOT NULL COMMENT 'Le groupe est-il initial ?', UNIQUE INDEX UNIQ_658C495FD357AE9F (ro_role), INDEX IDX_658C495F42B9B6E5 (ref_etat), PRIMARY KEY(ro_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE core_ressource (res_id INT AUTO_INCREMENT NOT NULL COMMENT 'ID de la ressource', res_nom VARCHAR(255) NOT NULL COMMENT 'Nom de la ressource', res_pattern VARCHAR(255) NOT NULL COMMENT 'Patron de regex de l URL', res_order INT NOT NULL COMMENT 'Ordre de la ressource', res_type INT DEFAULT 1 NOT NULL COMMENT 'Type de la ressource : 1 multiple, 2 simple', PRIMARY KEY(res_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE core_acl (ro_id INT NOT NULL COMMENT 'ID du groupe', res_id INT NOT NULL COMMENT 'ID de la ressource', acl_read TINYINT(1) NOT NULL COMMENT 'Autoriser la lecture', acl_write TINYINT(1) NOT NULL COMMENT 'Autoriser l écriture', INDEX IDX_812FBB3EBF75BFC5 (ro_id), INDEX IDX_812FBB3E4670E604 (res_id), PRIMARY KEY(ro_id, res_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE core_mail (mail_id INT AUTO_INCREMENT NOT NULL COMMENT 'ID du mail', mail_objet VARCHAR(255) NOT NULL COMMENT 'Objet du mail', mail_description VARCHAR(255) NOT NULL COMMENT 'Description du mail', mail_expediteur_mail VARCHAR(255) NOT NULL COMMENT 'Adresse mail de l expéditeur', mail_expediteur_name VARCHAR(255) NOT NULL COMMENT 'Nom de l expéditeur', mail_body LONGTEXT NOT NULL COMMENT 'Contenu du mail', mail_params LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)', PRIMARY KEY(mail_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_reference (ref_id INT AUTO_INCREMENT NOT NULL COMMENT 'ID de la référence', ref_etat INT DEFAULT NULL COMMENT 'ID de la référence', parent_id INT DEFAULT NULL COMMENT 'ID de la référence', ref_libelle VARCHAR(255) NOT NULL COMMENT 'Libellé de la référence', ref_code VARCHAR(255) NOT NULL COMMENT 'Code de la référence', ref_dictionnaire TINYINT(1) NOT NULL COMMENT 'Référence présente dans dictionnaire de référencement ?', ref_recherche TINYINT(1) NOT NULL COMMENT 'Référence présente dans le moteur de recherche ?', ref_lock TINYINT(1) NOT NULL COMMENT 'Référence verrouillée ?', ref_order INT NOT NULL COMMENT 'Ordre de la référence', INDEX IDX_579CE1DF42B9B6E5 (ref_etat), INDEX IDX_579CE1DF727ACA70 (parent_id), PRIMARY KEY(ref_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_etablissement (eta_id INT AUTO_INCREMENT NOT NULL COMMENT 'ID de l établissement', ref_type_organisme INT DEFAULT NULL COMMENT 'ID de la référence', ref_region INT DEFAULT NULL COMMENT 'ID de la référence', ref_departement INT DEFAULT NULL COMMENT 'ID de la référence', eta_nom VARCHAR(255) NOT NULL COMMENT 'Nom de l établissement', eta_finess VARCHAR(9) NOT NULL COMMENT 'Finesse géographique de l établissement', eta_adresse VARCHAR(512) NOT NULL COMMENT 'Adresse de l établissement', eta_ville VARCHAR(255) NOT NULL COMMENT 'Ville de l établissement', eta_codepostal VARCHAR(5) NOT NULL COMMENT 'Code postal de l établissement', INDEX IDX_57B264CE245F352C (ref_type_organisme), INDEX IDX_57B264CE7A7B998F (ref_region), INDEX IDX_57B264CE3B7FA3EF (ref_departement), PRIMARY KEY(eta_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_objet (obj_id INT AUTO_INCREMENT NOT NULL COMMENT 'ID de l objet', obj_locked_by INT DEFAULT NULL COMMENT 'ID de l utilisateur', ref_statut INT DEFAULT NULL COMMENT 'ID de la référence', obj_titre VARCHAR(255) NOT NULL COMMENT 'Titre de l objet', obj_alias VARCHAR(255) NOT NULL COMMENT 'Alias de l objet', obj_synthese LONGTEXT DEFAULT NULL COMMENT 'Synthèse de l objet', obj_resume LONGTEXT NOT NULL COMMENT 'Résumé de l objet', obj_path VARCHAR(255) DEFAULT NULL COMMENT 'Nom du fichier lié à l objet', obj_path2 VARCHAR(255) DEFAULT NULL COMMENT 'Nom du fichier 2 lié à l objet', obj_commentaires TINYINT(1) NOT NULL COMMENT 'Commentaires autorisés sur l objet ?', obj_notes TINYINT(1) NOT NULL COMMENT 'Notes autorisées sur l objet ?', obj_date_creation DATETIME NOT NULL COMMENT 'Date de création de l objet', obj_date_debut_publication DATETIME DEFAULT NULL COMMENT 'Date de début de la publication de l objet', obj_date_fin_publication DATETIME DEFAULT NULL COMMENT 'Date de fin de la publication de l objet', obj_date_modification DATETIME DEFAULT NULL COMMENT 'Date de modification de l objet', obj_lock TINYINT(1) NOT NULL COMMENT 'Verrouillage de l objet ?', obj_isInfraDoc TINYINT(1) NOT NULL COMMENT 'L objet est de type infradocumentaire ?', obj_isArticle TINYINT(1) NOT NULL COMMENT 'L objet est un article ?', obj_vignette VARCHAR(255) DEFAULT NULL COMMENT 'Vignette de l objet', UNIQUE INDEX UNIQ_C09252D824DC81D (obj_alias), INDEX IDX_C09252D88F6FF018 (obj_locked_by), INDEX IDX_C09252D8907D9846 (ref_statut), PRIMARY KEY(obj_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_objet_role (obj_id INT NOT NULL COMMENT 'ID de l objet', ro_id INT NOT NULL COMMENT 'ID du groupe', INDEX IDX_E7A0B21066093344 (obj_id), INDEX IDX_E7A0B210BF75BFC5 (ro_id), PRIMARY KEY(obj_id, ro_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_objet_type (obj_id INT NOT NULL COMMENT 'ID de l objet', ref_id INT NOT NULL COMMENT 'ID de la référence', INDEX IDX_3C176F5366093344 (obj_id), INDEX IDX_3C176F5321B741A9 (ref_id), PRIMARY KEY(obj_id, ref_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_objet_ambassadeur (obj_id INT NOT NULL COMMENT 'ID de l objet', usr_id INT NOT NULL COMMENT 'ID de l utilisateur', INDEX IDX_B29AF5E66093344 (obj_id), INDEX IDX_B29AF5EC69D3FB (usr_id), PRIMARY KEY(obj_id, usr_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_objet_contenu (con_id INT AUTO_INCREMENT NOT NULL COMMENT 'ID du contenu', parent_id INT DEFAULT NULL COMMENT 'ID du contenu', obj_id INT DEFAULT NULL COMMENT 'ID de l objet', con_titre VARCHAR(255) NOT NULL COMMENT 'Titre du contenu', con_alias VARCHAR(255) NOT NULL COMMENT 'Alias du contenu', con_order INT DEFAULT NULL COMMENT 'Ordre du contenu', con_contenu LONGTEXT NOT NULL COMMENT 'Texte du contenu', con_date_creation DATETIME NOT NULL COMMENT 'Date de création du contenu', con_date_modification DATETIME DEFAULT NULL COMMENT 'Date de modification du contenu', INDEX IDX_25832BE6727ACA70 (parent_id), INDEX IDX_25832BE666093344 (obj_id), PRIMARY KEY(con_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_objet_contenu_reference (refc_id INT AUTO_INCREMENT NOT NULL COMMENT 'ID de la référence du contenu', ref_id INT DEFAULT NULL COMMENT 'ID de la référence', con_id INT DEFAULT NULL COMMENT 'ID du contenu', refc_primary TINYINT(1) NOT NULL COMMENT 'La référence est de type primaire ?', INDEX IDX_99561D4421B741A9 (ref_id), INDEX IDX_99561D446639A0D9 (con_id), PRIMARY KEY(refc_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_objet_consultation (cln_id INT AUTO_INCREMENT NOT NULL COMMENT 'ID de la consultation', usr_id INT DEFAULT NULL COMMENT 'ID de l utilisateur', obj_id INT DEFAULT NULL COMMENT 'ID de l objet', con_id INT DEFAULT NULL COMMENT 'ID du contenu', cln_date_last_consulted DATETIME NOT NULL COMMENT 'Date de dernière consultation de l objet par l user', INDEX IDX_167AA4A3C69D3FB (usr_id), INDEX IDX_167AA4A366093344 (obj_id), INDEX IDX_167AA4A36639A0D9 (con_id), PRIMARY KEY(cln_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_objet_reference (refo_id INT AUTO_INCREMENT NOT NULL COMMENT 'ID de la référence de l objet', ref_id INT DEFAULT NULL COMMENT 'ID de la référence', obj_id INT DEFAULT NULL COMMENT 'ID de l objet', refo_primary TINYINT(1) NOT NULL COMMENT 'La référence est de type primaire ?', INDEX IDX_52E5624421B741A9 (ref_id), INDEX IDX_52E5624466093344 (obj_id), PRIMARY KEY(refo_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_questionnaire_question (que_id INT AUTO_INCREMENT NOT NULL COMMENT 'ID de la question', qst_id INT DEFAULT NULL COMMENT 'ID du questionnaire', typ_question INT DEFAULT NULL COMMENT 'ID du type de question', que_alias VARCHAR(60) NOT NULL COMMENT 'Alias de la question', que_libelle VARCHAR(255) NOT NULL COMMENT 'Libellé de la question', que_reference_param_tri VARCHAR(50) DEFAULT NULL COMMENT 'Code de la référence si le type est une entitée', que_obligatoire TINYINT(1) NOT NULL COMMENT 'La question est-elle obligatoire ?', que_verifJS VARCHAR(255) DEFAULT NULL COMMENT 'Vérification JavaScript', que_ordre INT NOT NULL COMMENT 'Ordre de la question', INDEX IDX_86A097EBB293CE31 (qst_id), INDEX IDX_86A097EB51818D8A (typ_question), PRIMARY KEY(que_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_questionnaire_type_question (typ_id INT AUTO_INCREMENT NOT NULL COMMENT 'ID du type de question', libelle VARCHAR(255) NOT NULL COMMENT 'Libellé du type de question', nom VARCHAR(255) NOT NULL COMMENT 'Nom du type de question', PRIMARY KEY(typ_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_questionnaire_questionnaire (qst_id INT AUTO_INCREMENT NOT NULL COMMENT 'ID du questionnaire', qst_nom VARCHAR(255) NOT NULL COMMENT 'Nom du questionnaire', qst_lock TINYINT(1) NOT NULL COMMENT 'Verrouillage du questionnaire ?', PRIMARY KEY(qst_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_questionnaire_reponse (rep_id INT AUTO_INCREMENT NOT NULL COMMENT 'ID de la réponse', usr_id INT DEFAULT NULL COMMENT 'ID de l utilisateur', que_id INT DEFAULT NULL COMMENT 'ID de la question', ref_reference INT DEFAULT NULL COMMENT 'ID de la référence', rep_reponse LONGTEXT NOT NULL COMMENT 'Contenu de la réponse', param_id INT DEFAULT NULL COMMENT 'Éventuelle clef étrangère', INDEX IDX_BD979228C69D3FB (usr_id), INDEX IDX_BD979228D5760B6B (que_id), INDEX IDX_BD979228DDF94856 (ref_reference), PRIMARY KEY(rep_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_intervention_regroupement_type (intervregtyp_id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, intervregtyp_libelle VARCHAR(32) NOT NULL, PRIMARY KEY(intervregtyp_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_intervention_initiateur (intervinit_id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, intervinit_type VARCHAR(32) NOT NULL, PRIMARY KEY(intervinit_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_intervention_regroupement (intervreg_id INT AUTO_INCREMENT NOT NULL, intervregtyp_id SMALLINT UNSIGNED DEFAULT NULL, interv_principale_id INT UNSIGNED DEFAULT NULL, interv_regroupee_id INT UNSIGNED DEFAULT NULL, INDEX IDX_39B795AD7DDE15 (intervregtyp_id), INDEX IDX_39B795B56A61A6 (interv_principale_id), INDEX IDX_39B7952B07AECF (interv_regroupee_id), PRIMARY KEY(intervreg_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_intervention_demande (interv_id INT UNSIGNED AUTO_INCREMENT NOT NULL, referent_id INT DEFAULT NULL COMMENT 'ID de l utilisateur', ambassadeur_id INT DEFAULT NULL COMMENT 'ID de l utilisateur', cmsi_id INT DEFAULT NULL COMMENT 'ID de l utilisateur', directeur_id INT DEFAULT NULL COMMENT 'ID de l utilisateur', intervinit_id SMALLINT UNSIGNED DEFAULT NULL, ref_intervention_type_id INT NOT NULL COMMENT 'ID de la référence', ref_intervention_etat_id INT DEFAULT NULL COMMENT 'ID de la référence', ref_evaluation_etat_id INT DEFAULT NULL COMMENT 'ID de la référence', ref_remboursement_etat_id INT DEFAULT NULL COMMENT 'ID de la référence', interv_date_creation DATETIME NOT NULL, interv_cmsi_date_choix DATETIME DEFAULT NULL, interv_ambassadeur_date_choix DATETIME DEFAULT NULL, interv_cmsi_date_derniere_relance DATETIME DEFAULT NULL, interv_ambassadeur_date_derniere_relance DATETIME DEFAULT NULL, interv_autres_etablissements TEXT, interv_description TEXT, interv_difficulte_description TEXT, interv_champ_libre TEXT, interv_rdv_informations TEXT, interv_cmsi_commentaire TEXT, interv_refus_message TEXT, INDEX IDX_6DEA573035E47E35 (referent_id), INDEX IDX_6DEA57305A509AEC (ambassadeur_id), INDEX IDX_6DEA5730F204AB36 (cmsi_id), INDEX IDX_6DEA5730E82E7EE8 (directeur_id), INDEX IDX_6DEA57304F81EDEA (intervinit_id), INDEX IDX_6DEA57303DC7BFE (ref_intervention_type_id), INDEX IDX_6DEA5730CBCE7192 (ref_intervention_etat_id), INDEX IDX_6DEA57307CF11135 (ref_evaluation_etat_id), INDEX IDX_6DEA5730EB161607 (ref_remboursement_etat_id), INDEX fk_hn_intervention_demande_date_creation (interv_date_creation), PRIMARY KEY(interv_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_intervention_ambassadeur_historique (interv_id INT UNSIGNED NOT NULL, ambassadeur_ancien_id INT NOT NULL COMMENT 'ID de l utilisateur', INDEX IDX_1D720677C7F0ABC4 (interv_id), INDEX IDX_1D720677D5A4D420 (ambassadeur_ancien_id), PRIMARY KEY(interv_id, ambassadeur_ancien_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_intervention_etablissement_rattache (interv_id INT UNSIGNED NOT NULL, eta_id INT NOT NULL COMMENT 'ID de l établissement', INDEX IDX_DA1B4928C7F0ABC4 (interv_id), INDEX IDX_DA1B4928FF33F501 (eta_id), PRIMARY KEY(interv_id, eta_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_intervention_objet (interv_id INT UNSIGNED NOT NULL, obj_id INT NOT NULL COMMENT 'ID de l objet', INDEX IDX_7845C1B3C7F0ABC4 (interv_id), INDEX IDX_7845C1B366093344 (obj_id), PRIMARY KEY(interv_id, obj_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_requete (req_id INT AUTO_INCREMENT NOT NULL, usr_id INT DEFAULT NULL COMMENT 'ID de l utilisateur', req_nom VARCHAR(128) NOT NULL COMMENT 'Nom de la requete', req_isDefault TINYINT(1) NOT NULL COMMENT 'La requete est-elle celle par default ?', req_isNew TINYINT(1) NOT NULL COMMENT 'Un element de la requete est taggue comme nouveau ?', req_isUpdated TINYINT(1) NOT NULL COMMENT 'Un element de la requete est taggue comme mis a jour ?', req_isUserNotified TINYINT(1) NOT NULL COMMENT 'L utilisateur a demande d etre notifie sur cette requete', obj_date_debut DATETIME DEFAULT NULL COMMENT 'Date de debut de la notification', obj_date_fin DATETIME DEFAULT NULL COMMENT 'Date de fin de la notification', req_refs LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)', INDEX IDX_BA17717AC69D3FB (usr_id), PRIMARY KEY(req_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE hn_contact (contact_id INT AUTO_INCREMENT NOT NULL, ref_civilite INT DEFAULT NULL COMMENT 'ID de la référence', ref_region INT DEFAULT NULL COMMENT 'ID de la référence', ref_departement INT DEFAULT NULL COMMENT 'ID de la référence', ref_statut_etablissement_sante INT DEFAULT NULL COMMENT 'ID de la référence', eta_etablissement_rattachement_sante INT DEFAULT NULL COMMENT 'ID de l établissement', contact_fonction_strucutre VARCHAR(255) DEFAULT NULL COMMENT 'Fonction au sein de la structure', usr_autre_rattachement_sante VARCHAR(255) DEFAULT NULL COMMENT 'Autre structure de rattachement santé de l utilisateur', contact_prenom VARCHAR(50) NOT NULL COMMENT 'Prénom de la personne qui a contacté', contact_nom VARCHAR(50) NOT NULL, contact_mail VARCHAR(255) NOT NULL, contact_ville VARCHAR(50) DEFAULT NULL, contact_codepostal VARCHAR(5) DEFAULT NULL, contact_telephone VARCHAR(14) DEFAULT NULL COMMENT 'Téléphone de l utilisateur', contact_message LONGTEXT NOT NULL, INDEX IDX_E813AEE8AA5BDD51 (ref_civilite), INDEX IDX_E813AEE87A7B998F (ref_region), INDEX IDX_E813AEE83B7FA3EF (ref_departement), INDEX IDX_E813AEE89657DD40 (ref_statut_etablissement_sante), INDEX IDX_E813AEE8EA6C7CAC (eta_etablissement_rattachement_sante), PRIMARY KEY(contact_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE core_faq (faq_id INT AUTO_INCREMENT NOT NULL COMMENT 'ID de la question/réponse FAQ', cat_id INT DEFAULT NULL COMMENT 'ID de la catégorie de FAQ', faq_question LONGTEXT NOT NULL COMMENT 'Intitulé de la question', faq_reponse LONGTEXT NOT NULL COMMENT 'Réponse à la question', faq_order INT NOT NULL COMMENT 'Ordre de l element', INDEX IDX_D550A3E0E6ADA943 (cat_id), PRIMARY KEY(faq_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE core_faq_categorie (cat_id INT AUTO_INCREMENT NOT NULL COMMENT 'ID de la catégorie de FAQ', cat_name VARCHAR(255) NOT NULL COMMENT 'Nom de la catégorie', cat_icon VARCHAR(255) DEFAULT NULL COMMENT 'Icone de la catégorie', PRIMARY KEY(cat_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE core_menu_item ADD CONSTRAINT FK_9834E574710838CD FOREIGN KEY (itm_parent) REFERENCES core_menu_item (itm_id)");
        $this->addSql("ALTER TABLE core_menu_item ADD CONSTRAINT FK_9834E57448A87C5C FOREIGN KEY (mnu_menu) REFERENCES core_menu (mnu_id)");
        $this->addSql("ALTER TABLE hn_user_refus_candidature ADD CONSTRAINT FK_A36968C1C69D3FB FOREIGN KEY (usr_id) REFERENCES core_user (usr_id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE hn_user_refus_candidature ADD CONSTRAINT FK_A36968C140EE18B4 FOREIGN KEY (usr_id_orgine_refus) REFERENCES core_user (usr_id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE hn_user_refus_candidature ADD CONSTRAINT FK_A36968C1B293CE31 FOREIGN KEY (qst_id) REFERENCES hn_questionnaire_questionnaire (qst_id)");
        $this->addSql("ALTER TABLE core_user_contractualisation ADD CONSTRAINT FK_915456F331C6FAEA FOREIGN KEY (ref_type_document) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE core_user_contractualisation ADD CONSTRAINT FK_915456F3C69D3FB FOREIGN KEY (usr_id) REFERENCES core_user (usr_id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE core_user ADD CONSTRAINT FK_BF76157C7A7B998F FOREIGN KEY (ref_region) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE core_user ADD CONSTRAINT FK_BF76157C3B7FA3EF FOREIGN KEY (ref_departement) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE core_user ADD CONSTRAINT FK_BF76157C42B9B6E5 FOREIGN KEY (ref_etat) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE core_user ADD CONSTRAINT FK_BF76157C8CBC2276 FOREIGN KEY (ref_titre) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE core_user ADD CONSTRAINT FK_BF76157CAA5BDD51 FOREIGN KEY (ref_civilite) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE core_user ADD CONSTRAINT FK_BF76157C9657DD40 FOREIGN KEY (ref_statut_etablissement_sante) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE core_user ADD CONSTRAINT FK_BF76157CEA6C7CAC FOREIGN KEY (eta_etablissement_rattachement_sante) REFERENCES hn_etablissement (eta_id)");
        $this->addSql("ALTER TABLE core_user ADD CONSTRAINT FK_BF76157CA30C838E FOREIGN KEY (ref_profil_etablissement_sante) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE core_user ADD CONSTRAINT FK_BF76157C6049BC8D FOREIGN KEY (ref_raison_inscription_sante) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE core_user ADD CONSTRAINT FK_BF76157CD8B5DFB9 FOREIGN KEY (ref_raison_inscription_structure) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE core_user_domaines ADD CONSTRAINT FK_E18CE0C5C69D3FB FOREIGN KEY (usr_id) REFERENCES core_user (usr_id)");
        $this->addSql("ALTER TABLE core_user_domaines ADD CONSTRAINT FK_E18CE0C521B741A9 FOREIGN KEY (ref_id) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE core_role ADD CONSTRAINT FK_658C495F42B9B6E5 FOREIGN KEY (ref_etat) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE core_acl ADD CONSTRAINT FK_812FBB3EBF75BFC5 FOREIGN KEY (ro_id) REFERENCES core_role (ro_id)");
        $this->addSql("ALTER TABLE core_acl ADD CONSTRAINT FK_812FBB3E4670E604 FOREIGN KEY (res_id) REFERENCES core_ressource (res_id)");
        $this->addSql("ALTER TABLE hn_reference ADD CONSTRAINT FK_579CE1DF42B9B6E5 FOREIGN KEY (ref_etat) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE hn_reference ADD CONSTRAINT FK_579CE1DF727ACA70 FOREIGN KEY (parent_id) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE hn_etablissement ADD CONSTRAINT FK_57B264CE245F352C FOREIGN KEY (ref_type_organisme) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE hn_etablissement ADD CONSTRAINT FK_57B264CE7A7B998F FOREIGN KEY (ref_region) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE hn_etablissement ADD CONSTRAINT FK_57B264CE3B7FA3EF FOREIGN KEY (ref_departement) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE hn_objet ADD CONSTRAINT FK_C09252D88F6FF018 FOREIGN KEY (obj_locked_by) REFERENCES core_user (usr_id)");
        $this->addSql("ALTER TABLE hn_objet ADD CONSTRAINT FK_C09252D8907D9846 FOREIGN KEY (ref_statut) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE hn_objet_role ADD CONSTRAINT FK_E7A0B21066093344 FOREIGN KEY (obj_id) REFERENCES hn_objet (obj_id)");
        $this->addSql("ALTER TABLE hn_objet_role ADD CONSTRAINT FK_E7A0B210BF75BFC5 FOREIGN KEY (ro_id) REFERENCES core_role (ro_id)");
        $this->addSql("ALTER TABLE hn_objet_type ADD CONSTRAINT FK_3C176F5366093344 FOREIGN KEY (obj_id) REFERENCES hn_objet (obj_id)");
        $this->addSql("ALTER TABLE hn_objet_type ADD CONSTRAINT FK_3C176F5321B741A9 FOREIGN KEY (ref_id) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE hn_objet_ambassadeur ADD CONSTRAINT FK_B29AF5E66093344 FOREIGN KEY (obj_id) REFERENCES hn_objet (obj_id)");
        $this->addSql("ALTER TABLE hn_objet_ambassadeur ADD CONSTRAINT FK_B29AF5EC69D3FB FOREIGN KEY (usr_id) REFERENCES core_user (usr_id)");
        $this->addSql("ALTER TABLE hn_objet_contenu ADD CONSTRAINT FK_25832BE6727ACA70 FOREIGN KEY (parent_id) REFERENCES hn_objet_contenu (con_id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE hn_objet_contenu ADD CONSTRAINT FK_25832BE666093344 FOREIGN KEY (obj_id) REFERENCES hn_objet (obj_id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE hn_objet_contenu_reference ADD CONSTRAINT FK_99561D4421B741A9 FOREIGN KEY (ref_id) REFERENCES hn_reference (ref_id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE hn_objet_contenu_reference ADD CONSTRAINT FK_99561D446639A0D9 FOREIGN KEY (con_id) REFERENCES hn_objet_contenu (con_id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE hn_objet_consultation ADD CONSTRAINT FK_167AA4A3C69D3FB FOREIGN KEY (usr_id) REFERENCES core_user (usr_id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE hn_objet_consultation ADD CONSTRAINT FK_167AA4A366093344 FOREIGN KEY (obj_id) REFERENCES hn_objet (obj_id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE hn_objet_consultation ADD CONSTRAINT FK_167AA4A36639A0D9 FOREIGN KEY (con_id) REFERENCES hn_objet_contenu (con_id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE hn_objet_reference ADD CONSTRAINT FK_52E5624421B741A9 FOREIGN KEY (ref_id) REFERENCES hn_reference (ref_id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE hn_objet_reference ADD CONSTRAINT FK_52E5624466093344 FOREIGN KEY (obj_id) REFERENCES hn_objet (obj_id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE hn_questionnaire_question ADD CONSTRAINT FK_86A097EBB293CE31 FOREIGN KEY (qst_id) REFERENCES hn_questionnaire_questionnaire (qst_id)");
        $this->addSql("ALTER TABLE hn_questionnaire_question ADD CONSTRAINT FK_86A097EB51818D8A FOREIGN KEY (typ_question) REFERENCES hn_questionnaire_type_question (typ_id)");
        $this->addSql("ALTER TABLE hn_questionnaire_reponse ADD CONSTRAINT FK_BD979228C69D3FB FOREIGN KEY (usr_id) REFERENCES core_user (usr_id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE hn_questionnaire_reponse ADD CONSTRAINT FK_BD979228D5760B6B FOREIGN KEY (que_id) REFERENCES hn_questionnaire_question (que_id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE hn_questionnaire_reponse ADD CONSTRAINT FK_BD979228DDF94856 FOREIGN KEY (ref_reference) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE hn_intervention_regroupement ADD CONSTRAINT FK_39B795AD7DDE15 FOREIGN KEY (intervregtyp_id) REFERENCES hn_intervention_regroupement_type (intervregtyp_id)");
        $this->addSql("ALTER TABLE hn_intervention_regroupement ADD CONSTRAINT FK_39B795B56A61A6 FOREIGN KEY (interv_principale_id) REFERENCES hn_intervention_demande (interv_id)");
        $this->addSql("ALTER TABLE hn_intervention_regroupement ADD CONSTRAINT FK_39B7952B07AECF FOREIGN KEY (interv_regroupee_id) REFERENCES hn_intervention_demande (interv_id)");
        $this->addSql("ALTER TABLE hn_intervention_demande ADD CONSTRAINT FK_6DEA573035E47E35 FOREIGN KEY (referent_id) REFERENCES core_user (usr_id)");
        $this->addSql("ALTER TABLE hn_intervention_demande ADD CONSTRAINT FK_6DEA57305A509AEC FOREIGN KEY (ambassadeur_id) REFERENCES core_user (usr_id)");
        $this->addSql("ALTER TABLE hn_intervention_demande ADD CONSTRAINT FK_6DEA5730F204AB36 FOREIGN KEY (cmsi_id) REFERENCES core_user (usr_id)");
        $this->addSql("ALTER TABLE hn_intervention_demande ADD CONSTRAINT FK_6DEA5730E82E7EE8 FOREIGN KEY (directeur_id) REFERENCES core_user (usr_id)");
        $this->addSql("ALTER TABLE hn_intervention_demande ADD CONSTRAINT FK_6DEA57304F81EDEA FOREIGN KEY (intervinit_id) REFERENCES hn_intervention_initiateur (intervinit_id)");
        $this->addSql("ALTER TABLE hn_intervention_demande ADD CONSTRAINT FK_6DEA57303DC7BFE FOREIGN KEY (ref_intervention_type_id) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE hn_intervention_demande ADD CONSTRAINT FK_6DEA5730CBCE7192 FOREIGN KEY (ref_intervention_etat_id) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE hn_intervention_demande ADD CONSTRAINT FK_6DEA57307CF11135 FOREIGN KEY (ref_evaluation_etat_id) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE hn_intervention_demande ADD CONSTRAINT FK_6DEA5730EB161607 FOREIGN KEY (ref_remboursement_etat_id) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE hn_intervention_ambassadeur_historique ADD CONSTRAINT FK_1D720677C7F0ABC4 FOREIGN KEY (interv_id) REFERENCES hn_intervention_demande (interv_id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE hn_intervention_ambassadeur_historique ADD CONSTRAINT FK_1D720677D5A4D420 FOREIGN KEY (ambassadeur_ancien_id) REFERENCES core_user (usr_id)");
        $this->addSql("ALTER TABLE hn_intervention_etablissement_rattache ADD CONSTRAINT FK_DA1B4928C7F0ABC4 FOREIGN KEY (interv_id) REFERENCES hn_intervention_demande (interv_id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE hn_intervention_etablissement_rattache ADD CONSTRAINT FK_DA1B4928FF33F501 FOREIGN KEY (eta_id) REFERENCES hn_etablissement (eta_id)");
        $this->addSql("ALTER TABLE hn_intervention_objet ADD CONSTRAINT FK_7845C1B3C7F0ABC4 FOREIGN KEY (interv_id) REFERENCES hn_intervention_demande (interv_id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE hn_intervention_objet ADD CONSTRAINT FK_7845C1B366093344 FOREIGN KEY (obj_id) REFERENCES hn_objet (obj_id)");
        $this->addSql("ALTER TABLE hn_requete ADD CONSTRAINT FK_BA17717AC69D3FB FOREIGN KEY (usr_id) REFERENCES core_user (usr_id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE hn_contact ADD CONSTRAINT FK_E813AEE8AA5BDD51 FOREIGN KEY (ref_civilite) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE hn_contact ADD CONSTRAINT FK_E813AEE87A7B998F FOREIGN KEY (ref_region) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE hn_contact ADD CONSTRAINT FK_E813AEE83B7FA3EF FOREIGN KEY (ref_departement) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE hn_contact ADD CONSTRAINT FK_E813AEE89657DD40 FOREIGN KEY (ref_statut_etablissement_sante) REFERENCES hn_reference (ref_id)");
        $this->addSql("ALTER TABLE hn_contact ADD CONSTRAINT FK_E813AEE8EA6C7CAC FOREIGN KEY (eta_etablissement_rattachement_sante) REFERENCES hn_etablissement (eta_id)");
        $this->addSql("ALTER TABLE core_faq ADD CONSTRAINT FK_D550A3E0E6ADA943 FOREIGN KEY (cat_id) REFERENCES core_faq_categorie (cat_id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql", "Migration can only be executed safely on 'mysql'.");
        
        $this->addSql("ALTER TABLE core_menu_item DROP FOREIGN KEY FK_9834E574710838CD");
        $this->addSql("ALTER TABLE core_menu_item DROP FOREIGN KEY FK_9834E57448A87C5C");
        $this->addSql("ALTER TABLE hn_user_refus_candidature DROP FOREIGN KEY FK_A36968C1C69D3FB");
        $this->addSql("ALTER TABLE hn_user_refus_candidature DROP FOREIGN KEY FK_A36968C140EE18B4");
        $this->addSql("ALTER TABLE core_user_contractualisation DROP FOREIGN KEY FK_915456F3C69D3FB");
        $this->addSql("ALTER TABLE core_user_domaines DROP FOREIGN KEY FK_E18CE0C5C69D3FB");
        $this->addSql("ALTER TABLE hn_objet DROP FOREIGN KEY FK_C09252D88F6FF018");
        $this->addSql("ALTER TABLE hn_objet_ambassadeur DROP FOREIGN KEY FK_B29AF5EC69D3FB");
        $this->addSql("ALTER TABLE hn_objet_consultation DROP FOREIGN KEY FK_167AA4A3C69D3FB");
        $this->addSql("ALTER TABLE hn_questionnaire_reponse DROP FOREIGN KEY FK_BD979228C69D3FB");
        $this->addSql("ALTER TABLE hn_intervention_demande DROP FOREIGN KEY FK_6DEA573035E47E35");
        $this->addSql("ALTER TABLE hn_intervention_demande DROP FOREIGN KEY FK_6DEA57305A509AEC");
        $this->addSql("ALTER TABLE hn_intervention_demande DROP FOREIGN KEY FK_6DEA5730F204AB36");
        $this->addSql("ALTER TABLE hn_intervention_demande DROP FOREIGN KEY FK_6DEA5730E82E7EE8");
        $this->addSql("ALTER TABLE hn_intervention_ambassadeur_historique DROP FOREIGN KEY FK_1D720677D5A4D420");
        $this->addSql("ALTER TABLE hn_requete DROP FOREIGN KEY FK_BA17717AC69D3FB");
        $this->addSql("ALTER TABLE core_acl DROP FOREIGN KEY FK_812FBB3EBF75BFC5");
        $this->addSql("ALTER TABLE hn_objet_role DROP FOREIGN KEY FK_E7A0B210BF75BFC5");
        $this->addSql("ALTER TABLE core_acl DROP FOREIGN KEY FK_812FBB3E4670E604");
        $this->addSql("ALTER TABLE core_user_contractualisation DROP FOREIGN KEY FK_915456F331C6FAEA");
        $this->addSql("ALTER TABLE core_user DROP FOREIGN KEY FK_BF76157C7A7B998F");
        $this->addSql("ALTER TABLE core_user DROP FOREIGN KEY FK_BF76157C3B7FA3EF");
        $this->addSql("ALTER TABLE core_user DROP FOREIGN KEY FK_BF76157C42B9B6E5");
        $this->addSql("ALTER TABLE core_user DROP FOREIGN KEY FK_BF76157C8CBC2276");
        $this->addSql("ALTER TABLE core_user DROP FOREIGN KEY FK_BF76157CAA5BDD51");
        $this->addSql("ALTER TABLE core_user DROP FOREIGN KEY FK_BF76157C9657DD40");
        $this->addSql("ALTER TABLE core_user DROP FOREIGN KEY FK_BF76157CA30C838E");
        $this->addSql("ALTER TABLE core_user DROP FOREIGN KEY FK_BF76157C6049BC8D");
        $this->addSql("ALTER TABLE core_user DROP FOREIGN KEY FK_BF76157CD8B5DFB9");
        $this->addSql("ALTER TABLE core_user_domaines DROP FOREIGN KEY FK_E18CE0C521B741A9");
        $this->addSql("ALTER TABLE core_role DROP FOREIGN KEY FK_658C495F42B9B6E5");
        $this->addSql("ALTER TABLE hn_reference DROP FOREIGN KEY FK_579CE1DF42B9B6E5");
        $this->addSql("ALTER TABLE hn_reference DROP FOREIGN KEY FK_579CE1DF727ACA70");
        $this->addSql("ALTER TABLE hn_etablissement DROP FOREIGN KEY FK_57B264CE245F352C");
        $this->addSql("ALTER TABLE hn_etablissement DROP FOREIGN KEY FK_57B264CE7A7B998F");
        $this->addSql("ALTER TABLE hn_etablissement DROP FOREIGN KEY FK_57B264CE3B7FA3EF");
        $this->addSql("ALTER TABLE hn_objet DROP FOREIGN KEY FK_C09252D8907D9846");
        $this->addSql("ALTER TABLE hn_objet_type DROP FOREIGN KEY FK_3C176F5321B741A9");
        $this->addSql("ALTER TABLE hn_objet_contenu_reference DROP FOREIGN KEY FK_99561D4421B741A9");
        $this->addSql("ALTER TABLE hn_objet_reference DROP FOREIGN KEY FK_52E5624421B741A9");
        $this->addSql("ALTER TABLE hn_questionnaire_reponse DROP FOREIGN KEY FK_BD979228DDF94856");
        $this->addSql("ALTER TABLE hn_intervention_demande DROP FOREIGN KEY FK_6DEA57303DC7BFE");
        $this->addSql("ALTER TABLE hn_intervention_demande DROP FOREIGN KEY FK_6DEA5730CBCE7192");
        $this->addSql("ALTER TABLE hn_intervention_demande DROP FOREIGN KEY FK_6DEA57307CF11135");
        $this->addSql("ALTER TABLE hn_intervention_demande DROP FOREIGN KEY FK_6DEA5730EB161607");
        $this->addSql("ALTER TABLE hn_contact DROP FOREIGN KEY FK_E813AEE8AA5BDD51");
        $this->addSql("ALTER TABLE hn_contact DROP FOREIGN KEY FK_E813AEE87A7B998F");
        $this->addSql("ALTER TABLE hn_contact DROP FOREIGN KEY FK_E813AEE83B7FA3EF");
        $this->addSql("ALTER TABLE hn_contact DROP FOREIGN KEY FK_E813AEE89657DD40");
        $this->addSql("ALTER TABLE core_user DROP FOREIGN KEY FK_BF76157CEA6C7CAC");
        $this->addSql("ALTER TABLE hn_intervention_etablissement_rattache DROP FOREIGN KEY FK_DA1B4928FF33F501");
        $this->addSql("ALTER TABLE hn_contact DROP FOREIGN KEY FK_E813AEE8EA6C7CAC");
        $this->addSql("ALTER TABLE hn_objet_role DROP FOREIGN KEY FK_E7A0B21066093344");
        $this->addSql("ALTER TABLE hn_objet_type DROP FOREIGN KEY FK_3C176F5366093344");
        $this->addSql("ALTER TABLE hn_objet_ambassadeur DROP FOREIGN KEY FK_B29AF5E66093344");
        $this->addSql("ALTER TABLE hn_objet_contenu DROP FOREIGN KEY FK_25832BE666093344");
        $this->addSql("ALTER TABLE hn_objet_consultation DROP FOREIGN KEY FK_167AA4A366093344");
        $this->addSql("ALTER TABLE hn_objet_reference DROP FOREIGN KEY FK_52E5624466093344");
        $this->addSql("ALTER TABLE hn_intervention_objet DROP FOREIGN KEY FK_7845C1B366093344");
        $this->addSql("ALTER TABLE hn_objet_contenu DROP FOREIGN KEY FK_25832BE6727ACA70");
        $this->addSql("ALTER TABLE hn_objet_contenu_reference DROP FOREIGN KEY FK_99561D446639A0D9");
        $this->addSql("ALTER TABLE hn_objet_consultation DROP FOREIGN KEY FK_167AA4A36639A0D9");
        $this->addSql("ALTER TABLE hn_questionnaire_reponse DROP FOREIGN KEY FK_BD979228D5760B6B");
        $this->addSql("ALTER TABLE hn_questionnaire_question DROP FOREIGN KEY FK_86A097EB51818D8A");
        $this->addSql("ALTER TABLE hn_user_refus_candidature DROP FOREIGN KEY FK_A36968C1B293CE31");
        $this->addSql("ALTER TABLE hn_questionnaire_question DROP FOREIGN KEY FK_86A097EBB293CE31");
        $this->addSql("ALTER TABLE hn_intervention_regroupement DROP FOREIGN KEY FK_39B795AD7DDE15");
        $this->addSql("ALTER TABLE hn_intervention_demande DROP FOREIGN KEY FK_6DEA57304F81EDEA");
        $this->addSql("ALTER TABLE hn_intervention_regroupement DROP FOREIGN KEY FK_39B795B56A61A6");
        $this->addSql("ALTER TABLE hn_intervention_regroupement DROP FOREIGN KEY FK_39B7952B07AECF");
        $this->addSql("ALTER TABLE hn_intervention_ambassadeur_historique DROP FOREIGN KEY FK_1D720677C7F0ABC4");
        $this->addSql("ALTER TABLE hn_intervention_etablissement_rattache DROP FOREIGN KEY FK_DA1B4928C7F0ABC4");
        $this->addSql("ALTER TABLE hn_intervention_objet DROP FOREIGN KEY FK_7845C1B3C7F0ABC4");
        $this->addSql("ALTER TABLE core_faq DROP FOREIGN KEY FK_D550A3E0E6ADA943");
        $this->addSql("DROP TABLE core_menu_item");
        $this->addSql("DROP TABLE core_menu");
        $this->addSql("DROP TABLE hn_user_refus_candidature");
        $this->addSql("DROP TABLE core_user_contractualisation");
        $this->addSql("DROP TABLE core_user");
        $this->addSql("DROP TABLE core_user_domaines");
        $this->addSql("DROP TABLE core_role");
        $this->addSql("DROP TABLE core_ressource");
        $this->addSql("DROP TABLE core_acl");
        $this->addSql("DROP TABLE core_mail");
        $this->addSql("DROP TABLE hn_reference");
        $this->addSql("DROP TABLE hn_etablissement");
        $this->addSql("DROP TABLE hn_objet");
        $this->addSql("DROP TABLE hn_objet_role");
        $this->addSql("DROP TABLE hn_objet_type");
        $this->addSql("DROP TABLE hn_objet_ambassadeur");
        $this->addSql("DROP TABLE hn_objet_contenu");
        $this->addSql("DROP TABLE hn_objet_contenu_reference");
        $this->addSql("DROP TABLE hn_objet_consultation");
        $this->addSql("DROP TABLE hn_objet_reference");
        $this->addSql("DROP TABLE hn_questionnaire_question");
        $this->addSql("DROP TABLE hn_questionnaire_type_question");
        $this->addSql("DROP TABLE hn_questionnaire_questionnaire");
        $this->addSql("DROP TABLE hn_questionnaire_reponse");
        $this->addSql("DROP TABLE hn_intervention_regroupement_type");
        $this->addSql("DROP TABLE hn_intervention_initiateur");
        $this->addSql("DROP TABLE hn_intervention_regroupement");
        $this->addSql("DROP TABLE hn_intervention_demande");
        $this->addSql("DROP TABLE hn_intervention_ambassadeur_historique");
        $this->addSql("DROP TABLE hn_intervention_etablissement_rattache");
        $this->addSql("DROP TABLE hn_intervention_objet");
        $this->addSql("DROP TABLE hn_requete");
        $this->addSql("DROP TABLE hn_contact");
        $this->addSql("DROP TABLE core_faq");
        $this->addSql("DROP TABLE core_faq_categorie");
    }
}
