hopitalnumerique_autodiag_list:
    path:     /autodiag
    defaults: { _controller: HopitalNumeriqueAutodiagBundle:Back/Autodiag:list }

hopitalnumerique_autodiag_create:
    path:     /autodiag/create
    defaults: { _controller: HopitalNumeriqueAutodiagBundle:Back/Autodiag:create }

hopitalnumerique_autodiag_edit:
    path:     /autodiag/edit/{id}
    defaults: { _controller: HopitalNumeriqueAutodiagBundle:Back/Autodiag:edit }

hopitalnumerique_autodiag_edit_survey:
    path:     /autodiag/edit/{id}/survey
    defaults: { _controller: HopitalNumeriqueAutodiagBundle:Back/Autodiag:surveyEdit }

hopitalnumerique_autodiag_edit_algorithm:
    path:     /autodiag/edit/{id}/algorithm
    defaults: { _controller: HopitalNumeriqueAutodiagBundle:Back/Autodiag:algorithmEdit }

hopitalnumerique_autodiag_edit_restitution:
    path:     /autodiag/edit/{id}/result
    defaults: { _controller: HopitalNumeriqueAutodiagBundle:Back/Autodiag:restitutionEdit }

hopitalnumerique_autodiag_export_survey:
    path:     /autodiag/edit/{id}/survey/export
    defaults: { _controller: HopitalNumeriqueAutodiagBundle:Back/Export:survey }
