hopitalnumerique_autodiag_entry_add:
    path:     /autodiagnostic/{autodiag}
    defaults: { _controller: HopitalNumeriqueAutodiagBundle:Front/AutodiagEntry:add }

hopitalnumerique_autodiag_entry_edit:
    path:     /autodiagnostic/edit/{entry}
    defaults: { _controller: HopitalNumeriqueAutodiagBundle:Front/AutodiagEntry:edit }

hopitalnumerique_autodiag_entry_attribute_save:
    path:     /autodiagnostic/save/{entry}/{attribute}
    defaults: { _controller: HopitalNumeriqueAutodiagBundle:Front/AutodiagEntry:ajaxAttributeSave }

hopitalnumerique_autodiag_entry_chapter_notconcerned:
    path:     /autodiagnostic/edit/{entry}/setchapternotconcerned/{chapter}
    defaults: { _controller: HopitalNumeriqueAutodiagBundle:Front/AutodiagEntry:ajaxChapterNotConcerned }

hopitalnumerique_autodiag_entry_restitution_demand:
    path:     /autodiagnostic/edit/{entry}/restitution_demand
    defaults: { _controller: HopitalNumeriqueAutodiagBundle:Front/AutodiagEntry:restitutionDemand }

hopitalnumerique_autodiag_synthesis_savenew:
    path: /autodiagnostic/{autodiag}/synthese/save
    methods: ["POST"]
    defaults: { _controller: HopitalNumeriqueAutodiagBundle:Front/Synthesis:saveNew }

hopitalnumerique_autodiag_restitution_index:
    path:     /autodiagnostic/restitution/{synthesis}
    defaults: { _controller: HopitalNumeriqueAutodiagBundle:Front/Restitution:index }

hopitalnumerique_autodiag_account_index:
    path:     compte-hn/autodiagnostic
    defaults: { _controller: HopitalNumeriqueAutodiagBundle:Front/Account:index }