services:
    HopitalNumerique\CoreBundle\Domain\Command\Relation\LinkObjectHandler:
        class: HopitalNumerique\CoreBundle\Domain\Command\Relation\LinkObjectHandler
        arguments:
            - '@HopitalNumerique\CoreBundle\Repository\ObjectIdentity\ObjectIdentityRepository'
            - '@HopitalNumerique\CoreBundle\Repository\ObjectIdentity\RelationRepository'
            - '@doctrine.orm.entity_manager'

    HopitalNumerique\CoreBundle\Domain\Command\Relation\ReorderObjectLinksHandler:
        class: HopitalNumerique\CoreBundle\Domain\Command\Relation\ReorderObjectLinksHandler
        arguments:
            - '@HopitalNumerique\CoreBundle\Repository\ObjectIdentity\RelationRepository'
            - '@doctrine.orm.entity_manager'

    HopitalNumerique\CoreBundle\Domain\Command\Relation\RemoveObjectLinkHandler:
        class: HopitalNumerique\CoreBundle\Domain\Command\Relation\RemoveObjectLinkHandler
        arguments:
            - '@HopitalNumerique\CoreBundle\Repository\ObjectIdentity\RelationRepository'
            - '@doctrine.orm.entity_manager'
