hopital_numerique_expert_admin:
    resource: "@HopitalNumeriqueExpertBundle/Resources/config/routing/admin.yml"
    prefix:   /admin

hopital_numerique_expert_front:
    resource: "@HopitalNumeriqueExpertBundle/Resources/config/routing/front.yml"
    prefix:   /compte-hn
