parameters:
    hopitalnumerique_expert.manager.activiteexpert.class: HopitalNumerique\ExpertBundle\Manager\ActiviteExpertManager
    hopitalnumerique_expert.grid.activiteexpert.class: HopitalNumerique\ExpertBundle\Grid\ActiviteExpertGrid
    hopitalnumerique_expert.form.activiteexpert.class: HopitalNumerique\ExpertBundle\Form\ActiviteExpertType

services:
    hopitalnumerique_expert.manager.activiteexpert:
        class: %hopitalnumerique_expert.manager.activiteexpert.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
           - [ setCache, [ @liip_doctrine_cache.ns.main ] ]

    hopitalnumerique_expert.grid.activiteexpert:
        class: %hopitalnumerique_expert.grid.activiteexpert.class%
        arguments: ["@service_container"]

    hopitalnumerique_expert.form.activiteexpert:
        class: %hopitalnumerique_expert.form.activiteexpert.class%
        arguments: ["@hopitalnumerique_expert.manager.activiteexpert", "@validator"]
        tags:
            - { name: form.type, alias: hopitalnumerique_expert_activiteexpert }
