parameters:
    hopitalnumerique_expert.manager.activiteexpert.class: HopitalNumerique\ExpertBundle\Manager\ActiviteExpertManager
    hopitalnumerique_expert.grid.activiteexpert.class: HopitalNumerique\ExpertBundle\Grid\ActiviteExpertGrid
    hopitalnumerique_expert.form.activiteexpert.class: HopitalNumerique\ExpertBundle\Form\ActiviteExpertType
    hopitalnumerique_expert.manager.evenementexpert.class: HopitalNumerique\ExpertBundle\Manager\EvenementExpertManager
    hopitalnumerique_expert.grid.evenementexpert.class: HopitalNumerique\ExpertBundle\Grid\EvenementExpertGrid
    hopitalnumerique_expert.form.evenementexpert.class: HopitalNumerique\ExpertBundle\Form\EvenementExpertType
    hopitalnumerique_expert.manager.evenementpresenceexpert.class: HopitalNumerique\ExpertBundle\Manager\EvenementPresenceExpertManager
    hopitalnumerique_expert.manager.datefictive.class: HopitalNumerique\ExpertBundle\Manager\DateFictiveActiviteExpertManager

services:
    hopitalnumerique_expert.manager.activiteexpert:
        class: %hopitalnumerique_expert.manager.activiteexpert.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
           - [ setCache, ["@liip_doctrine_cache.ns.main"] ]

    hopitalnumerique_expert.grid.activiteexpert:
        class: %hopitalnumerique_expert.grid.activiteexpert.class%
        arguments: ["@service_container"]

    hopitalnumerique_expert.form.activiteexpert:
        class: %hopitalnumerique_expert.form.activiteexpert.class%
        arguments: ["@hopitalnumerique_reference.manager.reference"]
        tags:
            - { name: form.type, alias: hopitalnumerique_expert_activiteexpert }

    hopitalnumerique_expert.form.activiteexpert.paiement:
        class: 'HopitalNumerique\ExpertBundle\Form\ActiviteExpert\PaiementType'
        tags:
            - { name: form.type, alias: hopitalnumerique_expert_activiteexpert_paiement }

    hopitalnumerique_expert.form.activiteexpert.paiements:
        class: 'HopitalNumerique\ExpertBundle\Form\ActiviteExpert\PaiementsType'
        arguments: ["@nodevo_mail.manager.mail"]
        tags:
            - { name: form.type, alias: hopitalnumerique_expert_activiteexpert_paiements }

    hopitalnumerique_expert.manager.courriel_registre:
        class: 'HopitalNumerique\ExpertBundle\Manager\CourrielRegistreManager'
        arguments: ['@doctrine.orm.entity_manager']

    hopitalnumerique_expert.manager.evenementexpert:
        class: %hopitalnumerique_expert.manager.evenementexpert.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
           - [ setCache, ["@liip_doctrine_cache.ns.main"] ]

    hopitalnumerique_expert.grid.evenementexpert:
        class: %hopitalnumerique_expert.grid.evenementexpert.class%
        arguments: ["@service_container"]

    hopitalnumerique_expert.form.evenementexpert:
        class: %hopitalnumerique_expert.form.evenementexpert.class%
        arguments: ["@hopitalnumerique_expert.manager.evenementexpert", "@validator"]
        tags:
            - { name: form.type, alias: hopitalnumerique_expert_evenementexpert }

    hopitalnumerique_expert.manager.evenementpresenceexpert:
        class: %hopitalnumerique_expert.manager.evenementpresenceexpert.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
           - [ setCache, ["@liip_doctrine_cache.ns.main"] ]

    hopitalnumerique_expert.manager.datefictive:
        class: %hopitalnumerique_expert.manager.datefictive.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
           - [ setCache, ["@liip_doctrine_cache.ns.main"] ]
