<?php

namespace HopitalNumerique\ObjetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends EntityRepository
{
    /**
     * Récupère les données du grid sous forme de tableau correctement formaté
     *
     * @return array
     */
    public function getDatasForGrid()
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('comm.id, comm.dateCreation, comm.texte, comm.publier, objet.id as objId, objet.titre as objTitre, contenu.id as contId, contenu.titre as contTitre, user.nom as userNom, user.prenom as userPrenom')
            ->from('HopitalNumeriqueObjetBundle:Commentaire', 'comm')
            ->leftJoin('comm.objet','objet')
            ->leftJoin('comm.contenu','contenu')
            ->leftJoin('comm.user','user');
            
        return $qb;
    }

    /**
     * Retourne la liste des commentaires étant assigné au domaine
     *
     * @param int $idDomaine Identifiant du domaine à filtrer
     *
     * @return QueryBuilder
     */
    public function findCommentaireByDomaine( $idDomaine )
    {
        $qb = $this->_em->createQueryBuilder();
    
        $qb->select('comm')
            ->from('HopitalNumeriqueObjetBundle:Commentaire', 'comm')
            ->leftJoin('comm.objet', 'objet')
            ->leftJoin('objet.domaines', 'domaine')
            ->where('domaine.id = :idDomaine')
            ->setParameter('idDomaine', $idDomaine);

        return $qb;
    }
}
