hopital_numerique_publication_synthese:
    pattern:  /synthese/{id}
    defaults: { _controller: "HopitalNumeriquePublicationBundle:Publication:synthese", id:1 }
    requirements:
        id: \d+

hopital_numerique_publication_publication_objet:
    pattern:  /{id}-{alias}
    defaults: { _controller: "HopitalNumeriquePublicationBundle:Publication:objet", id:1, alias:alias }
    requirements:
        id: \d+

hopital_numerique_publication_publication_contenu:
    pattern:  /{id}-{alias}/{idc}-{aliasc}
    defaults: { _controller: "HopitalNumeriquePublicationBundle:Publication:contenu", id:1, idc:1, alias:alias, aliasc:aliasc}
    requirements:
        id: \d+

hopital_numerique_publication_publication_article:
    pattern:  /{categorie}/{id}-{alias}
    defaults: { _controller: "HopitalNumeriquePublicationBundle:Publication:article", categorie:categorie, id:1, alias:alias }
    requirements:
        id: \d+