parameters:
    hopitalnumerique_publication.twig.publication.class: HopitalNumerique\PublicationBundle\Twig\PublicationExtension
    #Options
    hopital_numerique_publication.options:

services:
    #Extension Twig
    hopitalnumerique_publication.twig.publication_extension:
        class: %hopitalnumerique_publication.twig.publication.class%
        arguments : ["@service_container"]
        tags:
            - { name: twig.extension }