imports:
    - { resource: commandHandlers.yml }

parameters:
    hopitalnumerique_publication.twig.publication.class: HopitalNumerique\PublicationBundle\Twig\PublicationExtension
    #Options
    hopital_numerique_publication.options:
    #CronLogger
    hopitalnumerique_publication.service.logger.cronlogger.class: HopitalNumerique\PublicationBundle\DependencyInjection\Logger\CronLogger

services:
    #Extension Twig
    hopitalnumerique_publication.twig.publication_extension:
        class: %hopitalnumerique_publication.twig.publication.class%
        arguments : ["@service_container"]
        tags:
            - { name: twig.extension }

    #Cronlogger
    hopitalnumerique_publication.service.logger.cronlogger:
        class: "%hopitalnumerique_publication.service.logger.cronlogger.class%"
        arguments: ["@logger", "@session"]

    hopitalnumerique_publication.grid.suggestion:
        class: 'HopitalNumerique\PublicationBundle\Grid\SuggestionGrid'
        arguments: ["@service_container"]

    hopitalnumerique_publication.repository.suggestion:
        class: HopitalNumerique\PublicationBundle\Repository\SuggestionRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumeriquePublicationBundle:Suggestion'

    hopitalnumerique_publication.service.suggestion_converter:
        class: 'HopitalNumerique\PublicationBundle\Service\SuggestionConverter'
        arguments:
            - '@hopitalnumerique_reference.manager.reference'
            - '@hopitalnumerique_reference.manager.entity_has_reference'
            - '@hopitalnumerique_objet.manager.objet'
            - '@filesystem'
            - '@doctrine.orm.entity_manager'

    hopitalnumerique_publication.form.suggestion:
        class: 'HopitalNumerique\PublicationBundle\Form\Type\SuggestionType'
        arguments:
            - '@security.token_storage'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }

    hopitalnumerique_publication.service.relation_finder:
        class: HopitalNumerique\PublicationBundle\Service\RelationFinder\RelationFinder

    hopitalnumerique_publication.service.destination_content_source_content:
        class: HopitalNumerique\PublicationBundle\Service\RelationFinder\Finders\DestinationContentToSourceContentFinder
        arguments:
            - "@hopitalnumerique_objet.manager.contenu"
            - "@hopitalnumerique_objet.dependency_injection.production_liee"
        tags:
            - { name: resource.relation_finder }

    hopitalnumerique_publication.service.destionation_content_source_object:
        class: HopitalNumerique\PublicationBundle\Service\RelationFinder\Finders\DestinationContentToSourceObjectFinder
        arguments:
            - "@hopitalnumerique_objet.repository.objet"
            - "@hopitalnumerique_objet.manager.contenu"
            - "@hopitalnumerique_objet.dependency_injection.production_liee"
            - "@hopitalnumerique_publication.service.relation_finder"
        tags:
            - { name: resource.relation_finder }

    hopitalnumerique_publication.service.destination_object_source_object:
        class: HopitalNumerique\PublicationBundle\Service\RelationFinder\Finders\DestinationObjectToSourceObjectFinder
        arguments:
            - "@hopitalnumerique_objet.manager.objet"
            - "@hopitalnumerique_objet.dependency_injection.production_liee"
        tags:
            - { name: resource.relation_finder }

    hopitalnumerique_publication.service.source_content_destination_content:
        class: HopitalNumerique\PublicationBundle\Service\RelationFinder\Finders\SourceContentToDestinationContentFinder
        arguments:
            - "@hopitalnumerique_objet.manager.contenu"
            - "@hopitalnumerique_objet.dependency_injection.production_liee"
        tags:
            - { name: resource.relation_finder }

    hopitalnumerique_publication.service.source_object_destination_content:
        class: HopitalNumerique\PublicationBundle\Service\RelationFinder\Finders\SourceObjectToDestinationContentFinder
        arguments:
            - "@hopitalnumerique_objet.manager.contenu"
            - "@hopitalnumerique_objet.dependency_injection.production_liee"
        tags:
            - { name: resource.relation_finder }

    hopitalnumerique_publication.service.source_object_destination_object:
        class: HopitalNumerique\PublicationBundle\Service\RelationFinder\Finders\SourceObjectToDestinationObjectFinder
        arguments:
            - "@hopitalnumerique_objet.manager.objet"
            - "@hopitalnumerique_objet.dependency_injection.production_liee"
        tags:
            - { name: resource.relation_finder }

    hopitalnumerique_publication.service.source_content_destination_object:
        class: HopitalNumerique\PublicationBundle\Service\RelationFinder\Finders\SourceContentToDestinationObjectFinder
        arguments:
            - "@hopitalnumerique_objet.repository.objet"
            - "@hopitalnumerique_objet.dependency_injection.production_liee"
        tags:
            - { name: resource.relation_finder }

    hopitalnumerique_publication.service.destination_object_source_content:
        class: HopitalNumerique\PublicationBundle\Service\RelationFinder\Finders\DestinationObjectToSourceContent
        arguments:
            - "@hopitalnumerique_objet.manager.contenu"
            - "@hopitalnumerique_objet.dependency_injection.production_liee"
        tags:
            - { name: resource.relation_finder }

    hopitalnumerique_publication.media_uploader:
        class: HopitalNumerique\PublicationBundle\Service\Converter\MediaUploader
        arguments:
            - '%kernel.root_dir%/../web/'
            - 'medias/Objets/Import/'

    hopitalnumerique_publication.content_generator:
        class: HopitalNumerique\PublicationBundle\Service\Converter\ContentGenerator
        arguments:
            - '@hopitalnumerique_publication.node.parser'
            - '@doctrine.orm.entity_manager'
            - '@hopitalnumerique_publication.content.target_blank'
            - '@hopitalnumerique_publication.media_uploader'


    hopitalnumerique_publication.node.parser:
        class: HopitalNumerique\PublicationBundle\Service\Converter\Node\NodeParser

    hopitalnumerique_publication.node.empty_tag_cleaner:
        class: HopitalNumerique\PublicationBundle\Service\Converter\Node\Parser\EmptyTagCleaner
        public: false
        tags:
            - { name: converter.node_parser, priority: 99 }

    hopitalnumerique_publication.node.image_renamer:
        class: HopitalNumerique\PublicationBundle\Service\Converter\Node\Parser\ImageRenamer
        public: false
        calls:
            - [setMediaUploader, ['@hopitalnumerique_publication.media_uploader']]
        tags:
            - { name: converter.node_parser, priority: 99 }

    hopitalnumerique_publication.node.image_remover:
        class: HopitalNumerique\PublicationBundle\Service\Converter\Node\Parser\ImageRemover
        public: false
        calls:
            - [setMediaUploader, ['@hopitalnumerique_publication.media_uploader']]
        tags:
            - { name: converter.node_parser, priority: 110 }

    hopitalnumerique_publication.node.tag_remover:
        class: HopitalNumerique\PublicationBundle\Service\Converter\Node\Parser\TagRemover
        public: false
        tags:
            - { name: converter.node_parser, priority: 90 }

    hopitalnumerique_publication.node.customer_attributes:
        class: HopitalNumerique\PublicationBundle\Service\Converter\Node\Parser\CustomAttributes
        public: false
        tags:
            - { name: converter.node_parser }

    hopitalnumerique_publication.node.tag_switcher:
            class: HopitalNumerique\PublicationBundle\Service\Converter\Node\Parser\TagSwitcher
            public: false
            tags:
                - { name: converter.node_parser, priority: 80 }

    hopitalnumerique_publication.pandoc:
        class: HopitalNumerique\PublicationBundle\Service\Converter\Extractor\Pandoc
        arguments:
            - '%pandoc_path%'
            - '%pandoc_working_dir%'
            - '%pandoc_data_dir%'

    hopitalnumerique_publication.content.target_blank:
        class: HopitalNumerique\PublicationBundle\Service\Converter\Content\TargetBlank

    hopitalnumerique_publication.repository.document:
        class: HopitalNumerique\PublicationBundle\Repository\Converter\DocumentRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumeriquePublicationBundle:Converter\Document'
