parameters:
    hopitalnumerique_publication.twig.publication.class: HopitalNumerique\PublicationBundle\Twig\PublicationExtension
    #Options
    hopital_numerique_publication.options:
    #CronLogger
    hopitalnumerique_publication.service.logger.cronlogger.class: HopitalNumerique\PublicationBundle\DependencyInjection\Logger\CronLogger

services:
    #Extension Twig
    hopitalnumerique_publication.twig.publication_extension:
        class: %hopitalnumerique_publication.twig.publication.class%
        arguments : ["@service_container"]
        tags:
            - { name: twig.extension }

    #Cronlogger
    hopitalnumerique_publication.service.logger.cronlogger:
        class: "%hopitalnumerique_publication.service.logger.cronlogger.class%"
        arguments: ["@logger", "@session"]

    hopitalnumerique_publication.grid.suggestion:
        class: 'HopitalNumerique\PublicationBundle\Grid\SuggestionGrid'
        arguments: ["@service_container"]

    hopitalnumerique_publication.repository.suggestion:
        class: HopitalNumerique\PublicationBundle\Repository\SuggestionRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumeriquePublicationBundle:Suggestion'

    hopitalnumerique_publication.service.suggestion_converter:
        class: 'HopitalNumerique\PublicationBundle\Service\SuggestionConverter'
        arguments:
            - '@hopitalnumerique_reference.manager.reference'
            - '@hopitalnumerique_reference.manager.entity_has_reference'
            - '@hopitalnumerique_objet.manager.objet'
            - '@filesystem'
            - '@doctrine.orm.entity_manager'

    hopitalnumerique_publication.form.suggestion:
        class: 'HopitalNumerique\PublicationBundle\Form\Type\SuggestionType'
        arguments:
            - '@security.token_storage'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }