parameters:
    hopitalnumerique_intervention.type.intervention_demande.class: HopitalNumerique\InterventionBundle\Form\InterventionDemandeType
    hopitalnumerique_intervention.type.user.class: HopitalNumerique\InterventionBundle\Form\UserType

services:
    hopitalnumerique_intervention.type.intervention_demande:
        class: "%hopitalnumerique_intervention.type.intervention_demande.class%"
        tags:
            - { name: form.type, alias: hopitalnumerique_interventionbundle_interventiondemande }
        arguments: ["@service_container"]
    hopitalnumerique_intervention.type.user:
        class: "%hopitalnumerique_intervention.type.user.class%"
        tags:
            - { name: form.type, alias: hopitalnumerique_interventionbundle_user }
        arguments: ["@service_container"]
