parameters:
    hopitalnumerique_intervention.manager.intervention_courriel.class: HopitalNumerique\InterventionBundle\Manager\InterventionCourrielManager
    hopitalnumerique_intervention.manager.intervention_demande.class: HopitalNumerique\InterventionBundle\Manager\InterventionDemandeManager
    hopitalnumerique_intervention.manager.intervention_evaluation.class: HopitalNumerique\InterventionBundle\Manager\InterventionEvaluationManager
    hopitalnumerique_intervention.manager.intervention_evaluation_etat.class: HopitalNumerique\InterventionBundle\Manager\InterventionEvaluationEtatManager
    hopitalnumerique_intervention.manager.intervention_etat.class: HopitalNumerique\InterventionBundle\Manager\InterventionEtatManager
    hopitalnumerique_intervention.manager.intervention_initiateur.class: HopitalNumerique\InterventionBundle\Manager\InterventionInitiateurManager
    hopitalnumerique_intervention.manager.intervention_regroupement.class: HopitalNumerique\InterventionBundle\Manager\InterventionRegroupementManager
    hopitalnumerique_intervention.manager.form_intervention_demande.class: HopitalNumerique\InterventionBundle\Manager\Form\InterventionDemandeManager
    hopitalnumerique_intervention.manager.form_user.class: HopitalNumerique\InterventionBundle\Manager\Form\UserManager
    hopitalnumerique_intervention.manager.form_etablissement.class: HopitalNumerique\InterventionBundle\Manager\Form\EtablissementManager

services:
    hopitalnumerique_intervention.manager.intervention_courriel:
        class: "%hopitalnumerique_intervention.manager.intervention_courriel.class%"
        arguments: ["@nodevo_mail.manager.mail", "@mailer", "@twig"]
    hopitalnumerique_intervention.manager.intervention_demande:
        class: "%hopitalnumerique_intervention.manager.intervention_demande.class%"
        arguments: ["@doctrine.orm.entity_manager", "@security.context", "@router", "@hopitalnumerique_user.manager.user", "@hopitalnumerique_intervention.manager.intervention_etat", "@hopitalnumerique_intervention.manager.intervention_evaluation_etat", "@hopitalnumerique_intervention.manager.intervention_regroupement", "@hopitalnumerique_intervention.manager.intervention_courriel"]
    hopitalnumerique_intervention.manager.intervention_etat:
        class: "%hopitalnumerique_intervention.manager.intervention_etat.class%"
        arguments: ["@hopitalnumerique_reference.manager.reference"]
    hopitalnumerique_intervention.manager.intervention_evaluation:
        class: "%hopitalnumerique_intervention.manager.intervention_evaluation.class%"
        arguments: ["@security.context", "@router", "@hopitalnumerique_intervention.manager.intervention_courriel"]
    hopitalnumerique_intervention.manager.intervention_evaluation_etat:
        class: "%hopitalnumerique_intervention.manager.intervention_evaluation_etat.class%"
        arguments: ["@hopitalnumerique_reference.manager.reference"]
    hopitalnumerique_intervention.manager.intervention_initiateur:
        class: "%hopitalnumerique_intervention.manager.intervention_initiateur.class%"
        arguments: ["@doctrine.orm.entity_manager"]
    hopitalnumerique_intervention.manager.intervention_regroupement:
        class: "%hopitalnumerique_intervention.manager.intervention_regroupement.class%"
        arguments: ["@doctrine.orm.entity_manager"]
    hopitalnumerique_intervention.manager.form_intervention_demande:
        class: "%hopitalnumerique_intervention.manager.form_intervention_demande.class%"
        arguments: ["@hopitalnumerique_reference.manager.reference", "@hopitalnumerique_objet.manager.objet"]
    hopitalnumerique_intervention.manager.form_user:
        class: "%hopitalnumerique_intervention.manager.form_user.class%"
        arguments: ["@hopitalnumerique_user.manager.user", "@hopitalnumerique_reference.manager.reference", "@hopitalnumerique_etablissement.manager.etablissement"]
    hopitalnumerique_intervention.manager.form_etablissement:
        class: "%hopitalnumerique_intervention.manager.form_etablissement.class%"
        arguments: ["@hopitalnumerique_etablissement.manager.etablissement"]
