parameters:
    hopitalnumerique_intervention.manager.form_intervention_demande.class: HopitalNumerique\InterventionBundle\Manager\Form\InterventionDemandeManager
    hopitalnumerique_intervention.manager.form_user.class: HopitalNumerique\InterventionBundle\Manager\Form\UserManager

services:
    hopitalnumerique_intervention.manager.form_intervention_demande:
        class: "%hopitalnumerique_intervention.manager.form_intervention_demande.class%"
        arguments: ["@service_container"]
    hopitalnumerique_intervention.manager.form_user:
        class: "%hopitalnumerique_intervention.manager.form_user.class%"
        arguments: ["@service_container"]
