parameters:
    hopitalnumerique_intervention.manager.intervention_courriel.class: HopitalNumerique\InterventionBundle\Manager\InterventionCourrielManager
    hopitalnumerique_intervention.manager.intervention_demande.class: HopitalNumerique\InterventionBundle\Manager\InterventionDemandeManager
    hopitalnumerique_intervention.manager.intervention_etat.class: HopitalNumerique\InterventionBundle\Manager\InterventionEtatManager
    hopitalnumerique_intervention.manager.intervention_initiateur.class: HopitalNumerique\InterventionBundle\Manager\InterventionInitiateurManager
    hopitalnumerique_intervention.manager.form_intervention_demande.class: HopitalNumerique\InterventionBundle\Manager\Form\InterventionDemandeManager
    hopitalnumerique_intervention.manager.form_user.class: HopitalNumerique\InterventionBundle\Manager\Form\UserManager
    hopitalnumerique_intervention.manager.form_etablissement.class: HopitalNumerique\InterventionBundle\Manager\Form\EtablissementManager

services:
    hopitalnumerique_intervention.manager.intervention_courriel:
        class: "%hopitalnumerique_intervention.manager.intervention_courriel.class%"
        arguments: ["@service_container", "@twig"]
    hopitalnumerique_intervention.manager.intervention_demande:
        class: "%hopitalnumerique_intervention.manager.intervention_demande.class%"
        arguments: ["@doctrine.orm.entity_manager", "@security.context"]
    hopitalnumerique_intervention.manager.intervention_etat:
        class: "%hopitalnumerique_intervention.manager.intervention_etat.class%"
        arguments: ["@service_container"]
    hopitalnumerique_intervention.manager.intervention_initiateur:
        class: "%hopitalnumerique_intervention.manager.intervention_initiateur.class%"
        arguments: ["@doctrine.orm.entity_manager"]
    hopitalnumerique_intervention.manager.form_intervention_demande:
        class: "%hopitalnumerique_intervention.manager.form_intervention_demande.class%"
        arguments: ["@service_container"]
    hopitalnumerique_intervention.manager.form_user:
        class: "%hopitalnumerique_intervention.manager.form_user.class%"
        arguments: ["@service_container"]
    hopitalnumerique_intervention.manager.form_etablissement:
        class: "%hopitalnumerique_intervention.manager.form_etablissement.class%"
        arguments: ["@service_container"]
