hopital_numerique_intervention_demande_nouveau:
    pattern:  /demande/nouveau/{ambassadeur}
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Demande:nouveau" }
    requirements:
        ambassadeur: \d+

hopital_numerique_intervention_demande_voir:
    pattern:  /demande/voir/{id}
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Demande:voir" }
    requirements:
        id: \d+

hopital_numerique_intervention_demande_edit:
    pattern:  /demande/edit/{id}
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Demande:edit" }
    requirements:
        id: \d+

hopital_numerique_intervention_demande_liste:
    pattern:  /demandes/liste
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Demande:liste" }

#<-- Vues Grid
hopital_numerique_intervention_demandes_nouvelles:
    pattern: /demandes/liste/nouvelles
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Demande:listeDemandesNouvelles" }
hopital_numerique_intervention_demandes_traitees:
    pattern: /demandes/liste/traitees
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Demande:listeDemandesTraitees" }
#-->
