hopital_numerique_intervention_demande_liste:
    pattern:  /demandes/liste
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Demande:liste" }

hopital_numerique_intervention_demande_suivi_demandes:
    pattern:  /demandes/suivi-demandes
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Demande:suiviDemandes" }

hopital_numerique_intervention_demande_voir:
    pattern:  /demande/voir/{id}
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Demande:voir", id: 0 }
    requirements:
        id: \d+

hopital_numerique_intervention_demande_nouveau:
    pattern:  /demande/nouveau/{ambassadeur}
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Form/Demande:nouveau", ambassadeur: 0 }
    requirements:
        ambassadeur: \d+

hopital_numerique_intervention_demande_edit:
    pattern:  /demande/edit/{id}
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Form/Demande:edit", id: 0 }
    requirements:
        id: \d+

hopital_numerique_intervention_demande_cron:
    pattern:  /cron/{id}
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Demande:cron" }

#<-- Vues Grid
hopital_numerique_intervention_grid_cmsi_demandes_nouvelles:
    pattern: /demandes/grid/cmsi/nouvelles
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Demande:gridCmsiDemandesNouvelles" }
hopital_numerique_intervention_grid_cmsi_demandes_traitees:
    pattern: /demandes/grid/cmsi/traitees
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Demande:gridCmsiDemandesTraitees" }
hopital_numerique_intervention_grid_directeur_suivi_demandes:
    pattern: /demandes/grid/directeur
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Demande:gridDirecteurSuiviDemandes" }
hopital_numerique_intervention_grid_ambassadeur_demandes:
    pattern: /demandes/grid/ambassadeur
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Demande:gridAmbassadeurDemandes" }
hopital_numerique_intervention_grid_etablissement_demandes:
    pattern: /demandes/grid/etablissement
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Demande:gridEtablissementDemandes" }
#-->
