parameters:
#    hopital_numerique_intervention.example.class: HopitalNumerique\InterventionBundle\Example

services:
#    hopital_numerique_intervention.example:
#        class: %hopital_numerique_intervention.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
