imports:
    - { resource: managers.yml }
    - { resource: formulaires.yml }
    - { resource: grids.yml }

parameters:
    hopitalnumerique_intervention.service.demande.etat_type_derniere_demande.class: HopitalNumerique\InterventionBundle\DependencyInjection\Demande\EtatTypeDerniereDemande

services:
    hopitalnumerique_intervention.service.demande.etat_type_derniere_demande:
        class: "%hopitalnumerique_intervention.service.demande.etat_type_derniere_demande.class%"
        arguments: ["@session"]
