imports:
    - { resource: managers.yml }
    - { resource: formulaires.yml }
    - { resource: grids.yml }
    - { resource: repositories.yml }
    - { resource: events.yml }

parameters:
    hopitalnumerique_intervention.service.demande.etat_type_derniere_demande.class: HopitalNumerique\InterventionBundle\DependencyInjection\Demande\EtatTypeDerniereDemande
    hopitalnumerique_intervention.service.demande.envoi_courriels_affichage_logs.class: HopitalNumerique\InterventionBundle\DependencyInjection\Demande\EnvoiCourrielsAffichageLogs

services:
    hopitalnumerique_intervention.service.demande.etat_type_derniere_demande:
        class: "%hopitalnumerique_intervention.service.demande.etat_type_derniere_demande.class%"
        arguments: ["@session"]

    hopitalnumerique_intervention.service.demande.envoi_courriels_affichage_logs:
        class: "%hopitalnumerique_intervention.service.demande.envoi_courriels_affichage_logs.class%"
        arguments: ["@logger", "@session"]

    HopitalNumerique\InterventionBundle\Service\InterventionDemandeBuilder:
        class: HopitalNumerique\InterventionBundle\Service\InterventionDemandeBuilder

    HopitalNumerique\InterventionBundle\Service\InterventionDemandeWorkflow:
        class: HopitalNumerique\InterventionBundle\Service\InterventionDemandeWorkflow

    hopitalnumerique_intervention.dependency_injection.intervention.forfait_transport:
        class: 'HopitalNumerique\InterventionBundle\DependencyInjection\Intervention\ForfaitTransport'
        arguments: ['@ivory_google_map.distance_matrix', '@hopitalnumerique_intervention.manager.intervention.forfait_transport']

    hopitalnumerique_intervention.widget.request:
        class: HopitalNumerique\InterventionBundle\Service\Widget\RequestWidget
        tags:
            - { name: new_account.dashboard_widget, type: dashboard }
        arguments:
            - '@twig'
            - '@security.token_storage'
            - '@translator'
        calls:
            - [setInterventionRequestRepository, ['@hopitalnumerique_intervention.repository.intervention_demande']]
        public: false

    hopitalnumerique_intervention.widget.intervention:
        class: HopitalNumerique\InterventionBundle\Service\Widget\InterventionWidget
        tags:
            - { name: new_account.dashboard_widget, type: service }
        arguments:
            - '@twig'
            - '@security.token_storage'
            - '@translator'
            - '@router'
            - '@hn.intervention.repository.demande'
        public: false

    hopitalnumerique_intervention.repository.intervention_demande:
        class: 'HopitalNumerique\InterventionBundle\Repository\InterventionDemandeRepository'
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumerique\InterventionBundle\Entity\InterventionDemande'

    hopitalnumerique_intervention.service.builder.intervention_demande:
        class: HopitalNumerique\InterventionBundle\Service\InterventionDemandeBuilder
