imports:
    - { resource: managers.yml }
    - { resource: formulaires.yml }
    - { resource: grids.yml }

parameters:
    hopitalnumerique_intervention.service.demande.etat_type_derniere_demande.class: HopitalNumerique\InterventionBundle\DependencyInjection\Demande\EtatTypeDerniereDemande
    hopitalnumerique_intervention.service.demande.envoi_courriels_affichage_logs.class: HopitalNumerique\InterventionBundle\DependencyInjection\Demande\EnvoiCourrielsAffichageLogs

services:
    hopitalnumerique_intervention.service.demande.etat_type_derniere_demande:
        class: "%hopitalnumerique_intervention.service.demande.etat_type_derniere_demande.class%"
        arguments: ["@session"]

    hopitalnumerique_intervention.service.demande.envoi_courriels_affichage_logs:
        class: "%hopitalnumerique_intervention.service.demande.envoi_courriels_affichage_logs.class%"
        arguments: ["@logger", "@session"]

    hopitalnumerique_intervention.dependency_injection.intervention.forfait_transport:
        class: 'HopitalNumerique\InterventionBundle\DependencyInjection\Intervention\ForfaitTransport'
        arguments: ['@ivory_google_map.distance_matrix', '@hopitalnumerique_intervention.manager.intervention.forfait_transport']
