hopital_numerique_recherche_homepage:
    pattern: ''
    defaults: { _controller: 'HopitalNumeriqueRechercheBundle:Referencement:index' }
    methods: 'GET'

hopitalnumerique_recherche_referencement_indexwithreferences:
    pattern: '/references/{referenceString}'
    defaults: { _controller: 'HopitalNumeriqueRechercheBundle:Referencement:indexWithReferences' }
    methods: 'GET'
    requirements:
        referenceString: '[\d\-]+'

hopitalnumerique_recherche_referencement_jsonentitiesbyreferences:
    pattern: 'json-entities-by-references'
    defaults: { _controller: 'HopitalNumeriqueRechercheBundle:Referencement:jsonEntitiesByReferences' }
    methods: 'POST'

hopitalnumerique_recherche_referencement_jsonentities:
    pattern: 'view-entities'
    defaults: { _controller: 'HopitalNumeriqueRechercheBundle:Referencement:jsonEntities' }
    methods: 'POST'

hopitalnumerique_recherche_referencement_requete_popinsave:
    pattern: 'requete/popin-save'
    defaults: { _controller: 'HopitalNumeriqueRechercheBundle:Referencement\Requete:popinSave' }
    methods: 'POST'

hopitalnumerique_recherche_referencement_requete_save:
    pattern: 'requete/save'
    defaults: { _controller: 'HopitalNumeriqueRechercheBundle:Referencement\Requete:save' }
    methods: 'POST'

hopitalnumerique_recherche_referencement_requete_savesession:
    pattern: 'requete/save-session'
    defaults: { _controller: 'HopitalNumeriqueRechercheBundle:Referencement\Requete:saveSession' }
    methods: 'POST'
