services:
    autodiag.attribute_builder_provider:
        class: HopitalNumerique\AutodiagBundle\Service\Attribute\AttributeBuilderProvider

    autodiag.attribute_builder.criticite:
        public: false
        class: HopitalNumerique\AutodiagBundle\Service\Attribute\Builder\CriticiteBuilder
        calls:
            - [setTwigRenderer, ['@twig']]
            - [setCsrfTokenManager, ['@security.csrf.token_manager']]
        arguments: ['@doctrine.orm.entity_manager', '@form.factory']
        tags:
            - { name: autodiag.attribute_builder }

    autodiag.attribute_builder.maitrise:
        public: false
        class: HopitalNumerique\AutodiagBundle\Service\Attribute\Builder\MaitriseBuilder
        calls:
            - [setTwigRenderer, ['@twig']]
            - [setCsrfTokenManager, ['@security.csrf.token_manager']]
        arguments: ['@doctrine.orm.entity_manager', '@form.factory']
        tags:
            - { name: autodiag.attribute_builder }

    autodiag.attribute_builder.text:
        public: false
        class: HopitalNumerique\AutodiagBundle\Service\Attribute\Builder\TextBuilder
        calls:
            - [setTwigRenderer, ['@twig']]
            - [setCsrfTokenManager, ['@security.csrf.token_manager']]
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: autodiag.attribute_builder }

    autodiag.attribute_builder.select:
        public: false
        class: HopitalNumerique\AutodiagBundle\Service\Attribute\Builder\SelectBuilder
        calls:
            - [setTwigRenderer, ['@twig']]
            - [setCsrfTokenManager, ['@security.csrf.token_manager']]
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: autodiag.attribute_builder }

    autodiag.attribute_builder.radio:
        public: false
        class: HopitalNumerique\AutodiagBundle\Service\Attribute\Builder\RadioBuilder
        calls:
            - [setTwigRenderer, ['@twig']]
            - [setCsrfTokenManager, ['@security.csrf.token_manager']]
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: autodiag.attribute_builder }
