nodevo_mail_recommandation_popin:
    pattern: '/popin'
    defaults: { _controller: 'NodevoMailBundle:Recommandation:popin' }
    methods: 'GET|POST'

nodevo_mail_recommandation_topic:
    pattern: '/topic_recommandation'
    defaults: { _controller: 'NodevoMailBundle:Recommandation:topicRecommandation' }
    methods: 'GET|POST'