/* <-- ADMIN */
    /* Création des tables */
    CREATE TABLE hn_communautepratique_groupe (group_id INT UNSIGNED AUTO_INCREMENT NOT NULL, dom_id INT NOT NULL, qst_id INT NOT NULL COMMENT 'ID du questionnaire', group_titre VARCHAR(255) NOT NULL, group_description_courte TEXT NOT NULL, group_description_html TEXT NOT NULL, group_nombre_participants_maximum SMALLINT UNSIGNED NOT NULL, group_date_inscription_ouverture DATE NOT NULL, group_date_demarrage DATE NOT NULL, group_date_fin DATE NOT NULL, group_vedette TINYINT(1) DEFAULT '0' NOT NULL, INDEX IDX_A34AA84569893F8F (dom_id), INDEX IDX_A34AA845B293CE31 (qst_id), PRIMARY KEY(group_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
    CREATE TABLE hn_communautepratique_groupe_animateur (group_id INT UNSIGNED NOT NULL, usr_id INT NOT NULL COMMENT 'ID de l utilisateur', INDEX IDX_840981F7FE54D947 (group_id), INDEX IDX_840981F7C69D3FB (usr_id), PRIMARY KEY(group_id, usr_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
    ALTER TABLE hn_communautepratique_groupe ADD CONSTRAINT FK_A34AA84569893F8F FOREIGN KEY (dom_id) REFERENCES hn_domaine (dom_id) ON DELETE CASCADE;
    ALTER TABLE hn_communautepratique_groupe ADD CONSTRAINT FK_A34AA845B293CE31 FOREIGN KEY (qst_id) REFERENCES hn_questionnaire_questionnaire (qst_id) ON DELETE CASCADE;
    ALTER TABLE hn_communautepratique_groupe_animateur ADD CONSTRAINT FK_840981F7FE54D947 FOREIGN KEY (group_id) REFERENCES hn_communautepratique_groupe (group_id);
    ALTER TABLE hn_communautepratique_groupe_animateur ADD CONSTRAINT FK_840981F7C69D3FB FOREIGN KEY (usr_id) REFERENCES core_user (usr_id);
    ALTER TABLE hn_communautepratique_groupe ADD group_actif TINYINT(1) DEFAULT '0' NOT NULL;
    CREATE TABLE hn_communautepratique_groupe_user (group_id INT UNSIGNED NOT NULL, usr_id INT NOT NULL COMMENT 'ID de l utilisateur', INDEX IDX_305DA7BDFE54D947 (group_id), INDEX IDX_305DA7BDC69D3FB (usr_id), PRIMARY KEY(group_id, usr_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
    ALTER TABLE hn_communautepratique_groupe_user ADD CONSTRAINT FK_305DA7BDFE54D947 FOREIGN KEY (group_id) REFERENCES hn_communautepratique_groupe (group_id);
    ALTER TABLE hn_communautepratique_groupe_user ADD CONSTRAINT FK_305DA7BDC69D3FB FOREIGN KEY (usr_id) REFERENCES core_user (usr_id);
    CREATE TABLE hn_communautepratique_document (doc_id INT UNSIGNED AUTO_INCREMENT NOT NULL, group_id INT UNSIGNED NOT NULL, usr_id INT NOT NULL COMMENT 'ID de l utilisateur', doc_nom VARCHAR(255) NOT NULL, doc_libelle VARCHAR(255) NOT NULL, doc_size INT NOT NULL COMMENT 'Taille du fichier en octet', INDEX IDX_E5FB67F7FE54D947 (group_id), INDEX IDX_E5FB67F7C69D3FB (usr_id), PRIMARY KEY(doc_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
    ALTER TABLE hn_communautepratique_document ADD CONSTRAINT FK_E5FB67F7FE54D947 FOREIGN KEY (group_id) REFERENCES hn_communautepratique_groupe (group_id) ON DELETE CASCADE;
    ALTER TABLE hn_communautepratique_document ADD CONSTRAINT FK_E5FB67F7C69D3FB FOREIGN KEY (usr_id) REFERENCES core_user (usr_id) ON DELETE CASCADE;
    ALTER TABLE hn_communautepratique_document ADD doc_date_creation DATETIME NOT NULL;
    CREATE TABLE hn_communautepratique_fiche (fic_id INT UNSIGNED AUTO_INCREMENT NOT NULL, group_id INT UNSIGNED NOT NULL, fic_question_posee VARCHAR(255) NOT NULL, fic_contexte TEXT NOT NULL COMMENT 'Éléments de contexte à prendre en compte', fic_description TEXT NOT NULL, fic_aide_attendue TEXT NOT NULL, fic_resume TEXT NOT NULL, INDEX IDX_D811C99CFE54D947 (group_id), PRIMARY KEY(fic_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
    CREATE TABLE hn_communautepratique_fiche_document (fic_id INT UNSIGNED NOT NULL, doc_id INT UNSIGNED NOT NULL, INDEX IDX_80252B184BDE1C17 (fic_id), INDEX IDX_80252B18895648BC (doc_id), PRIMARY KEY(fic_id, doc_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
    ALTER TABLE hn_communautepratique_fiche ADD CONSTRAINT FK_D811C99CFE54D947 FOREIGN KEY (group_id) REFERENCES hn_communautepratique_groupe (group_id) ON DELETE CASCADE;
    ALTER TABLE hn_communautepratique_fiche_document ADD CONSTRAINT FK_80252B184BDE1C17 FOREIGN KEY (fic_id) REFERENCES hn_communautepratique_fiche (fic_id);
    ALTER TABLE hn_communautepratique_fiche_document ADD CONSTRAINT FK_80252B18895648BC FOREIGN KEY (doc_id) REFERENCES hn_communautepratique_document (doc_id);
    ALTER TABLE hn_communautepratique_fiche ADD usr_id INT NOT NULL COMMENT 'ID de l utilisateur';
    ALTER TABLE hn_communautepratique_fiche ADD CONSTRAINT FK_D811C99CC69D3FB FOREIGN KEY (usr_id) REFERENCES core_user (usr_id) ON DELETE CASCADE;
    CREATE INDEX IDX_D811C99CC69D3FB ON hn_communautepratique_fiche (usr_id);
    ALTER TABLE hn_communautepratique_fiche ADD fic_resolu TINYINT(1) DEFAULT '0' NOT NULL;
    ALTER TABLE hn_communautepratique_fiche_document DROP FOREIGN KEY FK_80252B184BDE1C17;
    ALTER TABLE hn_communautepratique_fiche_document DROP FOREIGN KEY FK_80252B18895648BC;
    ALTER TABLE hn_communautepratique_fiche_document ADD CONSTRAINT FK_80252B184BDE1C17 FOREIGN KEY (fic_id) REFERENCES hn_communautepratique_fiche (fic_id) ON DELETE CASCADE;
    ALTER TABLE hn_communautepratique_fiche_document ADD CONSTRAINT FK_80252B18895648BC FOREIGN KEY (doc_id) REFERENCES hn_communautepratique_document (doc_id) ON DELETE CASCADE;
    CREATE TABLE hn_communautepratique_commentaire (com_id INT UNSIGNED AUTO_INCREMENT NOT NULL, usr_id INT NOT NULL COMMENT 'ID de l utilisateur', group_id INT UNSIGNED NOT NULL, fic_id INT UNSIGNED NOT NULL, com_message TEXT NOT NULL, com_date_creation DATETIME NOT NULL, com_date_derniere_modification DATETIME DEFAULT NULL, INDEX IDX_72D666FFC69D3FB (usr_id), INDEX IDX_72D666FFFE54D947 (group_id), INDEX IDX_72D666FF4BDE1C17 (fic_id), PRIMARY KEY(com_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
    ALTER TABLE hn_communautepratique_commentaire ADD CONSTRAINT FK_72D666FFC69D3FB FOREIGN KEY (usr_id) REFERENCES core_user (usr_id) ON DELETE CASCADE;
    ALTER TABLE hn_communautepratique_commentaire ADD CONSTRAINT FK_72D666FFFE54D947 FOREIGN KEY (group_id) REFERENCES hn_communautepratique_groupe (group_id) ON DELETE CASCADE;
    ALTER TABLE hn_communautepratique_commentaire ADD CONSTRAINT FK_72D666FF4BDE1C17 FOREIGN KEY (fic_id) REFERENCES hn_communautepratique_fiche (fic_id) ON DELETE CASCADE;
    ALTER TABLE hn_communautepratique_commentaire CHANGE fic_id fic_id INT UNSIGNED DEFAULT NULL, CHANGE group_id group_id INT UNSIGNED DEFAULT NULL;
    ALTER TABLE hn_communautepratique_fiche ADD fic_date_creation DATETIME NOT NULL;

    /* Droits */
    INSERT INTO `core_ressource` (`res_id`, `res_nom`, `res_pattern`, `res_order`, `res_type`) VALUES (NULL, 'BackOffice - Gestion de la communauté de pratiques', '/^\\/admin\\/communaute\\-de\\-pratiques/', '38', '2');

    /* Menu */
    INSERT INTO `core_menu_item` (`itm_id`, `itm_parent`, `mnu_menu`, `itm_name`, `itm_route`, `itm_route_parameters`, `itm_route_absolute`, `itm_uri`, `itm_icon`, `itm_display`, `itm_display_children`, `itm_role`, `itm_order`) VALUES ('253', NULL, '1', 'Communauté de pratiques', 'hopitalnumerique_communautepratique_admin_groupe_list', '[]', '0', NULL, 'fa fa-users', '1', '0', 'IS_AUTHENTICATED_ANONYMOUSLY', '15');
    INSERT INTO `core_menu_item` (`itm_id`, `itm_parent`, `mnu_menu`, `itm_name`, `itm_route`, `itm_route_parameters`, `itm_route_absolute`, `itm_uri`, `itm_icon`, `itm_display`, `itm_display_children`, `itm_role`, `itm_order`) VALUES ('254', '253', '1', 'Éditer un groupe', 'hopitalnumerique_communautepratique_admin_groupe_edit', NULL, '0', NULL, NULL, '0', '0', 'IS_AUTHENTICATED_ANONYMOUSLY', '1');
    INSERT INTO `core_menu_item` (`itm_id`, `itm_parent`, `mnu_menu`, `itm_name`, `itm_route`, `itm_route_parameters`, `itm_route_absolute`, `itm_uri`, `itm_icon`, `itm_display`, `itm_display_children`, `itm_role`, `itm_order`) VALUES ('255', '253', '1', 'Ajouter un groupe', 'hopitalnumerique_communautepratique_admin_groupe_add', NULL, '0', NULL, NULL, '0', '0', 'IS_AUTHENTICATED_ANONYMOUSLY', '1');
/* --> */


/* Article */
INSERT INTO `hn_objet` (`obj_id`, `obj_locked_by`, `ref_statut`, `obj_titre`, `obj_alias`, `obj_synthese`, `obj_resume`, `obj_path`, `obj_commentaires`, `obj_notes`, `obj_date_creation`, `obj_date_debut_publication`, `obj_date_fin_publication`, `obj_date_modification`, `obj_lock`, `obj_isInfraDoc`, `obj_path2`, `obj_isArticle`, `obj_vignette`, `obj_nb_vue`, `obj_autodiag`, `obj_referencement`, `obj_objets`, `obj_glossaires`, `obj_date_debut_parution`, `ofm_id`, `obj_alaune`, `obj_publication_plus_consulte`, `obj_btn_sociaux`, `ref_cible_diffusion`) VALUES (1000, 1, 3, 'La communauté de pratiques', 'la-communaute-de-pratiques', NULL, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. Proin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. Duis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. Ut in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit.<br /><br />Ut velit mauris, egestas sed, gravida nec, ornare ut, mi. Aenean ut orci vel massa suscipit pulvinar. Nulla sollicitudin. Fusce varius, ligula non tempus aliquam, nunc turpis ullamcorper nibh, in tempus sapien eros vitae ligula. Pellentesque rhoncus nunc et augue. Integer id felis. Curabitur aliquet pellentesque diam. Integer quis metus vitae elit lobortis egestas. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi vel erat non mauris convallis vehicula. Nulla et sapien. Integer tortor tellus, aliquam faucibus, convallis id, congue eu, quam. Mauris ullamcorper felis vitae erat. Proin feugiat, augue non elementum posuere, metus purus iaculis lectus, et tristique ligula justo vitae magna.</p>', NULL, 1, 1, '2015-11-13 00:00:00', NULL, NULL, NULL, 1, 0, NULL, 1, NULL, 0, 'a:0:{}', 'a:0:{}', 'a:0:{}', 'a:1:{i:0;s:6:"risque";}', NULL, NULL, 0, 0, 1, NULL);
INSERT INTO `hn_objet_type` (`obj_id`, `ref_id`) VALUES (1000, 185);
INSERT INTO `core_menu_item` (`itm_id`, `itm_parent`, `mnu_menu`, `itm_name`, `itm_route`, `itm_route_parameters`, `itm_route_absolute`, `itm_uri`, `itm_icon`, `itm_display`, `itm_display_children`, `itm_role`, `itm_order`) VALUES (NULL, '65', '3', 'La communauté de pratiques', 'hopital_numerique_publication_publication_article', '{"categorie":"article","id":"1000","alias":"la-communaute-de-pratiques"}', NULL, NULL, NULL, '1', '0', 'IS_AUTHENTICATED_ANONYMOUSLY', '6');

INSERT INTO `hn_reference` (`ref_id`, `parent_id`, `ref_libelle`, `ref_code`, `ref_etat`, `ref_dictionnaire`, `ref_recherche`, `ref_lock`, `ref_order`) VALUES (623, NULL, 'Communauté de pratiques', 'CATEGORIE_ARTICLE', '3', '0', '0', '0', '100')
INSERT INTO `hn_reference` (`ref_id`, `parent_id`, `ref_libelle`, `ref_code`, `ref_etat`, `ref_dictionnaire`, `ref_recherche`, `ref_lock`, `ref_order`) VALUES ('624', '623', 'Divers', 'CATEGORIE_ARTICLE', '3', '0', '0', '0', '101');

/* Article test */
INSERT INTO `hn_objet` (`obj_id`, `obj_locked_by`, `ref_statut`, `obj_titre`, `obj_alias`, `obj_synthese`, `obj_resume`, `obj_path`, `obj_commentaires`, `obj_notes`, `obj_date_creation`, `obj_date_debut_publication`, `obj_date_fin_publication`, `obj_date_modification`, `obj_lock`, `obj_isInfraDoc`, `obj_path2`, `obj_isArticle`, `obj_vignette`, `obj_nb_vue`, `obj_autodiag`, `obj_referencement`, `obj_objets`, `obj_glossaires`, `obj_date_debut_parution`, `ofm_id`, `obj_alaune`, `obj_publication_plus_consulte`, `obj_btn_sociaux`, `ref_cible_diffusion`, `obj_source`) VALUES (1001, 1, 3, 'Lorem ipsum daolor sit amet', 'lorem-ipsum-daolor-sit-amet', NULL, '<p style="font-size: 13px;"><span style="font-family: ''ArialMT'', ''Arial''; font-weight: 400; font-size: 13px;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus mollis orci, sed rhoncus sapien nunc eget odio.</span></p>\r\n<p style="font-size: 13px;"><span style="font-family: ''ArialMT'', ''Arial''; font-weight: 400; font-size: 13px;"> </span></p>\r\n<p style="font-size: 13px;"><span style="font-family: ''ArialMT'', ''Arial''; font-weight: 400; font-size: 13px;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus mollis orci, sed rhoncus sapien nunc eget odio.</span></p>', NULL, 1, 1, '2015-12-08 00:00:00', NULL, NULL, NULL, 1, 0, NULL, 1, NULL, 0, 'a:0:{}', 'a:0:{}', 'a:0:{}', 'a:0:{}', NULL, NULL, 0, 0, 1, NULL, NULL);
INSERT INTO `core_menu_item` (`itm_id`, `itm_parent`, `mnu_menu`, `itm_name`, `itm_route`, `itm_route_parameters`, `itm_route_absolute`, `itm_uri`, `itm_icon`, `itm_display`, `itm_display_children`, `itm_role`, `itm_order`) VALUES (259, 257, 3, 'Lorem ipsum daolor sit amet', 'hopital_numerique_publication_publication_article', '{"categorie":"article","id":"1001","alias":"lorem-ipsum-daolor-sit-amet"}', NULL, NULL, NULL, 1, 0, 'IS_AUTHENTICATED_ANONYMOUSLY', 1);


/* User.inscritCommunautePratique */
ALTER TABLE core_user ADD usr_inscrit_communaute_pratique TINYINT(1) DEFAULT '0' NOT NULL COMMENT 'Indique si l utilisateur est inscrit à la communauté de pratiques';
