parameters:
    nodevo_gestionnaire_media.moxie_manager.extensions_autorisees: jpg,jpeg,png,gif,html,htm,txt,docx,doc,zip,pdf
    nodevo_gestionnaire_media.moxie_manager.media.dossiers:
        - /medias
    nodevo_gestionnaire_media.moxie_manager.langue.defaut: fr
    nodevo_gestionnaire_media.moxie_manager.langue.langues_disponibles:
        - fr
        - en
