imports:
    - { resource: moxie_manager.yml }

parameters:
    nodevo_gestionnaire_media.service.moxie_manager.class: Nodevo\GestionnaireMediaBundle\DependencyInjection\MoxieManager

services:
    nodevo_gestionnaire_media.service.moxie_manager:
        class: "%nodevo_gestionnaire_media.service.moxie_manager.class%"
        arguments: ["@service_container"]
