services:
    hopitalnumerique_account.doctrine.reference.contexte:
        class: 'HopitalNumerique\AccountBundle\Doctrine\Reference\Contexte'
        arguments: ['@session', '@hopitalnumerique_user.dependency_injection.connected_user', '@hopitalnumerique_reference.manager.reference', '@hopitalnumerique_user.manager.user']
