services:
    hopitalnumerique_account.dependency_injection.doctrine.reference.contexte:
        class: 'HopitalNumerique\AccountBundle\Doctrine\Reference\Contexte'
        arguments: ['@hopitalnumerique_user.dependency_injection.connected_user']
