#Admin
hopitalnumerique_glossaire_glossaire:
    pattern:  /admin/glossaire
    defaults: { _controller: "HopitalNumeriqueGlossaireBundle:Glossaire:index" }
    requirements: 
        _method: GET|POST

hopitalnumerique_glossaire_glossaire_parse:
    pattern:  /admin/glossaire/parse-publications
    defaults: { _controller: "HopitalNumeriqueGlossaireBundle:Glossaire:parsePublications" }
    requirements: 
        _method: GET|POST