<?php

namespace HopitalNumerique\RechercheParcoursBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RechercheParcoursDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RechercheParcoursDetailsRepository extends EntityRepository
{
    /**
     * Compte le nombre de chapitres lié à loutil
     *
     * @param Outil $outil Outil
     *
     * @return QueryBuilder
     */
    public function countDetails()
    {
        return $this->_em->createQueryBuilder()
                         ->select('count(details)')
                         ->from('\HopitalNumerique\RechercheParcoursBundle\Entity\RechercheParcoursDetails', 'details');
    }
}
