#Front - Module  
hopitalnumerique_module_module_front:
    pattern: /index
    defaults: { _controller: HopitalNumeriqueModuleBundle:Front/ModuleFront:index}

hopitalnumerique_module_module_show_front:
    pattern: /show/{id}
    defaults: { _controller: HopitalNumeriqueModuleBundle:Front/ModuleFront:show, id: 1 }
    requirements:
        id: \d+

#Front - Session
hopitalnumerique_module_session_description_front:
    pattern:  /session/description/{id}
    defaults: { _controller: HopitalNumeriqueModuleBundle:Front/SessionFront:description, id: 1  }
    requirements:
        id: \d+

hopitalnumerique_module_session_informations_front:
    pattern:  /session/informations/{id}
    defaults: { _controller: HopitalNumeriqueModuleBundle:Front/SessionFront:information, id: 1  }
    requirements:
        id: \d+

#Front - Inscription
hopitalnumerique_module_inscription_add_front:
    pattern:  /inscription/add/{id}
    defaults: { _controller: HopitalNumeriqueModuleBundle:Front/InscriptionFront:add, id: 1 }
    requirements:
        id: \d+

#Front - Evaluation
hopitalnumerique_module_evaluation_form_front:
    pattern:  /evaluation/{id}
    defaults: { _controller: HopitalNumeriqueModuleBundle:Front/EvaluationFront:formulaire, id: 1 }
    requirements:
        id: \d+

hopitalnumerique_module_evaluation_view_front:
    pattern:  /evaluation/view/{id}
    defaults: { _controller: HopitalNumeriqueModuleBundle:Front/EvaluationFront:formulaireVisualisation, id: 1 }
    requirements:
        id: \d+

