#Front - Inscription
hopitalnumerique_module_inscription_index_front:
    path:  /module-thematiques
    defaults: { _controller: HopitalNumeriqueModuleBundle:Front/InscriptionFront:index}

hopitalnumerique_module_inscription_attestation_front:
    path:  /module-thematiques/{id}/attestation
    defaults: { _controller: HopitalNumeriqueModuleBundle:Front/InscriptionFront:attestation, id: 1}
    requirements:
        id: \d+

hopitalnumerique_module_inscription_export_liste_front:
    path:  /module-thematiques/{id}/export-liste-participant
    defaults: { _controller: HopitalNumeriqueModuleBundle:Front/InscriptionFront:exportListeParticipant, id: 1}
    requirements:
        id: \d+

hopitalnumerique_module_inscription_annulation_inscription_front:
    path:  /module-thematiques/annulation-inscription/{id}/{json}
    defaults: { _controller: HopitalNumeriqueModuleBundle:Front/InscriptionFront:annulationInscription, id: 1, json: true}
    requirements:
        id: \d+

hopitalnumerique_module_session_evaluation_front:
    path:  /module-thematiques/session/{id}/evaluations
    defaults: { _controller: HopitalNumeriqueModuleBundle:Front/SessionFront:evaluation, id: 1}
    requirements:
        id: \d+

hopitalnumerique_module_session_formateur_front:
    path:  /module-thematiques/session/{id}/formateur
    defaults: { _controller: HopitalNumeriqueModuleBundle:Front/SessionFront:exportCommentaireCSV, id: 1}
    requirements:
        id: \d+

hopitalnumerique_module_session_formateur_session_front:
    path:  /module-thematiques/session/{id}/session
    defaults: { _controller: HopitalNumeriqueModuleBundle:Front/SessionFront:exportCommentaireCSVBySession, id: 1}
    requirements:
        id: \d+
