#Factures
hopitalnumerique_paiement_facture:
    path:  /admin/facture
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Facture:index" }

hopitalnumerique_paiement_facture_detail:
    path:  /admin/facture/detail/{id}
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Facture:detail", id:1 }
    requirements:
        id: \d+

hopitalnumerique_paiement_facture_paye:
    path:  /admin/facture/paye/{id}
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Facture:paye"}
    requirements: 
        id : \d+

hopitalnumerique_paiement_facture_cancel:
    path:  /admin/facture/cancel/{id}
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Facture:cancel" }
    requirements: 
        id: \d+

hopitalnumerique_paiement_change_etat:
    path:  /admin/facture/annulation/{id}
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Facture:etat" }
    requirements:
        id: \d+

hopitalnumerique_paiement_facture_total:
    path:  /admin/facture/total/{id}
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Facture:total" }
    requirements:
        id: \d+

hopitalnumerique_paiement_facture_export:
    path:  /admin/facture/export/{id}
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Facture:export" }
    requirements:
        id: \d+

hopitalnumerique_paiement_facture_regenerate:
    path:  /admin/facture/regenerate/{id}
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Facture:regenerate" }
    requirements:
        id: \d+

#Config
hopitalnumerique_paiement_config:
    path:  /admin/facture/config
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Config:index" }

hopitalnumerique_paiement_config_save:
    path:  /admin/facture/config/save
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Config:save" }
    requirements:
        _method:  POST

#Front
hopitalnumerique_paiement_front:
    path:  /mon-compte/suivi-des-paiements
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Front:suivi" }

hopitalnumerique_paiement_front_save:
    path:  /mon-compte/suivi-des-paiements/save
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Front:createFacture" }

hopitalnumerique_paiement_front_export:
    path:  /mon-compte/suivi-des-paiements/export/{id}
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Front:export" }
    requirements:
        id: \d+