hopitalnumerique_paiement_facture:
    pattern:  /admin/facture
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Facture:index" }

hopitalnumerique_paiement_facture_edit:
    pattern:  /admin/facture/edit/{id}
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Facture:edit" }
    requirements:
        id: \d+

hopitalnumerique_paiement_facture_delete:
    pattern:  /admin/facture/delete/{id}.{_format}
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Facture:delete", _format: json }
    requirements: 
        id: \d+


hopitalnumerique_paiement_config:
    pattern:  /admin/facture/config
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Config:index" }

hopitalnumerique_paiement_config_save:
    pattern:  /admin/facture/config/save
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Config:save" }
    requirements:
        _method:  POST



hopitalnumerique_paiement_front:
    pattern:  /compte-hn/suivi-des-paiements
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Front:suivi" }

hopitalnumerique_paiement_front_save:
    pattern:  /compte-hn/suivi-des-paiements/save
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Front:createFacture" }

hopitalnumerique_paiement_front_export:
    pattern:  /compte-hn/suivi-des-paiements/export/{id}
    defaults: { _controller: "HopitalNumeriquePaiementBundle:Front:export" }
    requirements:
        id: \d+