parameters:
    #Options
    hopital_numerique_paiement.options:parameters:
    #Facture
    hopitalnumerique_paiement.manager.facture.class: HopitalNumerique\PaiementBundle\Manager\FactureManager
    hopitalnumerique_paiement.grid.facture.class: HopitalNumerique\PaiementBundle\Grid\FactureGrid
    #Remboursement
    hopitalnumerique_paiement.manager.remboursement.class: HopitalNumerique\PaiementBundle\Manager\RemboursementManager
services:
    #Facture
    hopitalnumerique_paiement.manager.facture:
        class: %hopitalnumerique_paiement.manager.facture.class%
        arguments: 
            - "@doctrine.orm.entity_manager"
            - [ "@hopitalnumerique_intervention.manager.intervention_demande", "@hopitalnumerique_reference.manager.reference", "@hopitalnumerique_module.manager.inscription"]
        calls:
           - [ setCache, ["@liip_doctrine_cache.ns.main"] ]

    hopitalnumerique_paiement.grid.facture:
        class: %hopitalnumerique_paiement.grid.facture.class%
        arguments: ["@service_container"]

    #Remboursement
    hopitalnumerique_paiement.manager.remboursement:
        class: %hopitalnumerique_paiement.manager.remboursement.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
           - [ setCache, ["@liip_doctrine_cache.ns.main"] ]