hopital_numerique_intervention_admin_liste:
    pattern:  /demandes/liste
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Admin/Demande:liste" }

hopital_numerique_intervention_admin_demande_edit:
    pattern:  /demande/edit/{id}
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Admin/Form/Demande:edit", id: 0 }
    requirements:
        id: \d+

hopital_numerique_intervention_admin_evaluation_voir:
    pattern:  /demande/{interventionDemande}/evaluation/voir
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Admin/Evaluation:voir", interventionDemande: 0 }
    requirements:
        interventionDemande: \d+