hopital_numerique_intervention_demande_cron:
    pattern:  /cron/{id}
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Demande:cron" }

hopital_numerique_intervention_demande_cron_quotidien:
    pattern:  /cron-quotidien/{id}
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Demande:cronQuotidien" }