hopital_numerique_intervention_etablissement_etablissements:
    pattern:  /etablissements/json
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Etablissement:jsonEtablissements" }
    requirements:
        _method:  GET|POST
        _format: json