hopital_numerique_intervention_regroupement_regroupe:
    pattern:  /demande/{interventionDemandePrincipale}/regroupement/{interventionRegroupementType}/{interventionDemandeRegroupee}/regroupe
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Regroupement:ajaxRegroupe" }
    requirements:
        _method: POST
        interventionDemandePrincipale: \d+
        interventionRegroupementType: \d+
        interventionDemandeRegroupee: \d+
