hopital_numerique_intervention_reference_departements:
    pattern:  /departements/json
    defaults: { _controller: "HopitalNumeriqueInterventionBundle:Reference:jsonDepartements" }
    requirements:
        _format:  json
