hopital_numerique_recherche_parcours_homepage:
    pattern:  /admin/recherche-par-parcours/{id}
    defaults: { _controller: HopitalNumeriqueRechercheParcoursBundle:RechercheParcours:index, id: 1 }
    requirements: 
        id : \d+

hopital_numerique_recherche_parcours_reorder:
    pattern:  /admin/recherche-par-parcours/reorder
    defaults: { _controller: HopitalNumeriqueRechercheParcoursBundle:RechercheParcours:reorder }

hopital_numerique_recherche_parcours_edit:
    pattern: '/admin/recherche-par-parcours/edit/{rechercheParcours}'
    defaults: { _controller: 'HopitalNumeriqueRechercheParcoursBundle:RechercheParcours:edit' }
    methods: 'GET'
    requirements:
        rechercheParcours: '\d+'

hopital_numerique_recherche_parcours_save:
    pattern: '/admin/recherche-par-parcours/save/{rechercheParcours}'
    defaults: { _controller: 'HopitalNumeriqueRechercheParcoursBundle:RechercheParcours:save' }
    methods: 'POST'
    requirements:
        rechercheParcours: '\d+'

#Recherche par parcours - détails
hopital_numerique_recherche_parcours_details_index:
    pattern:  /admin/recherche-par-parcours/{id}/details
    defaults: { _controller: "HopitalNumeriqueRechercheParcoursBundle:RechercheParcoursDetails:index", id: 1 }
    requirements: 
        id : \d+

hopital_numerique_recherche_parcours_details_add:
    pattern:  /admin/recherche-par-parcours/{id}/details/add
    defaults: { _controller: "HopitalNumeriqueRechercheParcoursBundle:RechercheParcoursDetails:add", id: 1}
    requirements: 
        id : \d+

hopital_numerique_recherche_parcours_details_delete:
    pattern:  /admin/recherche-par-parcours/details/delete/{id}.{_format}
    defaults: { _controller: "HopitalNumeriqueRechercheParcoursBundle:RechercheParcoursDetails:delete", _format: json, id: 1 }
    requirements: 
        id: \d+
        _method: POST|DELETE

hopital_numerique_recherche_parcours_details_edit:
    pattern:  /admin/recherche-par-parcours/details/edit/{id}.{_format}
    defaults: { _controller: "HopitalNumeriqueRechercheParcoursBundle:RechercheParcoursDetails:editFancy",  _format: json, id: 1 }
    requirements: 
        id : \d+

hopital_numerique_recherche_parcours_details_save:
    pattern:  /admin/recherche-par-parcours/details/save/{id}.{_format}
    defaults: { _controller: "HopitalNumeriqueRechercheParcoursBundle:RechercheParcoursDetails:editSave", _format: json, id: 1 }
    requirements:
        id: \d+

hopital_numerique_recherche_parcours_details_reorder:
    pattern:  /admin/recherche-par-parcours/details/reorder
    defaults: { _controller: "HopitalNumeriqueRechercheParcoursBundle:RechercheParcoursDetails:reorder" }


hopitalnumerique_rechercheparcours_admin_recherche-par-parcours_gestion:
    pattern:  /admin/recherche-par-parcours/gestion
    defaults: { _controller: "HopitalNumeriqueRechercheParcoursBundle:RechercheParcoursGestion:index" }
    requirements: 
        _method: GET|POST

hopitalnumerique_rechercheparcours_admin_recherche-par-parcours_gestion_add:
    pattern:  /admin/recherche-par-parcours/gestion/add
    defaults: { _controller: "HopitalNumeriqueRechercheParcoursBundle:RechercheParcoursGestion:add" }
    requirements: 
        _method: GET|POST

hopitalnumerique_rechercheparcours_admin_recherche-par-parcours_gestion_show:
    pattern:  /admin/recherche-par-parcours/gestion/show/{id}
    defaults: { _controller: "HopitalNumeriqueRechercheParcoursBundle:RechercheParcoursGestion:show" }
    requirements:
        id: \d+
        _method: GET

hopitalnumerique_rechercheparcours_admin_recherche-par-parcours_gestion_edit:
    pattern:  /admin/recherche-par-parcours/gestion/edit/{id}
    defaults: { _controller: "HopitalNumeriqueRechercheParcoursBundle:RechercheParcoursGestion:edit" }
    requirements:
        id: \d+
        _method: GET|POST

hopitalnumerique_rechercheparcours_admin_recherche-par-parcours_gestion_delete:
    pattern:  /admin/recherche-par-parcours/gestion/delete/{id}.{_format}
    defaults: { _controller: "HopitalNumeriqueRechercheParcoursBundle:RechercheParcoursGestion:delete", _format: json }
    requirements: 
        id: \d+
        _method: POST|DELETE

#----------------------------------------------------------------------
#-----------------------------------FRONT------------------------------
#----------------------------------------------------------------------
hopital_numerique_recherche_parcours_homepage_front:
    pattern:  /recherche-par-parcours/{id}
    defaults: { _controller: HopitalNumeriqueRechercheParcoursBundle:RechercheParcours:indexFront }


#Recherche par parcours - détails
hopital_numerique_recherche_parcours_details_index_front:
    pattern:  /recherche-par-parcours/details/{id}-{alias}/{idEtape}-{etape}/{idRefEtapeChild}-{libRefEtapeChild}
    defaults: { _controller: "HopitalNumeriqueRechercheParcoursBundle:RechercheParcoursDetails:indexFront", id: 1 , idEtape: 0,alias: 'recherche-parcours',etape: '', idRefEtapeChild: null, libRefEtapeChild:'' }
    requirements:
        id : \d+
        idEtape : \d+
        idRefEtapeChild : \d*

#sauvegarde des notes
hopital_numerique_recherche_parcours_details_save_note_front:
    pattern:  /recherche-par-parcours/details/saveNote.{_format}
    defaults: { _controller: "HopitalNumeriqueRechercheParcoursBundle:MaitriseUser:saveNote", _format: json}
#sauvegarde du non concerné
hopital_numerique_recherche_parcours_details_save_non_concerne_front:
    pattern:  /recherche-par-parcours/details/saveNonConcerne.{_format}
    defaults: { _controller: "HopitalNumeriqueRechercheParcoursBundle:MaitriseUser:saveNonConcerne", _format: json}
