hopital_numerique_recherche_parcours_homepage:
    pattern:  /admin/recherche-par-parcours
    defaults: { _controller: HopitalNumeriqueRechercheParcoursBundle:RechercheParcours:index }

#Recherche par parcours - détails
hopital_numerique_recherche_parcours_details_index:
    pattern:  /admin/recherche-par-parcours/{id}/details
    defaults: { _controller: "HopitalNumeriqueRechercheParcoursBundle:RechercheParcoursDetails:index" }
    requirements: 
        id : \d+

hopital_numerique_recherche_parcours_details_add:
    pattern:  /admin/recherche-par-parcours/{id}/details/add
    defaults: { _controller: "HopitalNumeriqueRechercheParcoursBundle:RechercheParcoursDetails:add" }
    requirements: 
        id : \d+

hopital_numerique_recherche_parcours_details_delete:
    pattern:  /admin/recherche-par-parcours/details/delete/{id}.{_format}
    defaults: { _controller: "HopitalNumeriqueRechercheParcoursBundle:RechercheParcoursDetails:delete", _format: json }
    requirements: 
        id: \d+
        _method: POST|DELETE

hopital_numerique_recherche_parcours_details_edit:
    pattern:  /admin/recherche-par-parcours/details/edit/{id}.{_format}
    defaults: { _controller: "HopitalNumeriqueRechercheParcoursBundle:RechercheParcoursDetails:edit",  _format: json }
    requirements: 
        id : \d+

hopital_numerique_recherche_parcours_details_reorder:
    pattern:  /admin/recherche-par-parcours/{id}/details/reorder
    defaults: { _controller: "HopitalNumeriqueRechercheParcoursBundle:RechercheParcoursDetails:reorder" }
    requirements: 
        id : \d+