services:
    autodiag.entry_listener:
        class: HopitalNumerique\AutodiagBundle\EventListener\EntryListener
        arguments:
            - '@autodiag.repository.container'
            - '@autodiag.score_calculator'
        tags:
            - { name: kernel.event_listener, event: entry.updated, method: onEntryUpdated }

    account.security_listener:
            class: HopitalNumerique\AutodiagBundle\EventListener\SecurityListener
            arguments:
                - '@security.token_storage'
                - '@autodiag.entry.session'
                - '@doctrine'
            tags:
                - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
