imports:
    - { resource: attribute/builder.yml }
    - { resource: import.yml }

services:
    autodiag.form.model_preset:
        class: HopitalNumerique\AutodiagBundle\Form\Type\Autodiag\PresetType
        arguments: ['@autodiag.attribute_builder_provider']
        tags:
            - { name: form.type }
