imports:
    - { resource: attribute/builder.yml }
    - { resource: import.yml }

services:
    autodiag.form.model_preset:
        class: HopitalNumerique\AutodiagBundle\Form\Type\Autodiag\PresetType
        arguments: ['@autodiag.attribute_builder_provider']
        tags:
            - { name: form.type }

    autodiag.form.autodiag_update:
        class: HopitalNumerique\AutodiagBundle\Form\Type\Autodiag\AutodiagUpdateType
        arguments: ['@autodiag.attribute_builder_provider']
        tags:
            - { name: form.type }

    autodiag.history.reader:
        class: HopitalNumerique\AutodiagBundle\Service\Autodiag\HistoryReader
        arguments:
            - '@doctrine.orm.entity_manager'

    autodiag.import.handler:
        class: HopitalNumerique\AutodiagBundle\Model\AutodiagFileImportHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@session'
            - '@autodiag.attribute_builder_provider'
            - '@security.token_storage'
            - '@validator'

    autodiag.form.autodiagentry.value:
        class: HopitalNumerique\AutodiagBundle\Form\Type\AutodiagEntry\ValueType
        arguments: ['@autodiag.attribute_builder_provider']
        tags:
            - { name: form.type }

    autodiag.entry.session:
        class: HopitalNumerique\AutodiagBundle\Service\AutodiagEntrySession
        arguments:
            - '@autodiag.repository.autodiagentry'
            - '@session'

    autodiag.repository.autodiagentry:
        class: HopitalNumerique\AutodiagBundle\Repository\AutodiagEntryRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumeriqueAutodiagBundle:AutodiagEntry'

    autodiag.repository.restitution:
        class: HopitalNumerique\AutodiagBundle\Repository\RestitutionRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumeriqueAutodiagBundle:Restitution'

    autodiag.repository.synthesis:
        class: HopitalNumerique\AutodiagBundle\Repository\SynthesisRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumeriqueAutodiagBundle:Synthesis'

    autodiag.repository.autodiag:
        class: HopitalNumerique\AutodiagBundle\Repository\AutodiagRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumeriqueAutodiagBundle:Autodiag'

    autodiag.repository.weight:
        class: HopitalNumerique\AutodiagBundle\Repository\Autodiag\Attribute\WeightRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumeriqueAutodiagBundle:Autodiag\Attribute\Weight'

    autodiag.autodiagentry_voter:
        class: HopitalNumerique\AutodiagBundle\Security\AutodiagEntryVoter
        arguments: ['@autodiag.entry.session']
        tags:
            - { name: security.voter }
        public: false

    autodiag.synthesis_voter:
        class: HopitalNumerique\AutodiagBundle\Security\SynthesisVoter
        arguments: ['@autodiag.entry.session']
        tags:
            - { name: security.voter }
        public: false

    autodiag.twig_restitution_extension:
        class: HopitalNumerique\AutodiagBundle\Twig\RestitutionExtension
        public: false
        tags:
            - { name: twig.extension }

    autodiag.result.builder:
        class: HopitalNumerique\AutodiagBundle\Service\Result\ResultItemBuilder
        arguments:
            - '@autodiag.synthesis.completion'
            - '@autodiag.attribute_builder_provider'
            - '@autodiag.repository.weight'

    autodiag.restitution.calculator:
        class: HopitalNumerique\AutodiagBundle\Service\RestitutionCalculator
        arguments:
            - '@autodiag.algorithm.score'
            - '@autodiag.attribute_builder_provider'
            - '@autodiag.repository.autodiagentry'
            - '@autodiag.repository.restitution'
            - '@autodiag.synthesis.completion'

    autodiag.algorithm.score:
        class: HopitalNumerique\AutodiagBundle\Service\Algorithm\Score
        arguments: ['@doctrine.orm.entity_manager', '@autodiag.attribute_builder_provider']

    autodiag.synthesis.completion:
        class: HopitalNumerique\AutodiagBundle\Service\Synthesis\Completion
        arguments:
            - '@autodiag.attribute_builder_provider'

    autodiag.synthesis.dataformatter:
        class: HopitalNumerique\AutodiagBundle\Service\Synthesis\DataFormatter
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@autodiag.synthesis.completion'

    autodiag.synthesis.share:
        class: HopitalNumerique\AutodiagBundle\Service\Share
        arguments: ['@doctrine.orm.entity_manager']

    autodiag.synthesis.generator:
        class: HopitalNumerique\AutodiagBundle\Service\Synthesis\SynthesisGenerator

    autodiag.synthesis.remover:
        class: HopitalNumerique\AutodiagBundle\Service\Synthesis\SynthesisRemover
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@autodiag.repository.synthesis'

    autodiag.entries.grid:
        class: HopitalNumerique\AutodiagBundle\Grid\AutodiagEntryGrid
        arguments: ['@service_container']

    autodiag.entries.export:
        class: HopitalNumerique\AutodiagBundle\Service\Export\AutodiagEntriesExport
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@autodiag.result.builder'
            - '@autodiag.synthesis.completion'

    autodiag.restitution_item.export:
            class: HopitalNumerique\AutodiagBundle\Service\Export\RestitutionItemExport
            arguments:
                - '@autodiag.restitution.calculator'
