hopital_numerique_module_admin:
    resource: "@HopitalNumeriqueModuleBundle/Resources/config/routing/routing_admin.yml"
    prefix:   /admin

hopital_numerique_module_front:
    resource: "@HopitalNumeriqueModuleBundle/Resources/config/routing/routing_front.yml"
    prefix:   /module