imports:
    - { resource: repositories.yml}
    - { resource: services/events.yml}

parameters:
    #Options
    hopital_numerique_module.options:parameters:
    #Modules
    hopitalnumerique_module.manager.module.class: HopitalNumerique\ModuleBundle\Manager\ModuleManager
    hopitalnumerique_module.grid.module.class: HopitalNumerique\ModuleBundle\Grid\ModuleGrid
    hopitalnumerique_module.form.module.class: HopitalNumerique\ModuleBundle\Form\ModuleType
    #Sessions
    hopitalnumerique_module.manager.session.class: HopitalNumerique\ModuleBundle\Manager\SessionManager
    hopitalnumerique_module.grid.session.class: HopitalNumerique\ModuleBundle\Grid\SessionGrid
    hopitalnumerique_module.grid.allsession.class: HopitalNumerique\ModuleBundle\Grid\AllSessionGrid
    hopitalnumerique_module.form.session.class: HopitalNumerique\ModuleBundle\Form\SessionType
    #Inscriptions
    hopitalnumerique_module.manager.inscription.class: HopitalNumerique\ModuleBundle\Manager\InscriptionManager
    hopitalnumerique_module.grid.inscription.class: HopitalNumerique\ModuleBundle\Grid\InscriptionGrid
    hopitalnumerique_module.grid.allinscription.class: HopitalNumerique\ModuleBundle\Grid\AllInscriptionGrid
    hopitalnumerique_module.form.inscription.class: HopitalNumerique\ModuleBundle\Form\InscriptionType
    hopitalnumerique_module.form.addinscription.class: HopitalNumerique\ModuleBundle\Form\AddInscriptionType
    #CronLogger
    hopitalnumerique_module.service.logger.cronlogger.class: HopitalNumerique\ModuleBundle\DependencyInjection\Logger\CronLogger

services:
    #Modules
    #--Manager
    hopitalnumerique_module.manager.module:
        class: %hopitalnumerique_module.manager.module.class%
        arguments: ["@doctrine.orm.entity_manager", "@hopitalnumerique_user.manager.user"]

    #--Grid
    hopitalnumerique_module.grid.module:
        class: %hopitalnumerique_module.grid.module.class%
        arguments: ["@service_container"]

    #--Formulaire
    hopitalnumerique_module.form.module:
        class: %hopitalnumerique_module.form.module.class%
        arguments: ["@hopitalnumerique_module.manager.module", "@validator", "@hopitalnumerique_user.manager.user", "@hopitalnumerique_reference.manager.reference"]
        tags:
            - { name: form.type, alias: hopitalnumerique_module_module }

    #Sessions
    #--Manager
    hopitalnumerique_module.manager.session:
        class: %hopitalnumerique_module.manager.session.class%
        arguments: ["@doctrine.orm.entity_manager", "@hopitalnumerique_questionnaire.manager.reponse", "@hopitalnumerique_reference.manager.reference", "@hopitalnumerique_user.manager.user"]

    #--Grid
    #Sessions
    hopitalnumerique_module.grid.session:
        class: %hopitalnumerique_module.grid.session.class%
        arguments: ["@service_container"]
    #AllSessions
    hopitalnumerique_module.grid.allsession:
        class: %hopitalnumerique_module.grid.allsession.class%
        arguments: ["@service_container"]

    #--Formulaire
    hopitalnumerique_module.form.session:
        class: %hopitalnumerique_module.form.session.class%
        arguments: ["@hopitalnumerique_module.manager.session", "@validator", "@hopitalnumerique_reference.manager.reference"]
        tags:
            - { name: form.type, alias: hopitalnumerique_module_session }

    #Inscriptions
    #--Manager
    hopitalnumerique_module.manager.inscription:
        class: %hopitalnumerique_module.manager.inscription.class%
        arguments: ["@doctrine.orm.entity_manager", "@hopitalnumerique_user.manager.user", "@service_container"]

    #--Grid
    #Inscription
    hopitalnumerique_module.grid.inscription:
        class: %hopitalnumerique_module.grid.inscription.class%
        arguments: ["@service_container"]
    #AllInscription
    hopitalnumerique_module.grid.allinscription:
        class: %hopitalnumerique_module.grid.allinscription.class%
        arguments: ["@service_container"]

    #--Formulaire
    #Inscription FO
    hopitalnumerique_module.form.inscription:
        class: %hopitalnumerique_module.form.inscription.class%
        arguments: ["@hopitalnumerique_module.manager.inscription", "@validator"]
        tags:
            - { name: form.type, alias: hopitalnumerique_module_inscription }
    #Ajout en BO
    hopitalnumerique_module.form.addinscription:
        class: %hopitalnumerique_module.form.addinscription.class%
        arguments: ["@hopitalnumerique_module.manager.inscription", "@validator"]
        tags:
            - { name: form.type, alias: hopitalnumerique_module_addinscription }

    #Cronlogger
    hopitalnumerique_module.service.logger.cronlogger:
        class: "%hopitalnumerique_module.service.logger.cronlogger.class%"
        arguments: ["@logger", "@session"]

    hopitalnumerique_module.widget.session:
        class: HopitalNumerique\ModuleBundle\Service\Widget\SessionWidget
        tags:
            - { name: new_account.dashboard_widget, type: service, priority: 20 }
        arguments:
            - '@twig'
            - '@security.token_storage'
            - '@translator'
            - '@hopitalnumerique_module.service.registration_transformer'
            - '@hopitalnumerique_module.service.session_transformer'
            - '@hopitalnumerique_domaine.dependency_injection.current_domaine'
        public: false

    hopitalnumerique_module.widget.module_session:
        class: HopitalNumerique\ModuleBundle\Service\Widget\ModuleSessionWidget
        tags:
            - { name: new_account.dashboard_widget, type: dashboard }
        arguments:
            - '@twig'
            - '@security.token_storage'
            - '@translator'
            - '@hopitalnumerique_module.service.registration_transformer'
            - '@hopitalnumerique_module.service.session_transformer'
            - '@hopitalnumerique_domaine.dependency_injection.current_domaine'
        public: false

    hopitalnumerique_module.service.registration_transformer:
        class: HopitalNumerique\ModuleBundle\Service\Widget\DataProvider\RegistrationProvider
        arguments:
            - '@hn.module.repository.inscription'
            - '@security.token_storage'
            - '@nodevo_acl.manager.acl'
            - '@router'
            - '@translator'

    hopitalnumerique_module.service.session_transformer:
        class: HopitalNumerique\ModuleBundle\Service\Widget\DataProvider\SessionProvider
        arguments:
            - '@hn.module.repository.session'
            - '@security.token_storage'
            - '@nodevo_acl.manager.acl'
            - '@router'
            - '@translator'

    HopitalNumerique\ModuleBundle\Service\Notification\ComingTrainingSessionsNotificationProvider:
        class: HopitalNumerique\ModuleBundle\Service\Notification\ComingTrainingSessionsNotificationProvider
        arguments:
            - '@event_dispatcher'
            - '@security.token_storage'
            - '@translator'
            - '@hopitalnumerique_user.repository.user'
            - '@nodevo_acl.manager.acl'
            - '@nodevo_acl.manager.ressource'
        tags:
            - { name: notification.aggregator, key: coming_training_sessions }
        calls:
            - [setMailManager, ['@nodevo_mail.manager.mail']]

    HopitalNumerique\ModuleBundle\EventListener\ComingTrainingSessionsListener:
        class: HopitalNumerique\ModuleBundle\EventListener\ComingTrainingSessionsListener
        arguments: [ '@hopitalnumerique\notificationbundle\service\notifications' ]
        tags:
            - { name: kernel.event_subscriber, event: coming_training_sessions }
