imports:
    - { resource: "config/manager.yml" }
    - { resource: "config/form.yml" }
    - { resource: "config/grid.yml" }
    - { resource: "config/twig.yml" }

services:
    hopitalnumerique_communautepratique.dependency_injection.inscription:
        class: "HopitalNumerique\CommunautePratiqueBundle\DependencyInjection\Inscription"

    hopitalnumerique_communautepratique.dependency_injection.annuaire:
        class: "HopitalNumerique\CommunautePratiqueBundle\DependencyInjection\Annuaire"
        arguments: ['@session', '@hopitalnumerique_user.manager.user', '@hopitalnumerique_reference.manager.reference']

    hopitalnumerique_communautepratique.pagerfanta.view:
        class: Pagerfanta\View\OptionableView
        arguments:
            - @pagerfanta.view.twitter_bootstrap3
            - { proximity: 2, prev_message: '&laquo;', next_message: '&raquo;' }
        public: false
        tags: [{ name: pagerfanta.view, alias: hopitalnumerique_communautepratique }]
