imports:
    - { resource: "services/manager.yml" }
    - { resource: "services/form.yml" }
    - { resource: "services/grid.yml" }
    - { resource: "services/twig.yml" }
    - { resource: "services/handlers.yml" }

services:
    hopitalnumerique_communautepratique.dependency_injection.annuaire:
        class: HopitalNumerique\CommunautePratiqueBundle\DependencyInjection\Annuaire
        arguments: ['@session', '@hopitalnumerique_user.manager.user', '@hopitalnumerique_reference.manager.reference']

    hopitalnumerique_communautepratique.dependency_injection.commentaire:
        class: HopitalNumerique\CommunautePratiqueBundle\DependencyInjection\Commentaire
        arguments: ['@router', '@form.factory']

    hopitalnumerique_communautepratique.dependency_injection.inscription:
        class: HopitalNumerique\CommunautePratiqueBundle\DependencyInjection\Inscription
        arguments:
            - '@translator.default'

    hopitalnumerique_communautepratique.dependency_injection.security:
        class: HopitalNumerique\CommunautePratiqueBundle\DependencyInjection\Security
        arguments: ['@security.context']

    hopitalnumerique_communautepratique.pagerfanta.view:
        class: Pagerfanta\View\OptionableView
        arguments:
            - @pagerfanta.view.twitter_bootstrap3
            - { proximity: 2, prev_message: '&laquo;', next_message: '&raquo;' }
        public: false
        tags: [{ name: pagerfanta.view, alias: hopitalnumerique_communautepratique }]

    communautepratique_router:
        class: HopitalNumerique\CommunautePratiqueBundle\Service\Router
        arguments:
            - '@hopitalnumerique_domaine.dependency_injection.current_domaine'
            - '@router'

    hopitalnumerique_communautepratique.repository.commentaire:
        class: HopitalNumerique\CommunautePratiqueBundle\Repository\CommentaireRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumerique\CommunautePratiqueBundle\Entity\Commentaire'

    hopitalnumerique_communautepratique.repository.groupe:
        class: HopitalNumerique\CommunautePratiqueBundle\Repository\GroupeRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumerique\CommunautePratiqueBundle\Entity\Groupe'

    hopitalnumerique_communautepratique.repository.fiche:
        class: HopitalNumerique\CommunautePratiqueBundle\Repository\FicheRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumerique\CommunautePratiqueBundle\Entity\Fiche'

    hopitalnumerique_communautepratique.widgets.cdp_widget:
        class: HopitalNumerique\CommunautePratiqueBundle\Service\Widget\DashboardWidget
        tags:
            - { name: new_account.dashboard_widget, type: dashboard }
        arguments:
            - '@twig'
            - '@security.token_storage'
            - '@translator'
        calls:
            - [setRepositories, ['@hopitalnumerique_user.repository.user', '@hopitalnumerique_communautepratique.repository.groupe']]
        public: false

    hopitalnumerique_communautepratique.repository.group:
        class: HopitalNumerique\CommunautePratiqueBundle\Repository\GroupeRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumerique\CommunautePratiqueBundle\Entity\Groupe'

    HopitalNumerique\CommunautePratiqueBundle\Service\Export\Comment\Csv:
        class: HopitalNumerique\CommunautePratiqueBundle\Service\Export\Comment\Csv

    HopitalNumerique\CommunautePratiqueBundle\Service\SelectedDomainStorage:
        class: HopitalNumerique\CommunautePratiqueBundle\Service\SelectedDomainStorage
        arguments:
            - '@session'
            - '@hopitalnumerique_domaine.repository.domaine'
            - '@hopitalnumerique_domaine.dependency_injection.current_domaine'
            - '@HopitalNumerique\CommunautePratiqueBundle\Service\AvailableDomainsRetriever'

    HopitalNumerique\CommunautePratiqueBundle\Service\AvailableDomainsRetriever:
        class: HopitalNumerique\CommunautePratiqueBundle\Service\AvailableDomainsRetriever
        arguments:
            - '@hopitalnumerique_domaine.repository.domaine'
            - '@hopitalnumerique_domaine.dependency_injection.current_domaine'
            - '@security.authorization_checker'
            - '@security.token_storage'
