imports:
    - { resource: "services/manager.yml" }
    - { resource: "services/form.yml" }
    - { resource: "services/grid.yml" }
    - { resource: "services/twig.yml" }
    - { resource: "services/handlers.yml" }

services:
    hopitalnumerique_communautepratique.dependency_injection.annuaire:
        class: HopitalNumerique\CommunautePratiqueBundle\DependencyInjection\Annuaire
        arguments: ['@session', '@hopitalnumerique_user.manager.user', '@hopitalnumerique_reference.manager.reference']

    hopitalnumerique_communautepratique.dependency_injection.commentaire:
        class: HopitalNumerique\CommunautePratiqueBundle\DependencyInjection\Commentaire
        arguments: ['@router', '@form.factory']

    hopitalnumerique_communautepratique.dependency_injection.inscription:
        class: HopitalNumerique\CommunautePratiqueBundle\DependencyInjection\Inscription
        arguments:
            - '@translator.default'

    hopitalnumerique_communautepratique.dependency_injection.security:
        class: HopitalNumerique\CommunautePratiqueBundle\DependencyInjection\Security
        arguments: ['@security.context']

    hopitalnumerique_communautepratique.pagerfanta.view:
        class: Pagerfanta\View\OptionableView
        arguments:
            - @pagerfanta.view.twitter_bootstrap3
            - { proximity: 2, prev_message: '&laquo;', next_message: '&raquo;' }
        public: false
        tags: [{ name: pagerfanta.view, alias: hopitalnumerique_communautepratique }]

    communautepratique_router:
        class: HopitalNumerique\CommunautePratiqueBundle\Service\Router
        arguments:
            - '@hopitalnumerique_domaine.dependency_injection.current_domaine'
            - '@router'

    hopitalnumerique_communautepratique.repository.commentaire:
        class: HopitalNumerique\CommunautePratiqueBundle\Repository\CommentaireRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumerique\CommunautePratiqueBundle\Entity\Commentaire'

    hopitalnumerique_communautepratique.repository.groupe:
        class: HopitalNumerique\CommunautePratiqueBundle\Repository\GroupeRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumerique\CommunautePratiqueBundle\Entity\Groupe'

    hopitalnumerique_communautepratique.repository.fiche:
        class: HopitalNumerique\CommunautePratiqueBundle\Repository\FicheRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumerique\CommunautePratiqueBundle\Entity\Fiche'

    HopitalNumerique\CommunautePratiqueBundle\Repository\GroupeInscriptionRepository:
        class: HopitalNumerique\CommunautePratiqueBundle\Repository\GroupeInscriptionRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumerique\CommunautePratiqueBundle\Entity\Inscription'

    hopitalnumerique_communautepratique.widgets.cdp_widget:
        class: HopitalNumerique\CommunautePratiqueBundle\Service\Widget\DashboardWidget
        tags:
            - { name: new_account.dashboard_widget, type: dashboard }
        arguments:
            - '@twig'
            - '@security.token_storage'
            - '@translator'
        calls:
            - [setRepositories, ['@hopitalnumerique_user.repository.user', '@hopitalnumerique_communautepratique.repository.groupe']]
        public: false

    hopitalnumerique_communautepratique.repository.group:
        class: HopitalNumerique\CommunautePratiqueBundle\Repository\GroupeRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'HopitalNumerique\CommunautePratiqueBundle\Entity\Groupe'

    HopitalNumerique\CommunautePratiqueBundle\Service\Notification\PracticeCommunityNotificationProviderAbstract:
            class: HopitalNumerique\CommunautePratiqueBundle\Service\Notification\PracticeCommunityNotificationProviderAbstract
            abstract: true
            arguments:
                - '@event_dispatcher'
                - '@security.token_storage'
                - '@hopitalnumerique_publication.twig.publication_extension'
                - '@hopitalnumerique\communautepratiquebundle\repository\groupeinscriptionrepository'

    HopitalNumerique\CommunautePratiqueBundle\Service\Notification\GroupCommentCreatedNotificationProvider:
        class: HopitalNumerique\CommunautePratiqueBundle\Service\Notification\GroupCommentCreatedNotificationProvider
        parent: HopitalNumerique\CommunautePratiqueBundle\Service\Notification\PracticeCommunityNotificationProviderAbstract
        tags:
            - { name: notification.aggregator, key: practice_community_group_comment_created }

    HopitalNumerique\CommunautePratiqueBundle\Service\Notification\FormCommentCreatedNotificationProvider:
        class: HopitalNumerique\CommunautePratiqueBundle\Service\Notification\FormCommentCreatedNotificationProvider
        parent: HopitalNumerique\CommunautePratiqueBundle\Service\Notification\PracticeCommunityNotificationProviderAbstract
        tags:
            - { name: notification.aggregator, key: practice_community_form_comment_created }

    HopitalNumerique\CommunautePratiqueBundle\Service\Notification\GroupDocumentCreatedNotificationProvider:
        class: HopitalNumerique\CommunautePratiqueBundle\Service\Notification\GroupDocumentCreatedNotificationProvider
        parent: HopitalNumerique\CommunautePratiqueBundle\Service\Notification\PracticeCommunityNotificationProviderAbstract
        tags:
            - { name: notification.aggregator, key: practice_community_group_document_created }

    HopitalNumerique\CommunautePratiqueBundle\Service\Notification\GroupUserJoinedNotificationProvider:
        class: HopitalNumerique\CommunautePratiqueBundle\Service\Notification\GroupUserJoinedNotificationProvider
        parent: HopitalNumerique\CommunautePratiqueBundle\Service\Notification\PracticeCommunityNotificationProviderAbstract
        tags:
            - { name: notification.aggregator, key: practice_community_group_user_joined }

    HopitalNumerique\CommunautePratiqueBundle\Service\Notification\GroupCreatedNotificationProvider:
        class: HopitalNumerique\CommunautePratiqueBundle\Service\Notification\GroupCreatedNotificationProvider
        parent: HopitalNumerique\CommunautePratiqueBundle\Service\Notification\PracticeCommunityNotificationProviderAbstract
        tags:
            - { name: notification.aggregator, key: practice_community_group_created }

    HopitalNumerique\CommunautePratiqueBundle\Service\Notification\CommunityUserJoinedNotificationProvider:
        class: HopitalNumerique\CommunautePratiqueBundle\Service\Notification\CommunityUserJoinedNotificationProvider
        parent: HopitalNumerique\CommunautePratiqueBundle\Service\Notification\PracticeCommunityNotificationProviderAbstract
        tags:
            - { name: notification.aggregator, key: practice_community_user_joined }

    HopitalNumerique\CommunautePratiqueBundle\EventListener\GroupCommentCreatedListener:
        class: HopitalNumerique\CommunautePratiqueBundle\EventListener\GroupCommentCreatedListener
        arguments: [ '@hopitalnumerique\notificationbundle\service\notifications' ]
        tags:
            - { name: kernel.event_subscriber, event: communautepratique.group_comment_created }

    HopitalNumerique\CommunautePratiqueBundle\EventListener\FormCommentCreatedListener:
        class: HopitalNumerique\CommunautePratiqueBundle\EventListener\FormCommentCreatedListener
        arguments: [ '@hopitalnumerique\notificationbundle\service\notifications' ]
        tags:
            - { name: kernel.event_subscriber, event: communautepratique.group_comment_created }

    HopitalNumerique\CommunautePratiqueBundle\EventListener\GroupDocumentCreatedListener:
        class: HopitalNumerique\CommunautePratiqueBundle\EventListener\GroupDocumentCreatedListener
        arguments: [ '@hopitalnumerique\notificationbundle\service\notifications' ]
        tags:
            - { name: kernel.event_subscriber, event: communautepratique.group_document_created }

    HopitalNumerique\CommunautePratiqueBundle\EventListener\GroupUserJoinedListener:
        class: HopitalNumerique\CommunautePratiqueBundle\EventListener\GroupUserJoinedListener
        arguments: [ '@hopitalnumerique\notificationbundle\service\notifications' ]
        tags:
            - { name: kernel.event_subscriber, event: communautepratique.group_user_joined }

    HopitalNumerique\CommunautePratiqueBundle\EventListener\GroupCreatedListener:
        class: HopitalNumerique\CommunautePratiqueBundle\EventListener\GroupCreatedListener
        arguments: [ '@hopitalnumerique\notificationbundle\service\notifications' ]
        tags:
            - { name: kernel.event_subscriber, event: communautepratique.group_created }

    HopitalNumerique\CommunautePratiqueBundle\EventListener\CommunityUserJoinedListener:
        class: HopitalNumerique\CommunautePratiqueBundle\EventListener\CommunityUserJoinedListener
        arguments: [ '@hopitalnumerique\notificationbundle\service\notifications' ]
        tags:
            - { name: kernel.event_subscriber, event: communautepratique.enroll_user }
