hopital_numerique_admin_homepage:
    pattern:  /admin/
    defaults: { _controller: HopitalNumeriqueAdminBundle:Default:index }

hopital_numerique_admin_homepage_reorder:
    pattern:  /admin/reorder
    defaults: { _controller: HopitalNumeriqueAdminBundle:Default:reorder }
