hopital_numerique_admin_homepage:
    pattern:  /
    defaults: { _controller: HopitalNumeriqueAdminBundle:Default:index }

hopital_numerique_admin_homepage_histo:
    pattern:  /histo
    defaults: { _controller: HopitalNumeriqueAdminBundle:Default:histo }