hopital_numerique_admin_homepage:
    pattern:  /
    defaults: { _controller: HopitalNumeriqueAdminBundle:Default:index }

hopital_numerique_admin_homepage_reorder:
    pattern:  /reorder
    defaults: { _controller: HopitalNumeriqueAdminBundle:Default:reorder }
