services:
    hopitalnumerique_communautepratique.manager.commentaire:
        class: "HopitalNumerique\CommunautePratiqueBundle\Manager\CommentaireManager"
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@nodevo_mail.manager.mail'
            - '@event_dispatcher'

    hopitalnumerique_communautepratique.manager.document:
        class: "HopitalNumerique\CommunautePratiqueBundle\Manager\DocumentManager"
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@event_dispatcher'

    hopitalnumerique_communautepratique.manager.fiche:
        class: "HopitalNumerique\CommunautePratiqueBundle\Manager\FicheManager"
        arguments: ['@doctrine.orm.entity_manager']

    hopitalnumerique_communautepratique.manager.groupe:
        class: "HopitalNumerique\CommunautePratiqueBundle\Manager\GroupeManager"
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"

    hopitalnumerique_communautepratique.manager.groupe.inscription:
        class: "HopitalNumerique\CommunautePratiqueBundle\Manager\GroupeInscriptionManager"
        arguments: ["@doctrine.orm.entity_manager"]
