services:
    hopitalnumerique_communautepratique.twig.extension.filter:
        class: "HopitalNumerique\CommunautePratiqueBundle\Twig\Extension\FilterExtension"
        arguments: ['@hopitalnumerique_communautepratique.dependency_injection.inscription', '@hopitalnumerique_communautepratique.dependency_injection.security', '@communautepratique_router']
        tags:
            - { name: twig.extension }
