services:
    HopitalNumerique\CommunautePratiqueBundle\Security\Discussion\MessageVoter:
        class: HopitalNumerique\CommunautePratiqueBundle\Security\Discussion\MessageVoter
        tags:
            - { name: security.voter }
        public: false
