hopital_numerique_domaine_admin_domaine:
    resource: "@HopitalNumeriqueDomaineBundle/Resources/config/routing/domaine.yml"
    prefix:   /admin/domaine

#CRON
hopitalnumerique_domaine_cron:
    pattern:  /cron-domaine/{id}
    defaults: { _controller: HopitalNumeriqueDomaineBundle:Cron:generationDomaine}
