parameters:
    #Options
    hopital_numerique_domaine.options:parameters:
    hopitalnumerique_domaine.manager.domaine.class: HopitalNumerique\DomaineBundle\Manager\DomaineManager
    hopitalnumerique_domaine.grid.domaine.class: HopitalNumerique\DomaineBundle\Grid\DomaineGrid
    hopitalnumerique_domaine.form.domaine.class: HopitalNumerique\DomaineBundle\Form\DomaineType

services:
    hopitalnumerique_domaine.manager.domaine:
        class: %hopitalnumerique_domaine.manager.domaine.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
           - [ setCache, [ @liip_doctrine_cache.ns.main ] ]

    hopitalnumerique_domaine.grid.domaine:
        class: %hopitalnumerique_domaine.grid.domaine.class%
        arguments: ["@service_container"]

    hopitalnumerique_domaine.form.domaine:
        class: %hopitalnumerique_domaine.form.domaine.class%
        arguments: ["@hopitalnumerique_domaine.manager.domaine", "@validator"]
        tags:
            - { name: form.type, alias: hopitalnumerique_domaine_domaine }