nodevo_role_role:
    pattern:  /role/
    defaults: { _controller: "NodevoRoleBundle:Role:index" }
    requirements:
        _method: GET|POST

nodevo_role_add:
    pattern:  /role/add
    defaults: { _controller: "NodevoRoleBundle:Role:add" }
    requirements:
        _method: GET|POST

nodevo_role_show:
    pattern:  /role/show/{id}
    defaults: { _controller: "NodevoRoleBundle:Role:show", id:1 }
    requirements:
        id: \d+
        _method: GET

nodevo_role_edit:
    pattern:  /role/edit/{id}
    defaults: { _controller: "NodevoRoleBundle:Role:edit", id:1 }
    requirements:
        id: \d+
        _method: POST|GET

nodevo_role_delete:
    pattern:  /role/delete/{id}.{_format}
    defaults: { _controller: "NodevoRoleBundle:Role:delete", _format: json }
    requirements:
        idItem: \d+
        _method: POST|DELETE