<?php

namespace HopitalNumerique\QuestionnaireBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionnaireRepository extends EntityRepository
{    

    /**
     * Récupère les données du grid sous forme de tableau correctement formaté
     *
     * @return array
     * 
     * @author Gaetan MELCHILSEN
     * @copyright Nodevo
     */
    public function getDatasForGrid()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('questionnaire.id, questionnaire.nom, count(DISTINCT user.id) as nbUser')
            ->from('HopitalNumeriqueQuestionnaireBundle:Questionnaire', 'questionnaire')
            ->leftJoin('questionnaire.questions' , 'questions')
            ->leftJoin('questions.reponses', 'reponses')
            ->leftJoin('reponses.user', 'user')
            ->where('questionnaire.lock = :locked')
            ->setParameter('locked', false)
            ->orderBy('questionnaire.nom')
            ->groupBy('questionnaire.id');
        
        return $qb;
    }

    /**
     * Récupère les questions/réponses d'un questionnaire
     *
     * @return array
     */
    public function getQuestionsReponses( $idQuestionnaire, $idUser, $paramId )
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('questionnaire, question, reponse')
            ->from('\HopitalNumerique\QuestionnaireBundle\Entity\Question', 'question')
            ->innerJoin('question.questionnaire', 'questionnaire' ,'WITH' , 'questionnaire.id = :idQuestionnaire')
            ->setParameter('idQuestionnaire', $idQuestionnaire );
        
        if ($paramId != null)
        {
            $qb->leftJoin('question.reponses', 'reponse', 'WITH' , 'reponse.user = :idUser AND reponse.paramId = :paramId')
                ->setParameter('idUser', $idUser)
                ->setParameter('paramId', $paramId);
        }
        else
        {
            $qb->leftJoin('question.reponses', 'reponse', 'WITH' , 'reponse.user = :idUser ')
                ->setParameter('idUser', $idUser );
        }
        $qb->orderBy('question.ordre');

        return $qb->getQuery()->getResult();
    }
}
