<?php

namespace HopitalNumerique\QuestionnaireBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
    /**
     * Recupère toutes les questions du type passé en paramètre pour le questionnaire $idQuestionnaire
     * 
     * @param int    $idQuestionnaire
     * @param string $typeQuestion
     * 
     * @return array(\HopitalNumerique\QuestionnaireBundle\Entity\Questions) Tableau des questions de type $typeQuestion
     */
    public function getQuestionsByType( $idQuestionnaire, $typeQuestion )
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('question')
        ->from('\HopitalNumerique\QuestionnaireBundle\Entity\Question', 'question')
        ->innerJoin('question.questionnaire', 'questionnaire' ,'WITH' , 'questionnaire.id = :idQuestionnaire')
        ->setParameter('idQuestionnaire', $idQuestionnaire )
        ->innerJoin('question.typeQuestion', 'typeQuestion', 'WITH' , 'typeQuestion.libelle = :typeQuestion ')
        ->setParameter('typeQuestion', $typeQuestion )
        ->orderBy('question.ordre');
    
        return $qb->getQuery()->getResult();
    }
}
