imports:
    - { resource: 'services/manager.yml' }
    - { resource: 'services/form.yml' }

services:
    hopitalnumerique_reference.grid.reference:
        class: 'HopitalNumerique\ReferenceBundle\Grid\ReferenceGrid'
        arguments: ["@service_container"]

    hopitalnumerique.twig.ref_extension:
        class: HopitalNumerique\ReferenceBundle\Twig\ReferenceExtension
        arguments : ["@hopitalnumerique_reference.manager.reference"]
        tags:
            - { name: twig.extension }