imports:
    - { resource: 'services/manager.yml' }
    - { resource: 'services/form.yml' }
    - { resource: 'services/security.yml' }
    - { resource: 'services/twig.yml' }
    - { resource: 'services/repository.yml' }
    - { resource: 'services/command_handler.yml' }
    - { resource: 'services/event.yml' }

services:
    hopitalnumerique_reference.grid.reference:
        class: 'HopitalNumerique\ReferenceBundle\Grid\ReferenceGrid'
        arguments: ["@service_container"]

    hopitalnumerique_reference.dependency_injection.referencement:
        class: 'HopitalNumerique\ReferenceBundle\DependencyInjection\Referencement'
        arguments: ['@hopitalnumerique_reference.dependency_injection.reference.tree', '@hopitalnumerique_reference.manager.reference', '@hopitalnumerique_reference.manager.entity_has_reference']

    hopitalnumerique_reference.dependency_injection.reference.tree:
        class: 'HopitalNumerique\ReferenceBundle\DependencyInjection\Reference\Tree'
        arguments: ['@hopitalnumerique_reference.manager.reference']

    hopitalnumerique_reference.doctrine.glossaire.migration:
        class: 'HopitalNumerique\ReferenceBundle\Doctrine\Glossaire\Migration'
        arguments: ['@database_connection', '@hopitalnumerique_reference.manager.reference', '@hopitalnumerique_domaine.manager.domaine']

    hopitalnumerique_reference.doctrine.glossaire.parse:
        class: 'HopitalNumerique\ReferenceBundle\Doctrine\Glossaire\Parse'
        arguments:
            - '@hopitalnumerique_core.dependency_injection.entity'
            - '@hopitalnumerique_reference.manager.entity_has_glossaire'
            - '@hopitalnumerique_reference.manager.reference'
            - '@hopitalnumerique_domaine.manager.domaine'
            - '@hopitalnumerique_objet.manager.objet'
            - '@hopitalnumerique_objet.manager.contenu'
            - '@hopitalnumerique_domaine.dependency_injection.current_domaine'

    hopitalnumerique_reference.doctrine.glossaire.reader:
        class: 'HopitalNumerique\ReferenceBundle\Doctrine\Glossaire\Reader'
        arguments: ['@hopitalnumerique_core.dependency_injection.entity', '@hopitalnumerique_reference.manager.entity_has_glossaire', '@hopitalnumerique_reference.manager.reference']

    hopitalnumerique_reference.doctrine.reference.domaine_udpater:
        class: 'HopitalNumerique\ReferenceBundle\Doctrine\Reference\DomaineUpdater'

    hopitalnumerique_reference.doctrine.referencement_deleter:
        class: 'HopitalNumerique\ReferenceBundle\Doctrine\ReferencementDeleter'
        arguments: ['@hopitalnumerique_core.dependency_injection.entity', '@hopitalnumerique_reference.doctrine.referencement.note_deleter', '@hopitalnumerique_reference.manager.entity_has_reference']

    hopitalnumerique_reference.doctrine.referencement.deleter:
        class: 'HopitalNumerique\ReferenceBundle\Doctrine\Referencement\Deleter'
        arguments: ['@hopitalnumerique_core.dependency_injection.entity', '@hopitalnumerique_reference.doctrine.referencement.note_deleter', '@hopitalnumerique_reference.manager.entity_has_reference']

    hopitalnumerique_reference.doctrine.referencement.note_saver:
        class: 'HopitalNumerique\ReferenceBundle\Doctrine\Referencement\NoteSaver'
        arguments: ['@hopitalnumerique_reference.dependency_injection.referencement', '@hopitalnumerique_core.dependency_injection.entity', '@hopitalnumerique_reference.manager.entity_has_reference', '@hopitalnumerique_reference.manager.entity_has_note', '@hopitalnumerique_domaine.manager.domaine']

    hopitalnumerique_reference.doctrine.referencement.note_reader:
        class: 'HopitalNumerique\ReferenceBundle\Doctrine\Referencement\NoteReader'
        arguments: ['@hopitalnumerique_core.dependency_injection.entity', '@hopitalnumerique_reference.manager.entity_has_note']

    hopitalnumerique_reference.doctrine.referencement.note_deleter:
        class: 'HopitalNumerique\ReferenceBundle\Doctrine\Referencement\NoteDeleter'
        arguments: ['@hopitalnumerique_reference.manager.entity_has_note']

    hopitalnumerique_reference.doctrine.referencement.migration:
        class: 'HopitalNumerique\ReferenceBundle\Doctrine\Referencement\Migration'
        arguments: ['@doctrine', '@database_connection', '@hopitalnumerique_reference.manager.entity_has_reference']

    hopitalnumerique_reference.service.reference_switcher:
        class: 'HopitalNumerique\ReferenceBundle\Service\ReferenceSwitcher'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@hopitalnumerique_reference.repository.entity_has_reference'
            - '@stat.repository.search'
