nodevo_mail_mail:
    path:  /mail
    defaults: { _controller: "NodevoMailBundle:Mail:index" }
    requirements: 
        id: \d+

nodevo_mail_mail_add:
    path:  /mail/add
    defaults: { _controller: "NodevoMailBundle:Mail:add" }

nodevo_mail_mail_show:
    path:  /mail/show/{id}
    defaults: { _controller: "NodevoMailBundle:Mail:show", id:1 }
    requirements:
        id: \d+

nodevo_mail_mail_edit:
    path:  /mail/edit/{id}
    defaults: { _controller: "NodevoMailBundle:Mail:edit", id:1 }
    requirements:
        id: \d+

nodevo_mail_mail_delete:
    path:  /mail/delete/{id}.{_format}
    defaults: { _controller: "NodevoMailBundle:Mail:delete", _format: json }
    requirements: 
        id: \d+

nodevo_mail_mail_test:
    path:  /mail/sendTest/{id}
    defaults: { _controller: "NodevoMailBundle:Mail:sendTest", id:1 }
    requirements:
        id: \d+
