parameters:
    #Options
    nodevo_mail.options:

    nodevo_mail.manager.mail.class: Nodevo\MailBundle\Manager\MailManager
    nodevo_mail.grid.mail.class: Nodevo\MailBundle\Grid\MailGrid
    nodevo_mail.form.mail.class: Nodevo\MailBundle\Form\MailType

services:
    nodevo_mail.manager.mail:
        class: "%nodevo_mail.manager.mail.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@mailer"
            - "@twig"
            - "@router"
            - '@security.context'
            - "@request_stack"
            - "@session"
            - "@hopitalnumerique_domaine.manager.domaine"
            - "@hopitalnumerique_user.manager.user"
            - '@hopitalnumerique_reference.manager.reference'
            - '@hopitalnumerique_expert.manager.activiteexpert'
            - '@hopitalnumerique_expert.manager.courriel_registre'
            - "%nodevo_mail.options%"
            - "@ccdn_component_bb_code.component.bootstrap"

    nodevo_mail.grid.mail:
        class: %nodevo_mail.grid.mail.class%
        arguments: ["@service_container", "%nodevo_mail.options%"]

    nodevo_mail.form.mail:
        class: %nodevo_mail.form.mail.class%
        arguments: ["@nodevo_mail.manager.mail", "@validator"]
        tags:
            - { name: form.type, alias: nodevo_mail_mail }

    nodevo_mail.form.type.recommandation:
        class: 'Nodevo\MailBundle\Form\Type\RecommandationType'
        arguments: ['@router']
        tags:
            - { name: 'form.type' }

    nodevo_mail.subscriber.mail_log:
        class: Nodevo\MailBundle\EventListener\RecommendationMailSendedSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: 'kernel.event_subscriber' }

    Nodevo\MailBundle\EventListener\GroupNotificationSendSubscriber:
        class: Nodevo\MailBundle\EventListener\GroupNotificationSendSubscriber
        arguments:
            - '@nodevo_mail.manager.mail'
            - '@hopitalnumerique\notificationbundle\service\notifications'
        tags:
            - { name: kernel.event_subscriber, event: SEND_NOTIFICATION_GROUP }

    nodevo_mail.repository.recommendation_mail_log:
        class: Nodevo\MailBundle\Repository\RecommendationMailLogRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - 'Nodevo\MailBundle\Entity\RecommendationMailLog'
