parameters:
    #Options
    nodevo_mail.options:

    nodevo_mail.manager.mail.class: Nodevo\MailBundle\Manager\MailManager
    nodevo_mail.grid.mail.class: Nodevo\MailBundle\Grid\MailGrid
    nodevo_mail.form.mail.class: Nodevo\MailBundle\Form\MailType

services:
    nodevo_mail.manager.mail:
        class: "%nodevo_mail.manager.mail.class%"
        arguments: ["@doctrine.orm.entity_manager", "@mailer", "@twig", "@router", "@request_stack", "@session", "@hopitalnumerique_domaine.manager.domaine", "%nodevo_mail.options%"]
        calls:
           - [ setCache, [ "@liip_doctrine_cache.ns.main" ] ]

    nodevo_mail.grid.mail:
        class: %nodevo_mail.grid.mail.class%
        arguments: ["@service_container", "%nodevo_mail.options%"]

    nodevo_mail.form.mail:
        class: %nodevo_mail.form.mail.class%
        arguments: ["@nodevo_mail.manager.mail", "@validator"]
        tags:
            - { name: form.type, alias: nodevo_mail_mail }