# CCDNForum\ForumBundle\Entity\Post:
HopitalNumerique\ForumBundle\Entity\Post:
    type: entity
    repositoryClass: HopitalNumerique\ForumBundle\Repository\PostRepository
    table: hn_forum_post
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        body:
            type: text
        createdDate:
            type: datetime
            column: created_date
        editedDate:
            type: datetime
            column: edited_date
            nullable: true
        isDeleted:
            type: boolean
            column: is_deleted
            nullable: false
        deletedDate:
            type: datetime
            column: deleted_date
            nullable: true
        unlockedDate:
            type: datetime
            column: unlocked_date
            nullable: true
        unlockedUntilDate:
            type: datetime
            column: unlocked_until_date
            nullable: true
        enAttente:
            type: boolean
            column: en_attente
            nullable: false
        pieceJointe:
            type: string
            length: 128
            column: piece_jointe
            nullable: true
    manyToOne:
        topic:
            targetEntity: HopitalNumerique\ForumBundle\Entity\Topic
            cascade: ["persist"]
            inversedBy: posts
            #nullable: true
            joinColumn:
                name: fk_topic_id
                referencedColumnName: id
                onDelete: SET NULL
        createdBy:
            targetEntity: HopitalNumerique\UserBundle\Entity\User
            cascade: []
            nullable: true
            joinColumn:
                name: fk_created_by_user_id
                referencedColumnName: usr_id
                onDelete: CASCADE
        editedBy:
            targetEntity: HopitalNumerique\UserBundle\Entity\User
            cascade: []
            nullable: true
            joinColumn:
                name: fk_edited_by_user_id
                referencedColumnName: usr_id
                onDelete: CASCADE
        deletedBy:
            targetEntity: HopitalNumerique\UserBundle\Entity\User
            cascade: []
            nullable: true
            joinColumn:
                name: fk_deleted_by_user_id
                referencedColumnName: usr_id
                onDelete: CASCADE
        unlockedBy:
            targetEntity: HopitalNumerique\UserBundle\Entity\User
            cascade: []
            nullable: true
            joinColumn:
                name: fk_unlocked_by_user_id
                referencedColumnName: usr_id
                onDelete: CASCADE
