services:
    HopitalNumerique\FichierBundle\Security\File\FileVoter:
        class: HopitalNumerique\FichierBundle\Security\File\FileVoter
        tags:
            - { name: security.voter }
        public: false
