#Index des stats
hopital_numerique_stat_show:
    pattern: /admin/statistiques/show
    defaults: { _controller: HopitalNumeriqueStatBundle:Stats:show}

#-Point dur
hopital_numerique_stat_point_dur_generate_tableau:
    pattern: /admin/statistiques/show/pointdur/generate
    defaults: { _controller: HopitalNumeriqueStatBundle:Pointdur:generateTableau}

hopital_numerique_stat_point_dur_export_csv:
    pattern: /admin/statistiques/show/pointdur/exportCSV
    defaults: { _controller: HopitalNumeriqueStatBundle:Pointdur:exportCSV}

#-Item requete
hopital_numerique_stat_item_requete_generate_tableau:
    pattern: /admin/statistiques/show/itemRequete/generate
    defaults: { _controller: HopitalNumeriqueStatBundle:ItemRequete:generateTableau}

hopital_numerique_stat_item_requete_export_csv:
    pattern: /admin/statistiques/show/itemRequete/exportCSV
    defaults: { _controller: HopitalNumeriqueStatBundle:ItemRequete:exportCSV}

#-Requete fantome
hopital_numerique_stat_requete_fantome_generate_tableau:
    pattern: /admin/statistiques/show/requeteFantome/generate
    defaults: { _controller: HopitalNumeriqueStatBundle:RequeteFantome:generateTableau}

#-Erreurs
hopital_numerique_stat_erreurs_curl:
    pattern: /admin/statistiques/show/erreurs
    defaults: { _controller: HopitalNumeriqueStatBundle:Erreurs:curl}

hopital_numerique_stat_erreurs_curl_generate_tableau:
    pattern: /admin/statistiques/show/erreurs/generate
    defaults: { _controller: HopitalNumeriqueStatBundle:Erreurs:generateTableau}