#Index des stats
hopital_numerique_stat_show:
    pattern: /admin/statistiques/show
    defaults: { _controller: HopitalNumeriqueStatBundle:Stats:show}

#-Erreurs
hopital_numerique_stat_erreurs_export:
    pattern: /admin/statistiques/show/url_errors/export
    defaults: { _controller: HopitalNumeriqueStatBundle:Erreurs:export}
