parameters:
    hopitalnumerique_stat.manager.statrecherche.class: HopitalNumerique\StatBundle\Manager\StatRechercheManager
    hopitalnumerique_stat.manager.stattelechargement.class: HopitalNumerique\StatBundle\Manager\StatTelechargementManager
    hopitalnumerique_stat.manager.errorurl.class: HopitalNumerique\StatBundle\Manager\ErrorUrlManager
    #Listener
    hopitalnumerique_stat.event.listenerstat.class: HopitalNumerique\StatBundle\Event\ListenerStat
    #CronLogger
    hopitalnumerique_stat.logger.cronlogger.class: HopitalNumerique\StatBundle\DependencyInjection\Logger\CronLogger

services:
    hopitalnumerique_stat.manager.statrecherche:
        class: %hopitalnumerique_stat.manager.statrecherche.class%
        arguments: ["@doctrine.orm.entity_manager", "@hopitalnumerique_reference.manager.reference", "@security.context"]
        calls:
           - [ setCache, ["@liip_doctrine_cache.ns.main"] ]
    hopitalnumerique_stat.manager.stattelechargement:
        class: %hopitalnumerique_stat.manager.stattelechargement.class%
        arguments: ["@doctrine.orm.entity_manager", "@security.context"]
        calls:
           - [ setCache, ["@liip_doctrine_cache.ns.main"] ]
    #Listener
    hopitalnumerique_stat.manager.listenerstat.downloadsuccess:
        class: %hopitalnumerique_stat.event.listenerstat.class%
        arguments: ['@hopitalnumerique_stat.manager.stattelechargement']
        tags:
            - { name: kernel.event_listener, event: objet_download_success, method: objetDownloadSuccess }
    #Cronlogger
    hopitalnumerique_stat.logger.cronlogger:
        class: "%hopitalnumerique_stat.logger.cronlogger.class%"
        arguments: ["@logger", "@session"]
    hopitalnumerique_stat.manager.errorurl:
        class: %hopitalnumerique_stat.manager.errorurl.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
           - [ setCache, ["@liip_doctrine_cache.ns.main"] ]
