services:
    stat.manager.error:
        class: HopitalNumerique\StatBundle\Manager\ErrorUrlManager
        arguments:
            - "@doctrine.orm.entity_manager"

    stat.repository.error:
            class: HopitalNumerique\StatBundle\Repository\ErrorUrlRepository
            factory: ["@doctrine.orm.entity_manager", "getRepository"]
            arguments:
                - 'HopitalNumeriqueStatBundle:ErrorUrl'

    stat.service.url_checker:
        class: HopitalNumerique\StatBundle\Service\UrlChecker
        arguments:
            - "@hopitalnumerique_objet.manager.objet"
            - "@hopitalnumerique_objet.manager.contenu"
            - "@stat.repository.error"
            - "@hopitalnumerique_domaine.manager.domaine"
            - "@stat.manager.error"
            - "@autodiag.repository.autodiag"
            - "@hopitalnumerique_questionnaire.manager.questionnaire"

    stat.service.url_exporter:
            class: HopitalNumerique\StatBundle\Service\ErrorUrlExporter
            arguments:
                - "@stat.repository.error"

    stat.repository.search:
        class: 'HopitalNumerique\StatBundle\Repository\StatRechercheRepository'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - 'HopitalNumeriqueStatBundle:StatRecherche'
