
ccdn_forum_admin_board_list:
    pattern: /
    defaults: { _controller: HopitalNumeriqueForumBundle:AdminBoard:list, _locale: fr }

ccdn_forum_admin_board_create:
    pattern: /create
    defaults: { _controller: HopitalNumeriqueForumBundle:AdminBoard:create, _locale: fr }

ccdn_forum_admin_board_create_process:
    pattern: /create/process
    defaults: { _controller: HopitalNumeriqueForumBundle:AdminBoard:createProcess, _locale: fr }

ccdn_forum_admin_board_edit:
    pattern: /edit/{boardId}
    defaults: { _controller: HopitalNumeriqueForumBundle:AdminBoard:edit, _locale: fr }

ccdn_forum_admin_board_edit_process:
    pattern: /edit/{boardId}/process
    defaults: { _controller: HopitalNumeriqueForumBundle:AdminBoard:editProcess, _locale: fr }

ccdn_forum_admin_board_delete:
    pattern: /delete/{boardId}
    defaults: { _controller: HopitalNumeriqueForumBundle:AdminBoard:delete, _locale: fr }

ccdn_forum_admin_board_delete_process:
    pattern: /delete/{boardId}/process
    defaults: { _controller: HopitalNumeriqueForumBundle:AdminBoard:deleteProcess, _locale: fr }

ccdn_forum_admin_board_reorder_up:
    pattern: /reorder/{boardId}/up
    defaults: { _controller: HopitalNumeriqueForumBundle:AdminBoard:reorder, _locale: fr, direction: 0 }

ccdn_forum_admin_board_reorder_down:
    pattern: /reorder/{boardId}/down
    defaults: { _controller: HopitalNumeriqueForumBundle:AdminBoard:reorder, _locale: fr, direction: 1 }
