
ccdn_forum_moderator_topic_close:
    pattern: /{topicId}/close
    defaults: { _controller: HopitalNumeriqueForumBundle:ModeratorTopic:close, _locale: fr, forumName: Public }

ccdn_forum_moderator_topic_reopen:
    pattern: /{topicId}/reopen
    defaults: { _controller: HopitalNumeriqueForumBundle:ModeratorTopic:reopen, _locale: fr, forumName: Public }

ccdn_forum_moderator_topic_sticky:
    pattern: /{topicId}/sticky
    defaults: { _controller: HopitalNumeriqueForumBundle:ModeratorTopic:sticky, _locale: fr, forumName: Public }

ccdn_forum_moderator_topic_unsticky:
    pattern: /{topicId}/unsticky
    defaults: { _controller: HopitalNumeriqueForumBundle:ModeratorTopic:unsticky, _locale: fr, forumName: Public }

ccdn_forum_moderator_topic_delete:
    pattern: /{topicId}/delete
    defaults: { _controller: HopitalNumeriqueForumBundle:ModeratorTopic:delete, _locale: fr, forumName: Public }

ccdn_forum_moderator_topic_delete_process:
    pattern: /{topicId}/delete/process
    defaults: { _controller: HopitalNumeriqueForumBundle:ModeratorTopic:deleteProcess, _locale: fr, forumName: Public }

ccdn_forum_moderator_topic_restore:
    pattern: /{topicId}/restore
    defaults: { _controller: HopitalNumeriqueForumBundle:ModeratorTopic:restore, _locale: fr, forumName: Public }

ccdn_forum_moderator_topic_change_board:
    pattern: /{topicId}/change-board
    defaults: { _controller: HopitalNumeriqueForumBundle:ModeratorTopic:changeBoard, _locale: fr, forumName: Public }

ccdn_forum_moderator_topic_change_board_process:
    pattern: /{topicId}/change-board/process
    defaults: { _controller: HopitalNumeriqueForumBundle:ModeratorTopic:changeBoardProcess, _locale: fr, forumName: Public }
