#
# CRUD
#
ccdn_forum_user_post_show:
    pattern: /{postId}
    defaults: { _controller: CCDNForumForumBundle:UserPost:show, _locale: fr, forumName: Public }

ccdn_forum_user_post_edit:
    pattern: /{postId}/edit
    defaults: { _controller: CCDNForumForumBundle:UserPost:edit, _locale: fr, forumName: Public }

ccdn_forum_user_post_edit_process:
    pattern: /{postId}/edit/process
    defaults: { _controller: HopitalNumeriqueForumBundle:UserPost:editProcess, _locale: fr, forumName: Public }

ccdn_forum_user_post_delete:
    pattern: /{postId}/delete
    defaults: { _controller: CCDNForumForumBundle:UserPost:delete, _locale: fr, forumName: Public }

ccdn_forum_user_post_delete_process:
    pattern: /{postId}/delete/process
    defaults: { _controller: CCDNForumForumBundle:UserPost:deleteProcess, _locale: fr, forumName: Public }

ccdn_forum_user_post_download:
    pattern: /post/{post}/telecharge
    defaults: { _controller: HopitalNumeriqueForumBundle:UserPost:downloadPieceJointe, _locale: fr }
    methods: GET

ccdn_forum_user_post_activation_enattente:
    pattern: /post/{post}/activation
    defaults: { _controller: HopitalNumeriqueForumBundle:UserPost:activierPostEnAttente, _locale: fr, forumName: Public }
    methods: GET
