
#ccdn_forum_user_category_index:
#    pattern: /index
#    defaults: { _controller: CCDNForumForumBundle:UserCategory:index, _locale: fr, forumName: default }

ccdn_forum_user_category_index:
    path:     /{forumName}
    defaults: { _controller: CCDNForumForumBundle:UserCategory:index, _locale: fr, forumName: Test } #Mettre le nom du forum HN

ccdn_forum_user_category_show:
    path:     /{forumName}/category/{categoryId}
    defaults: { _controller: CCDNForumForumBundle:UserCategory:show, _locale: fr, forumName: Test } #Mettre le nom du forum HN
