
ccdn_forum_user_subscription_index:
    pattern: /
    defaults: { _controller: HopitalNumeriqueForumBundle:UserSubscription:index, _locale: fr }

ccdn_forum_user_subscription_subscribe:
    pattern: /topic/{topicId}/subscribe
    defaults: { _controller: CCDNForumForumBundle:UserSubscription:subscribe, _locale: fr }

ccdn_forum_user_subscription_unsubscribe:
    pattern: /topic/{topicId}/unsubscribe
    defaults: { _controller: CCDNForumForumBundle:UserSubscription:unsubscribe, _locale: fr }

ccdn_forum_user_board_subscription_subscribe:
    pattern: /board/{board}/subscribe
    defaults: { _controller: CCDNForumForumBundle:UserSubscription:subscribeBoard, _locale: fr }
    methods: GET

ccdn_forum_user_board_subscription_unsubscribe:
    pattern: /board/{board}/unsubscribe
    defaults: { _controller: CCDNForumForumBundle:UserSubscription:unsubscribeBoard, _locale: fr }
    methods: GET
