
#
# CRUD
#
ccdn_forum_user_topic_show:
    pattern: /{topicId}
    defaults: { _controller: HopitalNumeriqueForumBundle:UserTopic:show, _locale: fr, forumName: Public }

ccdn_forum_user_topic_create:
    pattern: /create/for-board/{boardId}
    defaults: { _controller: CCDNForumForumBundle:UserTopic:create, _locale: fr, forumName: Public }

ccdn_forum_user_topic_create_process:
    pattern: /create/for-board/{boardId}/process
    defaults: { _controller: CCDNForumForumBundle:UserTopic:createProcess, _locale: fr, forumName: Public }

ccdn_forum_user_topic_reply:
    pattern: /{topicId}/reply
    defaults: { _controller: CCDNForumForumBundle:UserTopic:reply, _locale: fr, forumName: Public }

ccdn_forum_user_topic_reply_process:
    pattern: /{topicId}/reply/process
    defaults: { _controller: CCDNForumForumBundle:UserTopic:replyProcess, _locale: fr, forumName: Public }

hopitalnumerique_forum_post_move:
    pattern: /{topicId}/move
    defaults: { _controller: CCDNForumForumBundle:UserTopic:deplacerTopic, _locale: fr, forumName: Public }

#Reference
hopitalnumerique_forum_reference_topic:
    pattern:  /reference/topic/{id}
    defaults: { _controller: "HopitalNumeriqueForumBundle:Reference:topic", id:1, forumName: Public }
    requirements:
        id: \d+

hopitalnumerique_forum_reference_topic_own:
    pattern:  /reference/topic-own/{id}
    defaults: { _controller: "HopitalNumeriqueForumBundle:Reference:topicOwn", id:1, forumName: Public  }
    requirements:
        id: \d+

hopitalnumerique_forum_reference_topic_save:
    pattern:  /reference/save/topic/{id}
    defaults: { _controller: "HopitalNumeriqueForumBundle:Reference:saveTopic", forumName: Public  }
    requirements:
        id: \d+

hopitalnumerique_forum_reference_contenu:
    pattern:  /reference/contenu/{id}
    defaults: { _controller: "HopitalNumeriqueForumBundle:Reference:contenu", id:1, forumName: Public  }
    requirements:
        id: \d+

hopitalnumerique_forum_reference_contenu_own:
    pattern:  /reference/contenu_own/{id}
    defaults: { _controller: "HopitalNumeriqueForumBundle:Reference:contenuOwn", id:1, forumName: Public  }
    requirements:
        id: \d+

hopitalnumerique_forum_reference_contenu_save:
    pattern:  /reference/save/contenu
    defaults: { _controller: "HopitalNumeriqueForumBundle:Reference:saveContenu", forumName: Public  }
