global:
    boost:
        title: 2
    exact_result_score: 100
    highlights:
        enabled: true
        tag: span
    query:
        exact:
            enabled: true
            boost: 1000
            fuzziness:
                enabled: false
        similar:
            enabled: true
            fuzziness:
                enabled: true
                value: AUTO
                prefix: 2
                expansion: 5
        suggestion:
            enabled: true
            fuzziness:
                enabled: true
                value: AUTO
                prefix: 2
                expansion: 5

autodiag:
    boost:
        title: 3
