<?php

namespace HopitalNumerique\RechercheBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExpBesoinGestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpBesoinGestionRepository extends EntityRepository
{
    /**
     * Récupère les données du grid sous forme de tableau correctement formaté
     *
     * @return Query Builder
     */
    public function getDatasForGrid($domainesIds, $condition = null)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('expbg.id, expbg.nom, domaine.nom as domaineNom')
            ->from('HopitalNumeriqueRechercheBundle:ExpBesoinGestion', 'expbg')
            ->leftJoin('expbg.domaines', 'domaine')
                ->where($qb->expr()->orX(
                    $qb->expr()->in('domaine.id', ':domainesId'),
                    $qb->expr()->isNull('domaine.id')
                ))
                ->setParameter('domainesId', $domainesIds)
            ->orderBy('expbg.nom');
            
        return $qb;
    }
}
