<?php

namespace HopitalNumerique\RechercheBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExpBesoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpBesoinRepository extends EntityRepository
{
    /**
     * Compte le nombre de chapitres lié à loutil
     *
     * @param Outil $outil Outil
     *
     * @return QueryBuilder
     */
    public function countQuestions()
    {
        return $this->_em->createQueryBuilder()
                         ->select('count(expb)')
                         ->from('\HopitalNumerique\RechercheBundle\Entity\ExpBesoin', 'expb');
    }
}
