<?php

namespace HopitalNumerique\RechercheBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StatClicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatClicRepository extends EntityRepository
{
    /**
     * Retourne la liste des clicks par réponse
     *
     * @return QueryBuilder
     */
    public function getNbNoteByReponse( $dateDebut, $dateFin )
    {
        $qb = $this->_em->createQueryBuilder()
                         ->select('count(clic) as nbClic, reponse.id, reponse.libelle as reponseLibelle, question.libelle as questionLibelle, question.order as questionOrder')
                         ->from('\HopitalNumerique\RechercheBundle\Entity\StatClic', 'clic')
                         ->leftJoin('clic.reponse', 'reponse')
                         ->leftJoin('reponse.question', 'question');

                         if(!is_null($dateDebut))
                         {
                            $qb->andWhere('clic.dateClic >= :dateDebut')
                               ->setParameter('dateDebut', $dateDebut );
                         }
                         if(!is_null($dateFin))
                         {
                            $qb->andWhere('clic.dateClic <= :dateFin')
                               ->setParameter('dateFin', $dateFin );
                         }
                         
                         $qb->groupBy('reponse.id')
                            ->orderBy('nbClic', 'DESC');

        return $qb;
    }
}
